/**
 * Tencent is pleased to support the open source community by making Tars available.
 *
 * Copyright (C) 2016THL A29 Limited, a Tencent company. All rights reserved.
 *
 * Licensed under the BSD 3-Clause License (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * https://opensource.org/licenses/BSD-3-Clause
 */

// Package node generates Node.js/TypeScript code from Tars IDL
package node

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/TarsCloud/TarsCpp/tools/tarsc-go/pkg/ast"
)

// Generator generates Node.js code
type Generator struct {
	baseDir string
}

// NewGenerator creates a new Node.js generator
func NewGenerator(baseDir string) *Generator {
	return &Generator{baseDir: baseDir}
}

// Generate generates Node.js code for the document
func (g *Generator) Generate(doc *ast.Document, baseName string) error {
	for _, ns := range doc.Namespaces {
		// Generate JavaScript
		if err := g.generateJS(doc, ns, baseName); err != nil {
			return err
		}
		// Generate TypeScript definitions
		if err := g.generateDTS(doc, ns, baseName); err != nil {
			return err
		}
	}
	return nil
}

func (g *Generator) generateJS(doc *ast.Document, ns *ast.Namespace, baseName string) error {
	var sb strings.Builder

	// Header
	sb.WriteString("// Generated by tarsc - Tars IDL Compiler\n")
	sb.WriteString("// DO NOT EDIT!\n\n")

	sb.WriteString("'use strict';\n\n")

	// Require statements
	sb.WriteString("const TarsStream = require('@aspect/tars-stream');\n")
	sb.WriteString("const TarsClient = require('@aspect/tars-rpc').client;\n\n")

	// Module exports
	sb.WriteString(fmt.Sprintf("const %s = {};\n\n", ns.Name))

	// Generate enums
	for _, e := range ns.Enums {
		sb.WriteString(g.generateEnumJS(e, ns.Name))
		sb.WriteString("\n")
	}

	// Generate structs
	for _, s := range ns.Structs {
		sb.WriteString(g.generateStructJS(s, ns.Name))
		sb.WriteString("\n")
	}

	// Generate interfaces
	for _, iface := range ns.Interfaces {
		sb.WriteString(g.generateInterfaceJS(iface, ns.Name))
		sb.WriteString("\n")
	}

	sb.WriteString(fmt.Sprintf("module.exports = %s;\n", ns.Name))

	// Write file
	dir := filepath.Join(g.baseDir, ns.Name)
	if err := os.MkdirAll(dir, 0755); err != nil {
		return err
	}

	filePath := filepath.Join(dir, baseName+".js")
	return os.WriteFile(filePath, []byte(sb.String()), 0644)
}

func (g *Generator) generateDTS(doc *ast.Document, ns *ast.Namespace, baseName string) error {
	var sb strings.Builder

	// Header
	sb.WriteString("// Generated by tarsc - Tars IDL Compiler\n")
	sb.WriteString("// DO NOT EDIT!\n\n")

	sb.WriteString("import * as TarsStream from '@aspect/tars-stream';\n\n")

	sb.WriteString(fmt.Sprintf("declare namespace %s {\n\n", ns.Name))

	// Generate enums
	for _, e := range ns.Enums {
		sb.WriteString(g.generateEnumDTS(e))
		sb.WriteString("\n")
	}

	// Generate interfaces (structs)
	for _, s := range ns.Structs {
		sb.WriteString(g.generateStructDTS(s))
		sb.WriteString("\n")
	}

	// Generate service interfaces
	for _, iface := range ns.Interfaces {
		sb.WriteString(g.generateInterfaceDTS(iface))
		sb.WriteString("\n")
	}

	sb.WriteString("}\n\n")
	sb.WriteString(fmt.Sprintf("export = %s;\n", ns.Name))

	// Write file
	dir := filepath.Join(g.baseDir, ns.Name)
	filePath := filepath.Join(dir, baseName+".d.ts")
	return os.WriteFile(filePath, []byte(sb.String()), 0644)
}

func (g *Generator) generateEnumJS(e *ast.Enum, nsName string) string {
	var sb strings.Builder

	sb.WriteString(fmt.Sprintf("%s.%s = {\n", nsName, e.Name))
	for _, m := range e.Members {
		sb.WriteString(fmt.Sprintf("    %s: %d,\n", m.Name, m.Value))
	}
	sb.WriteString("};\n")

	return sb.String()
}

func (g *Generator) generateEnumDTS(e *ast.Enum) string {
	var sb strings.Builder

	sb.WriteString(fmt.Sprintf("    enum %s {\n", e.Name))
	for _, m := range e.Members {
		sb.WriteString(fmt.Sprintf("        %s = %d,\n", m.Name, m.Value))
	}
	sb.WriteString("    }\n")

	return sb.String()
}

func (g *Generator) generateStructJS(s *ast.Struct, nsName string) string {
	var sb strings.Builder

	sb.WriteString(fmt.Sprintf("%s.%s = class {\n", nsName, s.Name))

	// Constructor
	sb.WriteString("    constructor() {\n")
	for _, f := range s.Fields {
		defaultVal := g.getJSDefault(f)
		sb.WriteString(fmt.Sprintf("        this.%s = %s;\n", f.Name, defaultVal))
	}
	sb.WriteString("    }\n\n")

	// _writeTo method
	sb.WriteString("    _writeTo(os) {\n")
	for _, f := range s.Fields {
		sb.WriteString(fmt.Sprintf("        os.write%s(%d, this.%s);\n", g.getWriteMethod(f.Type), f.Tag, f.Name))
	}
	sb.WriteString("    }\n\n")

	// _readFrom method
	sb.WriteString("    _readFrom(is) {\n")
	for _, f := range s.Fields {
		required := "true"
		if !f.IsRequired {
			required = "false"
		}
		sb.WriteString(fmt.Sprintf("        this.%s = is.read%s(%d, %s, this.%s);\n", f.Name, g.getReadMethod(f.Type), f.Tag, required, f.Name))
	}
	sb.WriteString("    }\n")

	sb.WriteString("};\n")

	return sb.String()
}

func (g *Generator) generateStructDTS(s *ast.Struct) string {
	var sb strings.Builder

	sb.WriteString(fmt.Sprintf("    class %s {\n", s.Name))

	for _, f := range s.Fields {
		tsType := g.toTSType(f.Type)
		sb.WriteString(fmt.Sprintf("        %s: %s;\n", f.Name, tsType))
	}

	sb.WriteString("        _writeTo(os: TarsStream.TarsOutputStream): void;\n")
	sb.WriteString("        _readFrom(is: TarsStream.TarsInputStream): void;\n")
	sb.WriteString("    }\n")

	return sb.String()
}

func (g *Generator) generateInterfaceJS(iface *ast.Interface, nsName string) string {
	var sb strings.Builder

	// Proxy class
	sb.WriteString(fmt.Sprintf("%s.%sProxy = class extends TarsClient.ServantProxy {\n", nsName, iface.Name))

	for _, op := range iface.Operations {
		sb.WriteString(g.generateMethodJS(op))
		sb.WriteString("\n")
	}

	sb.WriteString("};\n")

	return sb.String()
}

func (g *Generator) generateInterfaceDTS(iface *ast.Interface) string {
	var sb strings.Builder

	sb.WriteString(fmt.Sprintf("    class %sProxy {\n", iface.Name))

	for _, op := range iface.Operations {
		sb.WriteString(g.generateMethodDTS(op))
	}

	sb.WriteString("    }\n")

	return sb.String()
}

func (g *Generator) generateMethodJS(op *ast.Operation) string {
	var sb strings.Builder

	var params []string
	for _, p := range op.Params {
		if !p.IsOut {
			params = append(params, p.Name)
		}
	}

	sb.WriteString(fmt.Sprintf("    %s(%s) {\n", op.Name, strings.Join(params, ", ")))
	sb.WriteString("        const os = new TarsStream.TarsOutputStream();\n")

	// Write input parameters
	tagNum := 1
	for _, p := range op.Params {
		if !p.IsOut {
			sb.WriteString(fmt.Sprintf("        os.write%s(%d, %s);\n", g.getWriteMethod(p.Type), tagNum, p.Name))
		}
		tagNum++
	}

	sb.WriteString(fmt.Sprintf("        return this._invoke('%s', os.getBinBuffer()).then(rsp => {\n", op.Name))
	sb.WriteString("            const is = new TarsStream.TarsInputStream(rsp.response.sBuffer);\n")

	// Read output
	hasReturn := false
	if op.ReturnType != nil {
		if bt, ok := op.ReturnType.(*ast.BuiltinType); !ok || bt.Kind != ast.KindVoid {
			hasReturn = true
			sb.WriteString(fmt.Sprintf("            const ret = is.read%s(0, true);\n", g.getReadMethod(op.ReturnType)))
		}
	}

	// Read out parameters
	var outParams []string
	tagNum = 1
	for _, p := range op.Params {
		if p.IsOut {
			sb.WriteString(fmt.Sprintf("            const %s = is.read%s(%d, true);\n", p.Name, g.getReadMethod(p.Type), tagNum))
			outParams = append(outParams, p.Name)
		}
		tagNum++
	}

	// Return
	var returns []string
	if hasReturn {
		returns = append(returns, "ret")
	}
	returns = append(returns, outParams...)

	if len(returns) == 1 {
		sb.WriteString(fmt.Sprintf("            return %s;\n", returns[0]))
	} else if len(returns) > 1 {
		sb.WriteString(fmt.Sprintf("            return { %s };\n", strings.Join(returns, ", ")))
	}

	sb.WriteString("        });\n")
	sb.WriteString("    }\n")

	return sb.String()
}

func (g *Generator) generateMethodDTS(op *ast.Operation) string {
	var sb strings.Builder

	var params []string
	for _, p := range op.Params {
		if !p.IsOut {
			params = append(params, fmt.Sprintf("%s: %s", p.Name, g.toTSType(p.Type)))
		}
	}

	returnType := "void"
	if op.ReturnType != nil {
		if bt, ok := op.ReturnType.(*ast.BuiltinType); !ok || bt.Kind != ast.KindVoid {
			returnType = g.toTSType(op.ReturnType)
		}
	}

	sb.WriteString(fmt.Sprintf("        %s(%s): Promise<%s>;\n", op.Name, strings.Join(params, ", "), returnType))

	return sb.String()
}

func (g *Generator) toTSType(t ast.Type) string {
	if t == nil {
		return "void"
	}

	switch v := t.(type) {
	case *ast.BuiltinType:
		switch v.Kind {
		case ast.KindVoid:
			return "void"
		case ast.KindBool:
			return "boolean"
		case ast.KindByte, ast.KindShort, ast.KindInt, ast.KindLong, ast.KindFloat, ast.KindDouble:
			return "number"
		case ast.KindString:
			return "string"
		}
	case *ast.VectorType:
		if bt, ok := v.ElementType.(*ast.BuiltinType); ok && bt.Kind == ast.KindByte {
			return "Buffer"
		}
		return fmt.Sprintf("Array<%s>", g.toTSType(v.ElementType))
	case *ast.MapType:
		return fmt.Sprintf("Map<%s, %s>", g.toTSType(v.KeyType), g.toTSType(v.ValueType))
	case *ast.CustomType:
		return v.TypeName_
	}
	return "any"
}

func (g *Generator) getJSDefault(f *ast.Field) string {
	if f.HasDefault && f.DefaultValue != "" {
		return f.DefaultValue
	}

	switch v := f.Type.(type) {
	case *ast.BuiltinType:
		switch v.Kind {
		case ast.KindBool:
			return "false"
		case ast.KindString:
			return "''"
		case ast.KindByte, ast.KindShort, ast.KindInt, ast.KindLong:
			return "0"
		case ast.KindFloat, ast.KindDouble:
			return "0.0"
		}
	case *ast.VectorType:
		return "[]"
	case *ast.MapType:
		return "new Map()"
	case *ast.CustomType:
		return fmt.Sprintf("new %s()", v.TypeName_)
	}
	return "null"
}

func (g *Generator) getWriteMethod(t ast.Type) string {
	switch v := t.(type) {
	case *ast.BuiltinType:
		switch v.Kind {
		case ast.KindBool:
			return "Boolean"
		case ast.KindByte:
			return "Int8"
		case ast.KindShort:
			if v.IsUnsigned {
				return "UInt16"
			}
			return "Int16"
		case ast.KindInt:
			if v.IsUnsigned {
				return "UInt32"
			}
			return "Int32"
		case ast.KindLong:
			if v.IsUnsigned {
				return "UInt64"
			}
			return "Int64"
		case ast.KindFloat:
			return "Float"
		case ast.KindDouble:
			return "Double"
		case ast.KindString:
			return "String"
		}
	case *ast.VectorType:
		return "Vector"
	case *ast.MapType:
		return "Map"
	case *ast.CustomType:
		return "Struct"
	}
	return "Int32"
}

func (g *Generator) getReadMethod(t ast.Type) string {
	return g.getWriteMethod(t)
}
