/**
 * Tencent is pleased to support the open source community by making Tars available.
 *
 * Copyright (C) 2016THL A29 Limited, a Tencent company. All rights reserved.
 *
 * Licensed under the BSD 3-Clause License (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * https://opensource.org/licenses/BSD-3-Clause
 */

// Package java generates Java code from Tars IDL
package java

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/TarsCloud/TarsCpp/tools/tarsc-go/pkg/ast"
)

// Generator generates Java code
type Generator struct {
	baseDir       string
	packagePrefix string
	isServant     bool // true = generate Servant interface, false = generate Prx interface
	enums         map[string]bool
}

// NewGenerator creates a new Java generator
func NewGenerator(baseDir string) *Generator {
	return &Generator{
		baseDir:       baseDir,
		packagePrefix: "",
		isServant:     false,
		enums:         make(map[string]bool),
	}
}

// SetPackagePrefix sets the package prefix
func (g *Generator) SetPackagePrefix(prefix string) {
	g.packagePrefix = prefix
}

// SetServantMode sets whether to generate Servant or Prx interface
func (g *Generator) SetServantMode(isServant bool) {
	g.isServant = isServant
}

// Generate generates Java code for the document
func (g *Generator) Generate(doc *ast.Document, baseName string) error {
	// First pass: collect all enums
	for _, ns := range doc.Namespaces {
		for _, e := range ns.Enums {
			g.enums[e.Name] = true
			g.enums[ns.Name+"::"+e.Name] = true
		}
	}

	for _, ns := range doc.Namespaces {
		if err := g.generateNamespace(doc, ns); err != nil {
			return err
		}
	}
	return nil
}

func (g *Generator) generateNamespace(doc *ast.Document, ns *ast.Namespace) error {
	// Generate constants class
	if len(ns.Consts) > 0 {
		if err := g.generateConstFile(ns); err != nil {
			return err
		}
	}

	// Generate each struct as a separate file
	for _, s := range ns.Structs {
		if err := g.generateStructFile(ns, s); err != nil {
			return err
		}
	}

	// Generate each enum as a separate file
	for _, e := range ns.Enums {
		if err := g.generateEnumFile(ns, e); err != nil {
			return err
		}
	}

	// Generate each interface
	for _, iface := range ns.Interfaces {
		if g.isServant {
			if err := g.generateServantFile(ns, iface); err != nil {
				return err
			}
		} else {
			// Generate Prx interface
			if err := g.generatePrxFile(ns, iface); err != nil {
				return err
			}
			// Generate PrxCallback class
			if err := g.generatePrxCallbackFile(ns, iface); err != nil {
				return err
			}
			// Also generate Servant interface
			if err := g.generateServantFile(ns, iface); err != nil {
				return err
			}
		}
	}

	return nil
}

func (g *Generator) printHead(sb *strings.Builder) {
	sb.WriteString("// **********************************************************************\n")
	sb.WriteString("// This file was generated by a TARS parser!\n")
	sb.WriteString("// TARS version 1.7.4.\n")
	sb.WriteString("// **********************************************************************\n\n")
}

func (g *Generator) getPackageName(ns *ast.Namespace) string {
	if g.packagePrefix != "" {
		prefix := g.packagePrefix
		if !strings.HasSuffix(prefix, ".") {
			prefix += "."
		}
		return prefix + strings.ToLower(ns.Name)
	}
	return strings.ToLower(ns.Name)
}

func (g *Generator) generateConstFile(ns *ast.Namespace) error {
	var sb strings.Builder

	g.printHead(&sb)

	packageName := g.getPackageName(ns)
	sb.WriteString(fmt.Sprintf("package %s;\n\n", packageName))

	constClass := firstUpStr(ns.Name) + "Const"
	sb.WriteString(fmt.Sprintf("public interface %s {\n\n", constClass))

	for _, c := range ns.Consts {
		javaType := g.toJavaType(c.Type)
		value := c.Value
		// Add type suffix if needed
		if bt, ok := c.Type.(*ast.BuiltinType); ok {
			switch bt.Kind {
			case ast.KindLong:
				if !strings.HasSuffix(value, "L") && !strings.HasSuffix(value, "l") {
					value += "L"
				}
			case ast.KindFloat:
				if !strings.HasSuffix(value, "F") && !strings.HasSuffix(value, "f") {
					value += "F"
				}
			case ast.KindDouble:
				if !strings.HasSuffix(value, "D") && !strings.HasSuffix(value, "d") {
					value += "D"
				}
			}
		}
		sb.WriteString(fmt.Sprintf("    public static final %s %s = %s;\n\n", javaType, c.Name, value))
	}

	sb.WriteString("}\n")

	// Write file
	dir := filepath.Join(g.baseDir, strings.ReplaceAll(packageName, ".", "/"))
	if err := os.MkdirAll(dir, 0755); err != nil {
		return err
	}

	filePath := filepath.Join(dir, constClass+".java")
	return os.WriteFile(filePath, []byte(sb.String()), 0644)
}

func (g *Generator) generateStructFile(ns *ast.Namespace, s *ast.Struct) error {
	var sb strings.Builder

	g.printHead(&sb)

	packageName := g.getPackageName(ns)
	sb.WriteString(fmt.Sprintf("package %s;\n\n", packageName))

	// Imports
	sb.WriteString("import com.qq.tars.protocol.util.*;\n")
	sb.WriteString("import com.qq.tars.protocol.annotation.*;\n")
	sb.WriteString("import com.qq.tars.protocol.tars.*;\n")
	sb.WriteString("import com.qq.tars.protocol.tars.annotation.*;\n\n")

	// Class declaration
	sb.WriteString("@TarsStruct\n")
	if len(s.Keys) > 0 {
		sb.WriteString(fmt.Sprintf("public class %s implements Comparable<%s> {\n\n", s.Name, s.Name))
	} else {
		sb.WriteString(fmt.Sprintf("public class %s {\n\n", s.Name))
	}

	// Fields with annotations
	for _, f := range s.Fields {
		javaType := g.toJavaType(f.Type)
		required := "false"
		if f.IsRequired {
			required = "true"
		}
		sb.WriteString(fmt.Sprintf("    @TarsStructProperty(order = %d, isRequire = %s)\n", f.Tag, required))
		sb.WriteString(fmt.Sprintf("    public %s %s", javaType, f.Name))

		defaultVal := g.getJavaDefault(f)
		sb.WriteString(fmt.Sprintf(" = %s", defaultVal))
		sb.WriteString(";\n\n")
	}

	// IsSet fields for primitive types
	optionalCount := 0
	for _, f := range s.Fields {
		if !g.typeCanBeNull(f.Type) {
			sb.WriteString(fmt.Sprintf("    private static final int __%s_ISSET_ID = %d;\n", strings.ToUpper(f.Name), optionalCount))
			optionalCount++
		}
	}

	// IsSet bit field
	if optionalCount > 0 {
		sb.WriteString("\n")
		if optionalCount <= 8 {
			sb.WriteString("    private byte __isset_bitfield = 0;\n\n")
		} else if optionalCount <= 16 {
			sb.WriteString("    private short __isset_bitfield = 0;\n\n")
		} else if optionalCount <= 32 {
			sb.WriteString("    private int __isset_bitfield = 0;\n\n")
		} else if optionalCount <= 64 {
			sb.WriteString("    private long __isset_bitfield = 0;\n\n")
		} else {
			sb.WriteString(fmt.Sprintf("    private java.util.BitSet __isset_bit_vector = new java.util.BitSet(%d);\n\n", optionalCount))
		}
	}

	// Default constructor
	sb.WriteString(fmt.Sprintf("    public %s() {\n    }\n\n", s.Name))

	// Full constructor
	if len(s.Fields) > 0 {
		sb.WriteString(fmt.Sprintf("    public %s(", s.Name))
		for i, f := range s.Fields {
			if i > 0 {
				sb.WriteString(", ")
			}
			sb.WriteString(fmt.Sprintf("%s %s", g.toJavaType(f.Type), f.Name))
		}
		sb.WriteString(") {\n")
		for _, f := range s.Fields {
			sb.WriteString(fmt.Sprintf("        this.%s = %s;\n", f.Name, f.Name))
		}
		sb.WriteString("    }\n\n")
	}

	// Getters, Setters, and isSet methods
	for _, f := range s.Fields {
		javaType := g.toJavaType(f.Type)
		fieldName := f.Name
		methodName := firstUpStr(fieldName)

		// Getter
		getterPrefix := "get"
		if bt, ok := f.Type.(*ast.BuiltinType); ok && bt.Kind == ast.KindBool {
			if !strings.HasPrefix(fieldName, "is") {
				getterPrefix = "is"
			}
		}
		sb.WriteString(fmt.Sprintf("    public %s %s%s() {\n", javaType, getterPrefix, methodName))
		sb.WriteString(fmt.Sprintf("        return %s;\n", fieldName))
		sb.WriteString("    }\n\n")

		// Setter
		sb.WriteString(fmt.Sprintf("    public void set%s(%s %s) {\n", methodName, javaType, fieldName))
		sb.WriteString(fmt.Sprintf("        this.%s = %s;\n", fieldName, fieldName))
		if !g.typeCanBeNull(f.Type) {
			sb.WriteString(fmt.Sprintf("        set%sIsSet(true);\n", methodName))
		}
		sb.WriteString("    }\n\n")

		// isSet method
		sb.WriteString(fmt.Sprintf("    /** Returns true if field %s is set (has been assigned a value) and false otherwise */\n", fieldName))
		sb.WriteString(fmt.Sprintf("    public boolean isSet%s() {\n", methodName))
		if g.typeCanBeNull(f.Type) {
			sb.WriteString(fmt.Sprintf("        return this.%s != null;\n", fieldName))
		} else if optionalCount <= 64 {
			sb.WriteString(fmt.Sprintf("        return EncodingUtils.testBit(__isset_bitfield, __%s_ISSET_ID);\n", strings.ToUpper(fieldName)))
		} else {
			sb.WriteString(fmt.Sprintf("        return __isset_bit_vector.get(__%s_ISSET_ID);\n", strings.ToUpper(fieldName)))
		}
		sb.WriteString("    }\n\n")

		// setFieldIsSet method
		sb.WriteString(fmt.Sprintf("    public void set%sIsSet(boolean value) {\n", methodName))
		if g.typeCanBeNull(f.Type) {
			sb.WriteString("        if (!value) {\n")
			sb.WriteString(fmt.Sprintf("            this.%s = null;\n", fieldName))
			sb.WriteString("        }\n")
		} else if optionalCount <= 64 {
			sb.WriteString(fmt.Sprintf("        __isset_bitfield = EncodingUtils.setBit(__isset_bitfield, __%s_ISSET_ID, value);\n", strings.ToUpper(fieldName)))
		} else {
			sb.WriteString(fmt.Sprintf("        __isset_bit_vector.set(__%s_ISSET_ID, value);\n", strings.ToUpper(fieldName)))
		}
		sb.WriteString("    }\n\n")
	}

	// compareTo() for structs with keys
	if len(s.Keys) > 0 {
		sb.WriteString("    @Override\n")
		sb.WriteString(fmt.Sprintf("    public int compareTo(%s o) {\n", s.Name))
		sb.WriteString("        int c = 0;\n")
		for _, k := range s.Keys {
			sb.WriteString(fmt.Sprintf("        if ((c = TarsUtil.compareTo(%s, o.%s)) != 0) {\n", k, k))
			sb.WriteString("            return c;\n")
			sb.WriteString("        }\n")
		}
		sb.WriteString("        return 0;\n")
		sb.WriteString("    }\n\n")
	}

	// hashCode()
	sb.WriteString("    @Override\n")
	sb.WriteString("    public int hashCode() {\n")
	sb.WriteString("        final int prime = 31;\n")
	sb.WriteString("        int result = 1;\n")
	if len(s.Keys) > 0 {
		for _, k := range s.Keys {
			sb.WriteString(fmt.Sprintf("        result = prime * result + TarsUtil.hashCode(%s);\n", k))
		}
	} else {
		for _, f := range s.Fields {
			sb.WriteString(fmt.Sprintf("        result = prime * result + TarsUtil.hashCode(%s);\n", f.Name))
		}
	}
	sb.WriteString("        return result;\n")
	sb.WriteString("    }\n\n")

	// equals()
	sb.WriteString("    @Override\n")
	sb.WriteString("    public boolean equals(Object obj) {\n")
	sb.WriteString("        if (this == obj) {\n")
	sb.WriteString("            return true;\n")
	sb.WriteString("        }\n")
	sb.WriteString("        if (obj == null) {\n")
	sb.WriteString("            return false;\n")
	sb.WriteString("        }\n")
	sb.WriteString(fmt.Sprintf("        if (!(obj instanceof %s)) {\n", s.Name))
	sb.WriteString("            return false;\n")
	sb.WriteString("        }\n")
	sb.WriteString(fmt.Sprintf("        %s other = (%s) obj;\n", s.Name, s.Name))
	sb.WriteString("        return (\n")
	if len(s.Keys) > 0 {
		for i, k := range s.Keys {
			suffix := ""
			if i < len(s.Keys)-1 {
				suffix = " &&"
			}
			sb.WriteString(fmt.Sprintf("            TarsUtil.equals(%s, other.%s)%s\n", k, k, suffix))
		}
	} else {
		for i, f := range s.Fields {
			suffix := ""
			if i < len(s.Fields)-1 {
				suffix = " &&"
			}
			sb.WriteString(fmt.Sprintf("            TarsUtil.equals(%s, other.%s)%s\n", f.Name, f.Name, suffix))
		}
	}
	sb.WriteString("        );\n")
	sb.WriteString("    }\n\n")

	// toString()
	sb.WriteString("    @Override\n")
	sb.WriteString("    public String toString() {\n")
	sb.WriteString(fmt.Sprintf("        StringBuilder sb = new StringBuilder(\"%s(\");\n", s.Name))
	sb.WriteString("        boolean first = true;\n\n")
	for i, f := range s.Fields {
		couldBeUnset := !f.IsRequired
		indent := "        "
		if couldBeUnset {
			sb.WriteString(fmt.Sprintf("        if (isSet%s()) {\n", firstUpStr(f.Name)))
			indent = "            "
		}
		if i > 0 {
			sb.WriteString(indent + "if (!first) sb.append(\", \");\n")
		}
		sb.WriteString(fmt.Sprintf("%ssb.append(\"%s:\");\n", indent, f.Name))
		if g.typeCanBeNull(f.Type) {
			sb.WriteString(fmt.Sprintf("%sif (this.%s == null) {\n", indent, f.Name))
			sb.WriteString(fmt.Sprintf("%s    sb.append(\"null\");\n", indent))
			sb.WriteString(fmt.Sprintf("%s} else {\n", indent))
			sb.WriteString(fmt.Sprintf("%s    sb.append(this.%s);\n", indent, f.Name))
			sb.WriteString(fmt.Sprintf("%s}\n", indent))
		} else {
			sb.WriteString(fmt.Sprintf("%ssb.append(this.%s);\n", indent, f.Name))
		}
		sb.WriteString(indent + "first = false;\n")
		if couldBeUnset {
			sb.WriteString("        }\n")
		}
	}
	sb.WriteString("        sb.append(\")\");\n")
	sb.WriteString("        return sb.toString();\n")
	sb.WriteString("    }\n\n")

	// writeTo()
	sb.WriteString("    public void writeTo(TarsOutputStream _os) {\n")
	for _, f := range s.Fields {
		if !f.IsRequired {
			if bt, ok := f.Type.(*ast.BuiltinType); ok && bt.Kind != ast.KindString {
				if g.isEnum(f.Type) {
					sb.WriteString(fmt.Sprintf("        _os.write(%s, %d);\n", f.Name, f.Tag))
				} else {
					sb.WriteString(fmt.Sprintf("        _os.write(%s, %d);\n", f.Name, f.Tag))
				}
			} else {
				sb.WriteString(fmt.Sprintf("        if (null != %s) {\n", f.Name))
				sb.WriteString(fmt.Sprintf("            _os.write(%s, %d);\n", f.Name, f.Tag))
				sb.WriteString("        }\n")
			}
		} else {
			sb.WriteString(fmt.Sprintf("        _os.write(%s, %d);\n", f.Name, f.Tag))
		}
	}
	sb.WriteString("    }\n\n")

	// Cache variables for complex types
	for _, f := range s.Fields {
		isEnum := g.isEnum(f.Type)
		if (!isEnum && g.isCustomType(f.Type)) || g.isMapType(f.Type) || g.isVectorType(f.Type) {
			memberName := "cache_" + f.Name
			sb.WriteString(fmt.Sprintf("    static %s %s;\n", g.toJavaBoxedType(f.Type), memberName))
			sb.WriteString("    static {\n")
			g.genCacheVar(&sb, memberName, true, f.Type, "        ")
			sb.WriteString("    }\n\n")
		}
	}

	// readFrom()
	sb.WriteString("    public void readFrom(TarsInputStream _is) {\n")
	for _, f := range s.Fields {
		isEnum := g.isEnum(f.Type)
		if (!isEnum && g.isCustomType(f.Type)) || g.isMapType(f.Type) || g.isVectorType(f.Type) {
			javaType := g.toJavaType(f.Type)
			sb.WriteString(fmt.Sprintf("        this.%s = (%s) _is.read(cache_%s, %d, %t);\n", f.Name, javaType, f.Name, f.Tag, f.IsRequired))
		} else {
			if bt, ok := f.Type.(*ast.BuiltinType); ok && bt.Kind == ast.KindString {
				sb.WriteString(fmt.Sprintf("        this.%s = _is.readString(%d, %t);\n", f.Name, f.Tag, f.IsRequired))
			} else {
				sb.WriteString(fmt.Sprintf("        this.%s = _is.read(%s, %d, %t);\n", f.Name, f.Name, f.Tag, f.IsRequired))
			}
		}
	}
	sb.WriteString("    }\n\n")

	sb.WriteString("}\n")

	// Write file
	dir := filepath.Join(g.baseDir, strings.ReplaceAll(packageName, ".", "/"))
	if err := os.MkdirAll(dir, 0755); err != nil {
		return err
	}

	filePath := filepath.Join(dir, s.Name+".java")
	return os.WriteFile(filePath, []byte(sb.String()), 0644)
}

func (g *Generator) genCacheVar(sb *strings.Builder, memberName string, hasDeclare bool, t ast.Type, indent string) {
	switch v := t.(type) {
	case *ast.CustomType:
		if !g.isEnum(t) {
			if hasDeclare {
				sb.WriteString(fmt.Sprintf("%s%s = new %s();\n", indent, memberName, g.toJavaBoxedType(t)))
			} else {
				sb.WriteString(fmt.Sprintf("%s%s %s = new %s();\n", indent, g.toJavaBoxedType(t), memberName, g.toJavaBoxedType(t)))
			}
		} else {
			if hasDeclare {
				sb.WriteString(fmt.Sprintf("%s%s = 0;\n", indent, memberName))
			} else {
				sb.WriteString(fmt.Sprintf("%sint %s = 0;\n", indent, memberName))
			}
		}
	case *ast.MapType:
		keyType := g.toJavaBoxedType(v.KeyType)
		valueType := g.toJavaBoxedType(v.ValueType)
		if hasDeclare {
			sb.WriteString(fmt.Sprintf("%s%s = new java.util.HashMap<%s, %s>();\n", indent, memberName, keyType, valueType))
		} else {
			sb.WriteString(fmt.Sprintf("%sjava.util.Map<%s, %s> %s = new java.util.HashMap<>();\n", indent, keyType, valueType, memberName))
		}
		varKey := "var_key_" + strings.ReplaceAll(memberName, "cache_", "")
		varVal := "var_val_" + strings.ReplaceAll(memberName, "cache_", "")
		g.genCacheVar(sb, varKey, false, v.KeyType, indent)
		g.genCacheVar(sb, varVal, false, v.ValueType, indent)
		sb.WriteString(fmt.Sprintf("%s%s.put(%s, %s);\n", indent, memberName, varKey, varVal))
	case *ast.VectorType:
		if bt, ok := v.ElementType.(*ast.BuiltinType); ok && bt.Kind == ast.KindByte {
			if hasDeclare {
				sb.WriteString(fmt.Sprintf("%s%s = new byte[1];\n", indent, memberName))
			} else {
				sb.WriteString(fmt.Sprintf("%sbyte[] %s = new byte[1];\n", indent, memberName))
			}
		} else {
			elemType := g.toJavaBoxedType(v.ElementType)
			if hasDeclare {
				sb.WriteString(fmt.Sprintf("%s%s = new java.util.ArrayList<%s>();\n", indent, memberName, elemType))
			} else {
				sb.WriteString(fmt.Sprintf("%sjava.util.List<%s> %s = new java.util.ArrayList<>();\n", indent, elemType, memberName))
			}
			varElem := "var_elem_" + strings.ReplaceAll(memberName, "cache_", "")
			g.genCacheVar(sb, varElem, false, v.ElementType, indent)
			sb.WriteString(fmt.Sprintf("%s%s.add(%s);\n", indent, memberName, varElem))
		}
	case *ast.BuiltinType:
		defaultVal := g.getBuiltinDefault(v, true)
		if hasDeclare {
			sb.WriteString(fmt.Sprintf("%s%s = %s;\n", indent, memberName, defaultVal))
		} else {
			sb.WriteString(fmt.Sprintf("%s%s %s = %s;\n", indent, g.toJavaType(t), memberName, defaultVal))
		}
	}
}

func (g *Generator) generateEnumFile(ns *ast.Namespace, e *ast.Enum) error {
	var sb strings.Builder

	g.printHead(&sb)

	packageName := g.getPackageName(ns)
	sb.WriteString(fmt.Sprintf("package %s;\n\n", packageName))

	sb.WriteString(fmt.Sprintf("public enum %s {\n\n", e.Name))

	for i, m := range e.Members {
		if i < len(e.Members)-1 {
			sb.WriteString(fmt.Sprintf("    %s(%d),\n", m.Name, m.Value))
		} else {
			sb.WriteString(fmt.Sprintf("    %s(%d);\n", m.Name, m.Value))
		}
	}

	sb.WriteString("\n")
	sb.WriteString("    private final int value;\n\n")
	sb.WriteString(fmt.Sprintf("    private %s(int value) {\n", e.Name))
	sb.WriteString("        this.value = value;\n")
	sb.WriteString("    }\n\n")
	sb.WriteString("    public int value() {\n")
	sb.WriteString("        return this.value;\n")
	sb.WriteString("    }\n\n")

	// toString
	sb.WriteString("    @Override\n")
	sb.WriteString("    public String toString() {\n")
	sb.WriteString("        return this.name() + \":\" + this.value;\n")
	sb.WriteString("    }\n\n")

	// convert method
	sb.WriteString(fmt.Sprintf("    public static %s convert(int value) {\n", e.Name))
	sb.WriteString(fmt.Sprintf("        for (%s v : values()) {\n", e.Name))
	sb.WriteString("            if (v.value() == value) {\n")
	sb.WriteString("                return v;\n")
	sb.WriteString("            }\n")
	sb.WriteString("        }\n")
	sb.WriteString("        return null;\n")
	sb.WriteString("    }\n")

	sb.WriteString("}\n")

	// Write file
	dir := filepath.Join(g.baseDir, strings.ReplaceAll(packageName, ".", "/"))
	if err := os.MkdirAll(dir, 0755); err != nil {
		return err
	}

	filePath := filepath.Join(dir, e.Name+".java")
	return os.WriteFile(filePath, []byte(sb.String()), 0644)
}

func (g *Generator) generatePrxFile(ns *ast.Namespace, iface *ast.Interface) error {
	var sb strings.Builder

	g.printHead(&sb)

	packageName := g.getPackageName(ns)
	prxClass := iface.Name + "Prx"

	sb.WriteString(fmt.Sprintf("package %s;\n\n", packageName))

	// Imports
	sb.WriteString("import com.qq.tars.protocol.annotation.*;\n")
	sb.WriteString("import com.qq.tars.protocol.tars.annotation.*;\n")
	sb.WriteString("import com.qq.tars.common.support.Holder;\n")
	sb.WriteString("import java.util.concurrent.CompletableFuture;\n\n")

	sb.WriteString("@Servant\n")
	sb.WriteString(fmt.Sprintf("public interface %s {\n\n", prxClass))

	for _, op := range iface.Operations {
		returnType := "void"
		if op.ReturnType != nil {
			if bt, ok := op.ReturnType.(*ast.BuiltinType); !ok || bt.Kind != ast.KindVoid {
				returnType = g.toJavaType(op.ReturnType)
			}
		}
		boxedReturnType := "Void"
		if op.ReturnType != nil {
			if bt, ok := op.ReturnType.(*ast.BuiltinType); !ok || bt.Kind != ast.KindVoid {
				boxedReturnType = g.toJavaBoxedType(op.ReturnType)
			}
		}

		// 1. Sync method without context
		sb.WriteString(fmt.Sprintf("    %s %s(%s);\n\n", returnType, op.Name, g.operationParams(op.Params, nil, true)))

		// 2. Sync method with context
		sb.WriteString(fmt.Sprintf("    %s %s(%s);\n\n", returnType, op.Name,
			g.operationParams(op.Params, []string{"@TarsContext java.util.Map<String, String> ctx"}, true)))

		// 3. Async method without context
		sb.WriteString(fmt.Sprintf("    void async_%s(%s);\n\n", op.Name,
			g.operationParamsWithPrefix([]string{"@TarsCallback " + prxClass + "Callback callback"}, op.Params, nil, false)))

		// 4. Async method with context
		sb.WriteString(fmt.Sprintf("    void async_%s(%s);\n\n", op.Name,
			g.operationParamsWithPrefix([]string{"@TarsCallback " + prxClass + "Callback callback"}, op.Params,
				[]string{"@TarsContext java.util.Map<String, String> ctx"}, false)))

		// 5. Promise method without context
		sb.WriteString(fmt.Sprintf("    CompletableFuture<%s> promise_%s(%s);\n\n", boxedReturnType, op.Name,
			g.operationParams(op.Params, nil, true)))

		// 6. Promise method with context
		sb.WriteString(fmt.Sprintf("    CompletableFuture<%s> promise_%s(%s);\n\n", boxedReturnType, op.Name,
			g.operationParams(op.Params, []string{"@TarsContext java.util.Map<String, String> ctx"}, true)))
	}

	sb.WriteString("}\n")

	// Write file
	dir := filepath.Join(g.baseDir, strings.ReplaceAll(packageName, ".", "/"))
	if err := os.MkdirAll(dir, 0755); err != nil {
		return err
	}

	filePath := filepath.Join(dir, prxClass+".java")
	return os.WriteFile(filePath, []byte(sb.String()), 0644)
}

func (g *Generator) generatePrxCallbackFile(ns *ast.Namespace, iface *ast.Interface) error {
	var sb strings.Builder

	g.printHead(&sb)

	packageName := g.getPackageName(ns)
	callbackClass := iface.Name + "PrxCallback"

	sb.WriteString(fmt.Sprintf("package %s;\n\n", packageName))

	sb.WriteString("import com.qq.tars.rpc.protocol.tars.support.TarsAbstractCallback;\n\n")

	sb.WriteString(fmt.Sprintf("public abstract class %s extends TarsAbstractCallback {\n\n", callbackClass))

	for _, op := range iface.Operations {
		returnType := g.toJavaType(op.ReturnType)
		params := g.callbackParams(op)

		if returnType == "void" || returnType == "Void" {
			sb.WriteString(fmt.Sprintf("    public abstract void callback_%s(%s);\n\n", op.Name, params))
		} else {
			if params == "" {
				sb.WriteString(fmt.Sprintf("    public abstract void callback_%s(%s ret);\n\n", op.Name, returnType))
			} else {
				sb.WriteString(fmt.Sprintf("    public abstract void callback_%s(%s ret, %s);\n\n", op.Name, returnType, params))
			}
		}
	}

	sb.WriteString("}\n")

	// Write file
	dir := filepath.Join(g.baseDir, strings.ReplaceAll(packageName, ".", "/"))
	if err := os.MkdirAll(dir, 0755); err != nil {
		return err
	}

	filePath := filepath.Join(dir, callbackClass+".java")
	return os.WriteFile(filePath, []byte(sb.String()), 0644)
}

func (g *Generator) generateServantFile(ns *ast.Namespace, iface *ast.Interface) error {
	var sb strings.Builder

	g.printHead(&sb)

	packageName := g.getPackageName(ns)
	servantClass := iface.Name + "Servant"

	sb.WriteString(fmt.Sprintf("package %s;\n\n", packageName))

	// Imports
	sb.WriteString("import com.qq.tars.protocol.annotation.*;\n")
	sb.WriteString("import com.qq.tars.protocol.tars.annotation.*;\n")
	sb.WriteString("import com.qq.tars.common.support.Holder;\n\n")

	sb.WriteString("@Servant\n")
	sb.WriteString(fmt.Sprintf("public interface %s {\n\n", servantClass))

	for _, op := range iface.Operations {
		returnType := "void"
		if op.ReturnType != nil {
			if bt, ok := op.ReturnType.(*ast.BuiltinType); !ok || bt.Kind != ast.KindVoid {
				returnType = g.toJavaType(op.ReturnType)
			}
		}

		sb.WriteString(fmt.Sprintf("    %s %s(%s);\n\n", returnType, op.Name, g.operationParams(op.Params, nil, true)))
	}

	sb.WriteString("}\n")

	// Write file
	dir := filepath.Join(g.baseDir, strings.ReplaceAll(packageName, ".", "/"))
	if err := os.MkdirAll(dir, 0755); err != nil {
		return err
	}

	filePath := filepath.Join(dir, servantClass+".java")
	return os.WriteFile(filePath, []byte(sb.String()), 0644)
}

func (g *Generator) operationParams(params []*ast.ParamDecl, afterParams []string, isSync bool) string {
	return g.operationParamsWithPrefix(nil, params, afterParams, isSync)
}

func (g *Generator) operationParamsWithPrefix(beforeParams []string, params []*ast.ParamDecl, afterParams []string, isSync bool) string {
	var parts []string

	for _, bp := range beforeParams {
		parts = append(parts, bp)
	}

	for _, p := range params {
		if !isSync && p.IsOut {
			continue
		}

		javaType := g.toJavaType(p.Type)
		annotation := ""

		if p.IsOut {
			annotation = fmt.Sprintf("@TarsHolder(name=\"%s\") ", p.Name)
			javaType = fmt.Sprintf("Holder<%s>", g.toJavaBoxedType(p.Type))
		} else {
			annotation = fmt.Sprintf("@TarsMethodParameter(name=\"%s\") ", p.Name)
			if p.IsRouteKey {
				annotation = "@TarsRouteKey " + annotation
			}
		}

		parts = append(parts, fmt.Sprintf("%s%s %s", annotation, javaType, p.Name))
	}

	for _, ap := range afterParams {
		parts = append(parts, ap)
	}

	return strings.Join(parts, ", ")
}

func (g *Generator) callbackParams(op *ast.Operation) string {
	var parts []string

	for _, p := range op.Params {
		if p.IsOut {
			javaType := g.toJavaType(p.Type)
			parts = append(parts, fmt.Sprintf("%s %s", javaType, p.Name))
		}
	}

	return strings.Join(parts, ", ")
}

func (g *Generator) toJavaType(t ast.Type) string {
	switch v := t.(type) {
	case *ast.BuiltinType:
		switch v.Kind {
		case ast.KindVoid:
			return "void"
		case ast.KindBool:
			return "boolean"
		case ast.KindByte:
			return "byte"
		case ast.KindShort:
			if v.IsUnsigned {
				return "int"
			}
			return "short"
		case ast.KindInt:
			if v.IsUnsigned {
				return "long"
			}
			return "int"
		case ast.KindLong:
			return "long"
		case ast.KindFloat:
			return "float"
		case ast.KindDouble:
			return "double"
		case ast.KindString:
			return "String"
		}
	case *ast.VectorType:
		if bt, ok := v.ElementType.(*ast.BuiltinType); ok && bt.Kind == ast.KindByte {
			return "byte[]"
		}
		return fmt.Sprintf("java.util.List<%s>", g.toJavaBoxedType(v.ElementType))
	case *ast.MapType:
		return fmt.Sprintf("java.util.Map<%s, %s>", g.toJavaBoxedType(v.KeyType), g.toJavaBoxedType(v.ValueType))
	case *ast.CustomType:
		if g.isEnum(t) {
			return "int"
		}
		return v.TypeName_
	}
	return "Object"
}

func (g *Generator) toJavaBoxedType(t ast.Type) string {
	switch v := t.(type) {
	case *ast.BuiltinType:
		switch v.Kind {
		case ast.KindVoid:
			return "Void"
		case ast.KindBool:
			return "Boolean"
		case ast.KindByte:
			return "Byte"
		case ast.KindShort:
			if v.IsUnsigned {
				return "Integer"
			}
			return "Short"
		case ast.KindInt:
			if v.IsUnsigned {
				return "Long"
			}
			return "Integer"
		case ast.KindLong:
			return "Long"
		case ast.KindFloat:
			return "Float"
		case ast.KindDouble:
			return "Double"
		case ast.KindString:
			return "String"
		}
	case *ast.CustomType:
		if g.isEnum(t) {
			return "Integer"
		}
	}
	return g.toJavaType(t)
}

func (g *Generator) getBuiltinDefault(bt *ast.BuiltinType, useDefault bool) string {
	switch bt.Kind {
	case ast.KindBool:
		return "false"
	case ast.KindString:
		return "\"\""
	case ast.KindByte:
		return "(byte)0"
	case ast.KindShort:
		return "(short)0"
	case ast.KindInt:
		return "0"
	case ast.KindLong:
		return "0L"
	case ast.KindFloat:
		return "0.0f"
	case ast.KindDouble:
		return "0.0"
	}
	return "null"
}

func (g *Generator) getJavaDefault(f *ast.Field) string {
	if f.HasDefault && f.DefaultValue != "" {
		value := f.DefaultValue
		if bt, ok := f.Type.(*ast.BuiltinType); ok {
			switch bt.Kind {
			case ast.KindLong:
				if !strings.HasSuffix(value, "L") && !strings.HasSuffix(value, "l") {
					value += "L"
				}
			case ast.KindFloat:
				if !strings.HasSuffix(value, "F") && !strings.HasSuffix(value, "f") {
					value += "F"
				}
			case ast.KindDouble:
				if !strings.HasSuffix(value, "D") && !strings.HasSuffix(value, "d") {
					value += "D"
				}
			}
		}
		return value
	}

	return g.getJavaTypeDefault(f.Type)
}

func (g *Generator) getJavaTypeDefault(t ast.Type) string {
	switch v := t.(type) {
	case *ast.BuiltinType:
		return g.getBuiltinDefault(v, false)
	case *ast.VectorType:
		if bt, ok := v.ElementType.(*ast.BuiltinType); ok && bt.Kind == ast.KindByte {
			return "null"
		}
		return "new java.util.ArrayList<>()"
	case *ast.MapType:
		return "new java.util.HashMap<>()"
	case *ast.CustomType:
		if g.isEnum(t) {
			return "0"
		}
		return "new " + v.TypeName_ + "()"
	}
	return "null"
}

func (g *Generator) typeCanBeNull(t ast.Type) bool {
	if ct, ok := t.(*ast.CustomType); ok {
		if g.isEnum(t) {
			return false
		}
		_ = ct
		return true
	}
	if bt, ok := t.(*ast.BuiltinType); ok {
		return bt.Kind == ast.KindString
	}
	return true
}

func (g *Generator) isEnum(t ast.Type) bool {
	if ct, ok := t.(*ast.CustomType); ok {
		return g.enums[ct.Name] || g.enums[ct.TypeName_]
	}
	return false
}

func (g *Generator) isCustomType(t ast.Type) bool {
	_, ok := t.(*ast.CustomType)
	return ok
}

func (g *Generator) isMapType(t ast.Type) bool {
	_, ok := t.(*ast.MapType)
	return ok
}

func (g *Generator) isVectorType(t ast.Type) bool {
	_, ok := t.(*ast.VectorType)
	return ok
}

func firstUpStr(str string) string {
	if len(str) == 0 {
		return str
	}
	return strings.ToUpper(str[:1]) + str[1:]
}
