// Generated by tarsc - Tars IDL Compiler
// DO NOT EDIT!

#![allow(dead_code, unused_imports, unused_mut, unused_variables, non_snake_case, non_camel_case_types, clippy::all)]

use std::collections::HashMap;
use std::sync::Arc;
use async_trait::async_trait;
use tars_core::{consts, Context, Result, TarsError};
use tars_core::codec::{Buffer, PackageStatus, Reader, TarsDecode, TarsEncode, TarsStruct, TarsType, parse_package};
use tars_protocol::protocol::{RequestPacket, ResponsePacket};
use tars_rpc::servant::ServantProxy;
use tars_transport::transport::ServerProtocolHandler;

pub mod demo {
    use super::*;

    #[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
    #[repr(i32)]
    pub enum Color {
        RED = 0,
        GREEN = 1,
        BLUE = 2,
    }

    impl Default for Color {
        fn default() -> Self {
            Color::RED
        }
    }

    impl From<i32> for Color {
        fn from(value: i32) -> Self {
            match value {
                0 => Color::RED,
                1 => Color::GREEN,
                2 => Color::BLUE,
                _ => Color::RED,
            }
        }
    }

    impl TarsEncode for Color {
        fn encode(&self, buf: &mut Buffer, tag: u8) -> Result<()> {
            (*self as i32).encode(buf, tag)
        }
    }

    impl TarsDecode for Color {
        fn decode(reader: &mut Reader, tag: u8, require: bool) -> Result<Self> {
            let v = i32::decode(reader, tag, require)?;
            Ok(Color::from(v))
        }
    }

    #[derive(Debug, Clone, Default)]
    pub struct Point {
        pub x: i32,
        pub y: i32,
        pub label: String,
    }

    impl TarsStruct for Point {
        fn write_to(&self, buf: &mut Buffer) -> Result<()> {
            self.x.encode(buf, 0)?;
            self.y.encode(buf, 1)?;
            self.label.encode(buf, 2)?;
            Ok(())
        }

        fn read_from(reader: &mut Reader) -> Result<Self> {
            let mut __out = Self::default();
            __out.x = <i32 as TarsDecode>::decode(reader, 0, true)?;
            __out.y = <i32 as TarsDecode>::decode(reader, 1, true)?;
            __out.label = <String as TarsDecode>::decode(reader, 2, false)?;
            Ok(__out)
        }
    }

    impl TarsEncode for Point {
        fn encode(&self, buf: &mut Buffer, tag: u8) -> Result<()> {
            buf.write_struct_begin(tag)?;
            self.write_to(buf)?;
            buf.write_struct_end()?;
            Ok(())
        }
    }

    impl TarsDecode for Point {
        fn decode(reader: &mut Reader, tag: u8, require: bool) -> Result<Self> {
            if !reader.read_struct_begin(tag, require)? {
                return Ok(Self::default());
            }
            let __out = Self::read_from(reader)?;
            reader.read_struct_end()?;
            Ok(__out)
        }
    }

    #[derive(Debug, Clone, Default)]
    pub struct Shape {
        pub name: String,
        pub points: Vec<Point>,
        pub color: Color,
        pub tags: HashMap<String, i32>,
    }

    impl TarsStruct for Shape {
        fn write_to(&self, buf: &mut Buffer) -> Result<()> {
            self.name.encode(buf, 0)?;
            buf.write_head(TarsType::List, 1)?;
            buf.write_int32(self.points.len() as i32, 0)?;
            for __item in self.points.iter() {
                __item.encode(buf, 0)?;
            }
            self.color.encode(buf, 2)?;
            buf.write_head(TarsType::Map, 3)?;
            buf.write_int32(self.tags.len() as i32, 0)?;
            for (__k, __v) in self.tags.iter() {
                __k.encode(buf, 0)?;
                __v.encode(buf, 1)?;
            }
            Ok(())
        }

        fn read_from(reader: &mut Reader) -> Result<Self> {
            let mut __out = Self::default();
            __out.name = <String as TarsDecode>::decode(reader, 0, true)?;
            __out.points = {
                let __len = reader.read_list_begin(1, true)?;
                let mut __vec: Vec<Point> = Vec::with_capacity(__len as usize);
                for _ in 0..__len {
                    let __item: Point = <Point as TarsDecode>::decode(reader, 0, true)?;
                    __vec.push(__item);
                }
                __vec
            };
            __out.color = <Color as TarsDecode>::decode(reader, 2, false)?;
            __out.tags = {
                let __len = reader.read_map_begin(3, false)?;
                let mut __map: HashMap<String, i32> = HashMap::with_capacity(__len as usize);
                for _ in 0..__len {
                    let __k: String = <String as TarsDecode>::decode(reader, 0, true)?;
                    let __v: i32 = <i32 as TarsDecode>::decode(reader, 1, true)?;
                    __map.insert(__k, __v);
                }
                __map
            };
            Ok(__out)
        }
    }

    impl TarsEncode for Shape {
        fn encode(&self, buf: &mut Buffer, tag: u8) -> Result<()> {
            buf.write_struct_begin(tag)?;
            self.write_to(buf)?;
            buf.write_struct_end()?;
            Ok(())
        }
    }

    impl TarsDecode for Shape {
        fn decode(reader: &mut Reader, tag: u8, require: bool) -> Result<Self> {
            if !reader.read_struct_begin(tag, require)? {
                return Ok(Self::default());
            }
            let __out = Self::read_from(reader)?;
            reader.read_struct_end()?;
            Ok(__out)
        }
    }

    /// Servant trait — implement this on the server side.
    #[async_trait]
    pub trait Drawer: Send + Sync + 'static {
        async fn draw(&self, ctx: &Context, input: Shape, repeats: i32) -> Result<Shape>;
        async fn count(&self, ctx: &Context, values: Vec<i32>) -> Result<(i32, Vec<i32>)>;
        async fn noop(&self, ctx: &Context) -> Result<()>;
    }

    /// Client-side proxy. Wraps an `Arc<ServantProxy>` and serializes calls.
    #[derive(Clone)]
    pub struct DrawerProxy {
        proxy: Arc<ServantProxy>,
    }

    impl DrawerProxy {
        pub fn new(proxy: Arc<ServantProxy>) -> Self {
            Self { proxy }
        }

        pub fn proxy(&self) -> &Arc<ServantProxy> {
            &self.proxy
        }

        pub async fn draw(&self, ctx: Context, input: Shape, repeats: i32) -> Result<Shape> {
            let mut __buf = Buffer::new();
            input.encode(&mut __buf, 1)?;
            repeats.encode(&mut __buf, 2)?;
            let __resp = self.proxy.invoke(ctx, "draw", __buf.to_bytes(), HashMap::new(), HashMap::new()).await?;
            let mut __reader = Reader::new(&__resp.s_buffer);
            let __ret: Shape = <Shape as TarsDecode>::decode(&mut __reader, 0, true)?;
            Ok(__ret)
        }

        pub async fn count(&self, ctx: Context, values: Vec<i32>) -> Result<(i32, Vec<i32>)> {
            let mut __buf = Buffer::new();
            __buf.write_head(TarsType::List, 1)?;
            __buf.write_int32(values.len() as i32, 0)?;
            for __item in values.iter() {
                __item.encode(&mut __buf, 0)?;
            }
            let __resp = self.proxy.invoke(ctx, "count", __buf.to_bytes(), HashMap::new(), HashMap::new()).await?;
            let mut __reader = Reader::new(&__resp.s_buffer);
            let __ret: i32 = <i32 as TarsDecode>::decode(&mut __reader, 0, true)?;
            let __out_doubled: Vec<i32> = {
                let __len = __reader.read_list_begin(2, true)?;
                let mut __vec: Vec<i32> = Vec::with_capacity(__len as usize);
                for _ in 0..__len {
                    let __item: i32 = <i32 as TarsDecode>::decode(&mut __reader, 0, true)?;
                    __vec.push(__item);
                }
                __vec
            };
            Ok((__ret, __out_doubled))
        }

        pub async fn noop(&self, ctx: Context) -> Result<()> {
            let mut __buf = Buffer::new();
            let __resp = self.proxy.invoke(ctx, "noop", __buf.to_bytes(), HashMap::new(), HashMap::new()).await?;
            let mut __reader = Reader::new(&__resp.s_buffer);
            Ok(())
        }
    }

    /// Server-side dispatcher. Wraps a user-supplied `T: Drawer` and
    /// implements `ServerProtocolHandler` for use with `Application::add_servant`.
    pub struct DrawerServant<T: Drawer> {
        inner: Arc<T>,
    }

    impl<T: Drawer> DrawerServant<T> {
        pub fn new(inner: T) -> Self {
            Self { inner: Arc::new(inner) }
        }

        pub fn from_arc(inner: Arc<T>) -> Self {
            Self { inner }
        }

        async fn __dispatch(&self, ctx: &mut Context, __req: &RequestPacket) -> Result<Vec<u8>> {
            match __req.s_func_name.as_str() {
                "draw" => {
                    let mut __reader = Reader::new(&__req.s_buffer);
                    let input: Shape = <Shape as TarsDecode>::decode(&mut __reader, 1, true)?;
                    let repeats: i32 = <i32 as TarsDecode>::decode(&mut __reader, 2, true)?;
                    let __ret = self.inner.draw(ctx, input, repeats).await?;
                    let mut __out = Buffer::new();
                    __ret.encode(&mut __out, 0)?;
                    Ok(__out.to_bytes())
                }
                "count" => {
                    let mut __reader = Reader::new(&__req.s_buffer);
                    let values: Vec<i32> = {
                        let __len = __reader.read_list_begin(1, true)?;
                        let mut __vec: Vec<i32> = Vec::with_capacity(__len as usize);
                        for _ in 0..__len {
                            let __item: i32 = <i32 as TarsDecode>::decode(&mut __reader, 0, true)?;
                            __vec.push(__item);
                        }
                        __vec
                    };
                    let (__ret, __out_doubled) = self.inner.count(ctx, values).await?;
                    let mut __out = Buffer::new();
                    __ret.encode(&mut __out, 0)?;
                    __out.write_head(TarsType::List, 2)?;
                    __out.write_int32(__out_doubled.len() as i32, 0)?;
                    for __item in __out_doubled.iter() {
                        __item.encode(&mut __out, 0)?;
                    }
                    Ok(__out.to_bytes())
                }
                "noop" => {
                    let mut __reader = Reader::new(&__req.s_buffer);
                    let () = self.inner.noop(ctx).await?;
                    let mut __out = Buffer::new();
                    Ok(__out.to_bytes())
                }
                __other => Err(TarsError::Protocol(format!("unknown method: {}", __other))),
            }
        }
    }

    #[async_trait]
    impl<T: Drawer> ServerProtocolHandler for DrawerServant<T> {
        fn parse_package(&self, buff: &[u8]) -> (usize, PackageStatus) {
            parse_package(buff)
        }

        async fn invoke(&self, ctx: &mut Context, pkg: &[u8]) -> Vec<u8> {
            let __req = match RequestPacket::decode(pkg) {
                Ok(r) => r,
                Err(e) => {
                    return ResponsePacket::error(0, consts::TARS_SERVER_DECODE_ERR, &e.to_string())
                        .encode().unwrap_or_default();
                }
            };
            let __request_id = __req.i_request_id;
            match self.__dispatch(ctx, &__req).await {
                Ok(__buf) => ResponsePacket::success(__request_id, __buf).encode().unwrap_or_default(),
                Err(TarsError::ServerError { code, message }) => ResponsePacket::error(__request_id, code, &message).encode().unwrap_or_default(),
                Err(e) => ResponsePacket::error(__request_id, consts::TARS_SERVER_UNKNOWN_ERR, &e.to_string()).encode().unwrap_or_default(),
            }
        }

        fn invoke_timeout(&self, pkg: &[u8]) -> Vec<u8> {
            let __id = RequestPacket::decode(pkg).map(|r| r.i_request_id).unwrap_or(0);
            ResponsePacket::timeout(__id).encode().unwrap_or_default()
        }

        fn get_close_msg(&self) -> Vec<u8> {
            Vec::new()
        }

        fn do_close(&self, _ctx: &Context) {}
    }

}
