// Generated by tarsc - Tars IDL Compiler
// DO NOT EDIT!

#![allow(dead_code, unused_imports, unused_mut, unused_variables, non_snake_case, non_camel_case_types, clippy::all)]

use std::collections::HashMap;
use std::sync::Arc;
use async_trait::async_trait;
use tars_core::{consts, Context, Result, TarsError};
use tars_core::codec::{Buffer, PackageStatus, Reader, TarsDecode, TarsEncode, TarsStruct, TarsType, parse_package};
use tars_protocol::protocol::{RequestPacket, ResponsePacket};
use tars_rpc::servant::ServantProxy;
use tars_transport::transport::ServerProtocolHandler;

pub mod test_app {
    use super::*;

    /// Servant trait — implement this on the server side.
    #[async_trait]
    pub trait Hello: Send + Sync + 'static {
        async fn hello(&self, ctx: &Context, no: i32, name: String) -> Result<String>;
    }

    /// Client-side proxy. Wraps an `Arc<ServantProxy>` and serializes calls.
    #[derive(Clone)]
    pub struct HelloProxy {
        proxy: Arc<ServantProxy>,
    }

    impl HelloProxy {
        pub fn new(proxy: Arc<ServantProxy>) -> Self {
            Self { proxy }
        }

        pub fn proxy(&self) -> &Arc<ServantProxy> {
            &self.proxy
        }

        pub async fn hello(&self, ctx: Context, no: i32, name: String) -> Result<String> {
            let mut __buf = Buffer::new();
            no.encode(&mut __buf, 1)?;
            name.encode(&mut __buf, 2)?;
            let __resp = self.proxy.invoke(ctx, "hello", __buf.to_bytes(), HashMap::new(), HashMap::new()).await?;
            let mut __reader = Reader::new(&__resp.s_buffer);
            let __ret: String = <String as TarsDecode>::decode(&mut __reader, 0, true)?;
            Ok(__ret)
        }
    }

    /// Server-side dispatcher. Wraps a user-supplied `T: Hello` and
    /// implements `ServerProtocolHandler` for use with `Application::add_servant`.
    pub struct HelloServant<T: Hello> {
        inner: Arc<T>,
    }

    impl<T: Hello> HelloServant<T> {
        pub fn new(inner: T) -> Self {
            Self { inner: Arc::new(inner) }
        }

        pub fn from_arc(inner: Arc<T>) -> Self {
            Self { inner }
        }

        async fn __dispatch(&self, ctx: &mut Context, __req: &RequestPacket) -> Result<Vec<u8>> {
            match __req.s_func_name.as_str() {
                "hello" => {
                    let mut __reader = Reader::new(&__req.s_buffer);
                    let no: i32 = <i32 as TarsDecode>::decode(&mut __reader, 1, true)?;
                    let name: String = <String as TarsDecode>::decode(&mut __reader, 2, true)?;
                    let __ret = self.inner.hello(ctx, no, name).await?;
                    let mut __out = Buffer::new();
                    __ret.encode(&mut __out, 0)?;
                    Ok(__out.to_bytes())
                }
                __other => Err(TarsError::Protocol(format!("unknown method: {}", __other))),
            }
        }
    }

    #[async_trait]
    impl<T: Hello> ServerProtocolHandler for HelloServant<T> {
        fn parse_package(&self, buff: &[u8]) -> (usize, PackageStatus) {
            parse_package(buff)
        }

        async fn invoke(&self, ctx: &mut Context, pkg: &[u8]) -> Vec<u8> {
            let __req = match RequestPacket::decode(pkg) {
                Ok(r) => r,
                Err(e) => {
                    return ResponsePacket::error(0, consts::TARS_SERVER_DECODE_ERR, &e.to_string())
                        .encode().unwrap_or_default();
                }
            };
            let __request_id = __req.i_request_id;
            match self.__dispatch(ctx, &__req).await {
                Ok(__buf) => ResponsePacket::success(__request_id, __buf).encode().unwrap_or_default(),
                Err(TarsError::ServerError { code, message }) => ResponsePacket::error(__request_id, code, &message).encode().unwrap_or_default(),
                Err(e) => ResponsePacket::error(__request_id, consts::TARS_SERVER_UNKNOWN_ERR, &e.to_string()).encode().unwrap_or_default(),
            }
        }

        fn invoke_timeout(&self, pkg: &[u8]) -> Vec<u8> {
            let __id = RequestPacket::decode(pkg).map(|r| r.i_request_id).unwrap_or(0);
            ResponsePacket::timeout(__id).encode().unwrap_or_default()
        }

        fn get_close_msg(&self) -> Vec<u8> {
            Vec::new()
        }

        fn do_close(&self, _ctx: &Context) {}
    }

}
