/**
 * Tencent is pleased to support the open source community by making Tars available.
 *
 * Copyright (C) 2016THL A29 Limited, a Tencent company. All rights reserved.
 *
 * Licensed under the BSD 3-Clause License (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * https://opensource.org/licenses/BSD-3-Clause
 */

// Package golang generates Go code from Tars IDL
package golang

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/TarsCloud/TarsCpp/tools/tarsc-go/pkg/ast"
)

// Generator generates Go code
type Generator struct {
	baseDir string
}

// NewGenerator creates a new Go generator
func NewGenerator(baseDir string) *Generator {
	return &Generator{baseDir: baseDir}
}

// Generate generates Go code for the document
func (g *Generator) Generate(doc *ast.Document, baseName string) error {
	for _, ns := range doc.Namespaces {
		if err := g.generateNamespace(doc, ns, baseName); err != nil {
			return err
		}
	}
	return nil
}

func (g *Generator) generateNamespace(doc *ast.Document, ns *ast.Namespace, baseName string) error {
	var sb strings.Builder

	// Header
	sb.WriteString("// Code generated by tarsc. DO NOT EDIT.\n\n")
	sb.WriteString(fmt.Sprintf("package %s\n\n", strings.ToLower(ns.Name)))

	// Imports
	sb.WriteString("import (\n")
	sb.WriteString("\t\"github.com/TarsCloud/TarsGo/tars/protocol/codec\"\n")
	sb.WriteString(")\n\n")

	// Generate consts
	if len(ns.Consts) > 0 {
		sb.WriteString("// Constants\n")
		sb.WriteString("const (\n")
		for _, c := range ns.Consts {
			sb.WriteString(fmt.Sprintf("\t%s = %s\n", c.Name, c.Value))
		}
		sb.WriteString(")\n\n")
	}

	// Generate enums
	for _, e := range ns.Enums {
		sb.WriteString(g.generateEnum(e))
		sb.WriteString("\n")
	}

	// Generate structs
	for _, s := range ns.Structs {
		sb.WriteString(g.generateStruct(s))
		sb.WriteString("\n")
	}

	// Generate interfaces
	for _, iface := range ns.Interfaces {
		sb.WriteString(g.generateInterface(iface))
		sb.WriteString("\n")
	}

	// Write file
	dir := filepath.Join(g.baseDir, strings.ToLower(ns.Name))
	if err := os.MkdirAll(dir, 0755); err != nil {
		return err
	}

	filePath := filepath.Join(dir, baseName+".go")
	return os.WriteFile(filePath, []byte(sb.String()), 0644)
}

func (g *Generator) generateEnum(e *ast.Enum) string {
	var sb strings.Builder

	sb.WriteString(fmt.Sprintf("// %s enum\n", e.Name))
	sb.WriteString(fmt.Sprintf("type %s int32\n\n", e.Name))
	sb.WriteString("const (\n")

	for i, m := range e.Members {
		if i == 0 {
			sb.WriteString(fmt.Sprintf("\t%s_%s %s = %d\n", e.Name, m.Name, e.Name, m.Value))
		} else {
			sb.WriteString(fmt.Sprintf("\t%s_%s = %d\n", e.Name, m.Name, m.Value))
		}
	}
	sb.WriteString(")\n")

	return sb.String()
}

func (g *Generator) generateStruct(s *ast.Struct) string {
	var sb strings.Builder

	// Struct definition
	sb.WriteString(fmt.Sprintf("// %s struct\n", s.Name))
	sb.WriteString(fmt.Sprintf("type %s struct {\n", s.Name))

	for _, f := range s.Fields {
		goType := g.toGoType(f.Type)
		tag := fmt.Sprintf("`json:\"%s\"`", f.Name)
		sb.WriteString(fmt.Sprintf("\t%s %s %s\n", g.toGoFieldName(f.Name), goType, tag))
	}
	sb.WriteString("}\n\n")

	// ResetDefault method
	sb.WriteString(fmt.Sprintf("func (st *%s) ResetDefault() {\n", s.Name))
	for _, f := range s.Fields {
		if f.HasDefault {
			sb.WriteString(fmt.Sprintf("\tst.%s = %s\n", g.toGoFieldName(f.Name), g.getGoDefault(f)))
		}
	}
	sb.WriteString("}\n\n")

	// ReadFrom method
	sb.WriteString(fmt.Sprintf("func (st *%s) ReadFrom(readBuf *codec.Reader) error {\n", s.Name))
	sb.WriteString("\tvar err error\n")
	sb.WriteString("\tvar have bool\n")
	sb.WriteString("\tvar ty byte\n")
	sb.WriteString("\tst.ResetDefault()\n\n")

	for _, f := range s.Fields {
		g.generateReadField(&sb, f)
	}

	sb.WriteString("\treturn nil\n")
	sb.WriteString("}\n\n")

	// WriteTo method
	sb.WriteString(fmt.Sprintf("func (st *%s) WriteTo(buf *codec.Buffer) error {\n", s.Name))
	sb.WriteString("\tvar err error\n\n")

	for _, f := range s.Fields {
		g.generateWriteField(&sb, f)
	}

	sb.WriteString("\treturn nil\n")
	sb.WriteString("}\n")

	return sb.String()
}

func (g *Generator) generateReadField(sb *strings.Builder, f *ast.Field) {
	goField := g.toGoFieldName(f.Name)
	required := "true"
	if !f.IsRequired {
		required = "false"
	}

	switch v := f.Type.(type) {
	case *ast.BuiltinType:
		readFunc := g.getReadFunc(v)
		sb.WriteString(fmt.Sprintf("\thave, ty, err = readBuf.SkipToNoCheck(%d, %s)\n", f.Tag, required))
		sb.WriteString("\tif err != nil {\n\t\treturn err\n\t}\n")
		sb.WriteString("\tif have {\n")
		sb.WriteString(fmt.Sprintf("\t\tst.%s, err = %s\n", goField, readFunc))
		sb.WriteString("\t\tif err != nil {\n\t\t\treturn err\n\t\t}\n")
		sb.WriteString("\t}\n\n")
	case *ast.VectorType:
		sb.WriteString(fmt.Sprintf("\thave, ty, err = readBuf.SkipToNoCheck(%d, %s)\n", f.Tag, required))
		sb.WriteString("\tif err != nil {\n\t\treturn err\n\t}\n")
		sb.WriteString("\tif have {\n")
		sb.WriteString(fmt.Sprintf("\t\terr = readBuf.ReadVector(&st.%s, ty)\n", goField))
		sb.WriteString("\t\tif err != nil {\n\t\t\treturn err\n\t\t}\n")
		sb.WriteString("\t}\n\n")
	case *ast.MapType:
		sb.WriteString(fmt.Sprintf("\thave, ty, err = readBuf.SkipToNoCheck(%d, %s)\n", f.Tag, required))
		sb.WriteString("\tif err != nil {\n\t\treturn err\n\t}\n")
		sb.WriteString("\tif have {\n")
		sb.WriteString(fmt.Sprintf("\t\terr = readBuf.ReadMap(&st.%s, ty)\n", goField))
		sb.WriteString("\t\tif err != nil {\n\t\t\treturn err\n\t\t}\n")
		sb.WriteString("\t}\n\n")
	case *ast.CustomType:
		sb.WriteString(fmt.Sprintf("\thave, ty, err = readBuf.SkipToNoCheck(%d, %s)\n", f.Tag, required))
		sb.WriteString("\tif err != nil {\n\t\treturn err\n\t}\n")
		sb.WriteString("\tif have {\n")
		sb.WriteString(fmt.Sprintf("\t\terr = st.%s.ReadFrom(readBuf)\n", goField))
		sb.WriteString("\t\tif err != nil {\n\t\t\treturn err\n\t\t}\n")
		sb.WriteString("\t}\n\n")
	}

	_ = required // Suppress unused warning
}

func (g *Generator) generateWriteField(sb *strings.Builder, f *ast.Field) {
	goField := g.toGoFieldName(f.Name)

	switch v := f.Type.(type) {
	case *ast.BuiltinType:
		writeFunc := g.getWriteFunc(v)
		sb.WriteString(fmt.Sprintf("\terr = buf.%s(st.%s, %d)\n", writeFunc, goField, f.Tag))
		sb.WriteString("\tif err != nil {\n\t\treturn err\n\t}\n\n")
	case *ast.VectorType:
		sb.WriteString(fmt.Sprintf("\terr = buf.WriteVector(st.%s, %d)\n", goField, f.Tag))
		sb.WriteString("\tif err != nil {\n\t\treturn err\n\t}\n\n")
	case *ast.MapType:
		sb.WriteString(fmt.Sprintf("\terr = buf.WriteMap(st.%s, %d)\n", goField, f.Tag))
		sb.WriteString("\tif err != nil {\n\t\treturn err\n\t}\n\n")
	case *ast.CustomType:
		sb.WriteString(fmt.Sprintf("\terr = st.%s.WriteTo(buf)\n", goField))
		sb.WriteString("\tif err != nil {\n\t\treturn err\n\t}\n\n")
	}
}

func (g *Generator) generateInterface(iface *ast.Interface) string {
	var sb strings.Builder

	// Interface definition
	sb.WriteString(fmt.Sprintf("// %s interface\n", iface.Name))
	sb.WriteString(fmt.Sprintf("type %s interface {\n", iface.Name))

	for _, op := range iface.Operations {
		sb.WriteString(g.generateOperationSignature(op))
	}
	sb.WriteString("}\n\n")

	// Proxy implementation
	sb.WriteString(fmt.Sprintf("// %sProxy proxy struct\n", iface.Name))
	sb.WriteString(fmt.Sprintf("type %sProxy struct {\n", iface.Name))
	sb.WriteString("\t// TODO: Add proxy fields\n")
	sb.WriteString("}\n")

	return sb.String()
}

func (g *Generator) generateOperationSignature(op *ast.Operation) string {
	var params []string
	var returns []string

	for _, p := range op.Params {
		goType := g.toGoType(p.Type)
		if p.IsOut {
			goType = "*" + goType
		}
		params = append(params, fmt.Sprintf("%s %s", p.Name, goType))
	}

	// Return type
	if op.ReturnType != nil {
		if bt, ok := op.ReturnType.(*ast.BuiltinType); !ok || bt.Kind != ast.KindVoid {
			returns = append(returns, g.toGoType(op.ReturnType))
		}
	}
	returns = append(returns, "error")

	returnStr := strings.Join(returns, ", ")
	if len(returns) > 1 {
		returnStr = "(" + returnStr + ")"
	}

	return fmt.Sprintf("\t%s(%s) %s\n", op.Name, strings.Join(params, ", "), returnStr)
}

func (g *Generator) toGoType(t ast.Type) string {
	switch v := t.(type) {
	case *ast.BuiltinType:
		switch v.Kind {
		case ast.KindVoid:
			return ""
		case ast.KindBool:
			return "bool"
		case ast.KindByte:
			if v.IsUnsigned {
				return "uint8"
			}
			return "int8"
		case ast.KindShort:
			if v.IsUnsigned {
				return "uint16"
			}
			return "int16"
		case ast.KindInt:
			if v.IsUnsigned {
				return "uint32"
			}
			return "int32"
		case ast.KindLong:
			if v.IsUnsigned {
				return "uint64"
			}
			return "int64"
		case ast.KindFloat:
			return "float32"
		case ast.KindDouble:
			return "float64"
		case ast.KindString:
			return "string"
		}
	case *ast.VectorType:
		if bt, ok := v.ElementType.(*ast.BuiltinType); ok && bt.Kind == ast.KindByte {
			return "[]byte"
		}
		return "[]" + g.toGoType(v.ElementType)
	case *ast.MapType:
		return fmt.Sprintf("map[%s]%s", g.toGoType(v.KeyType), g.toGoType(v.ValueType))
	case *ast.CustomType:
		return v.TypeName_
	}
	return "interface{}"
}

func (g *Generator) toGoFieldName(name string) string {
	if len(name) == 0 {
		return name
	}
	return strings.ToUpper(name[:1]) + name[1:]
}

func (g *Generator) getGoDefault(f *ast.Field) string {
	if f.HasDefault && f.DefaultValue != "" {
		return f.DefaultValue
	}

	switch v := f.Type.(type) {
	case *ast.BuiltinType:
		switch v.Kind {
		case ast.KindBool:
			return "false"
		case ast.KindString:
			return "\"\""
		case ast.KindByte, ast.KindShort, ast.KindInt, ast.KindLong:
			return "0"
		case ast.KindFloat, ast.KindDouble:
			return "0.0"
		}
	}
	return "nil"
}

func (g *Generator) getReadFunc(bt *ast.BuiltinType) string {
	switch bt.Kind {
	case ast.KindBool:
		return "readBuf.ReadBool()"
	case ast.KindByte:
		return "readBuf.ReadInt8()"
	case ast.KindShort:
		if bt.IsUnsigned {
			return "readBuf.ReadUint16()"
		}
		return "readBuf.ReadInt16()"
	case ast.KindInt:
		if bt.IsUnsigned {
			return "readBuf.ReadUint32()"
		}
		return "readBuf.ReadInt32()"
	case ast.KindLong:
		if bt.IsUnsigned {
			return "readBuf.ReadUint64()"
		}
		return "readBuf.ReadInt64()"
	case ast.KindFloat:
		return "readBuf.ReadFloat32()"
	case ast.KindDouble:
		return "readBuf.ReadFloat64()"
	case ast.KindString:
		return "readBuf.ReadString()"
	}
	return "readBuf.ReadInt32()"
}

func (g *Generator) getWriteFunc(bt *ast.BuiltinType) string {
	switch bt.Kind {
	case ast.KindBool:
		return "WriteBool"
	case ast.KindByte:
		return "WriteInt8"
	case ast.KindShort:
		if bt.IsUnsigned {
			return "WriteUint16"
		}
		return "WriteInt16"
	case ast.KindInt:
		if bt.IsUnsigned {
			return "WriteUint32"
		}
		return "WriteInt32"
	case ast.KindLong:
		if bt.IsUnsigned {
			return "WriteUint64"
		}
		return "WriteInt64"
	case ast.KindFloat:
		return "WriteFloat32"
	case ast.KindDouble:
		return "WriteFloat64"
	case ast.KindString:
		return "WriteString"
	}
	return "WriteInt32"
}
