// Generated by tarsc - Tars IDL Compiler
// DO NOT EDIT!

#![allow(dead_code)]
#![allow(unused_imports)]

use std::collections::HashMap;
use tars_stream::{TarsDecoder, TarsEncoder, TarsStruct};
use serde::{Deserialize, Serialize};

pub mod testapp {
    use super::*;

    pub trait Hello {
        fn hello(&mut self, no: &i32, name: &String) -> Result<String, Box<dyn std::error::Error>>;
    }

    pub struct HelloProxy {
        // TODO: Add proxy fields
    }

    impl Hello for HelloProxy {
        fn hello(&mut self, no: &i32, name: &String) -> Result<String, Box<dyn std::error::Error>> {
            // TODO: Implement proxy call
            unimplemented!()
        }

    }

}
