/**
 * Tencent is pleased to support the open source community by making Tars available.
 *
 * Copyright (C) 2016THL A29 Limited, a Tencent company. All rights reserved.
 *
 * Licensed under the BSD 3-Clause License (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * https://opensource.org/licenses/BSD-3-Clause
 */

// Package swift generates Swift code from Tars IDL
package swift

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/TarsCloud/TarsCpp/tools/tarsc-go/pkg/ast"
)

// Generator generates Swift code
type Generator struct {
	baseDir string
	enums   map[string]bool
}

// NewGenerator creates a new Swift generator
func NewGenerator(baseDir string) *Generator {
	return &Generator{
		baseDir: baseDir,
		enums:   make(map[string]bool),
	}
}

// Generate generates Swift code for the document
func (g *Generator) Generate(doc *ast.Document, baseName string) error {
	// First pass: collect all enums
	for _, ns := range doc.Namespaces {
		for _, e := range ns.Enums {
			g.enums[e.Name] = true
			g.enums[ns.Name+"::"+e.Name] = true
		}
	}

	for _, ns := range doc.Namespaces {
		if err := g.generateNamespace(ns, baseName); err != nil {
			return err
		}
	}
	return nil
}

func (g *Generator) generateNamespace(ns *ast.Namespace, baseName string) error {
	// Generate types file
	if err := g.generateTypesFile(ns, baseName); err != nil {
		return err
	}

	// Generate client file
	if len(ns.Interfaces) > 0 {
		if err := g.generateClientFile(ns, baseName); err != nil {
			return err
		}
		// Generate server file
		if err := g.generateServerFile(ns, baseName); err != nil {
			return err
		}
	}

	return nil
}

func (g *Generator) generateTypesFile(ns *ast.Namespace, baseName string) error {
	var sb strings.Builder

	g.printHeader(&sb)

	sb.WriteString("import Foundation\nimport TarsKit\n\n")

	// Module/Namespace as enum (Swift pattern for namespacing)
	sb.WriteString(fmt.Sprintf("// MARK: - %s Types\n\n", ns.Name))

	// Generate constants
	if len(ns.Consts) > 0 {
		sb.WriteString("// MARK: - Constants\n\n")
		sb.WriteString(fmt.Sprintf("public enum %sConstants {\n", ns.Name))
		for _, c := range ns.Consts {
			swiftType := g.toSwiftType(c.Type)
			value := g.formatConstValue(c.Value, c.Type)
			sb.WriteString(fmt.Sprintf("    public static let %s: %s = %s\n", lowerFirst(c.Name), swiftType, value))
		}
		sb.WriteString("}\n\n")
	}

	// Generate enums
	if len(ns.Enums) > 0 {
		sb.WriteString("// MARK: - Enums\n\n")
		for _, e := range ns.Enums {
			g.generateEnum(&sb, e)
			sb.WriteString("\n")
		}
	}

	// Generate structs
	if len(ns.Structs) > 0 {
		sb.WriteString("// MARK: - Structs\n\n")
		for _, s := range ns.Structs {
			g.generateStruct(&sb, s, ns)
			sb.WriteString("\n")
		}
	}

	// Write file
	dir := filepath.Join(g.baseDir, ns.Name)
	if err := os.MkdirAll(dir, 0755); err != nil {
		return err
	}

	filePath := filepath.Join(dir, ns.Name+"Types.swift")
	return os.WriteFile(filePath, []byte(sb.String()), 0644)
}

func (g *Generator) generateClientFile(ns *ast.Namespace, baseName string) error {
	var sb strings.Builder

	g.printHeader(&sb)

	sb.WriteString("import Foundation\nimport TarsKit\n\n")

	sb.WriteString(fmt.Sprintf("// MARK: - %s Client Proxies\n\n", ns.Name))

	for _, iface := range ns.Interfaces {
		g.generateClientProxy(&sb, iface, ns)
		sb.WriteString("\n")
	}

	// Write file
	dir := filepath.Join(g.baseDir, ns.Name)
	filePath := filepath.Join(dir, ns.Name+"Client.swift")
	return os.WriteFile(filePath, []byte(sb.String()), 0644)
}

func (g *Generator) generateServerFile(ns *ast.Namespace, baseName string) error {
	var sb strings.Builder

	g.printHeader(&sb)

	sb.WriteString("import Foundation\nimport TarsKit\n\n")

	sb.WriteString(fmt.Sprintf("// MARK: - %s Server Protocols\n\n", ns.Name))

	for _, iface := range ns.Interfaces {
		g.generateServerProtocol(&sb, iface, ns)
		sb.WriteString("\n")
		g.generateServantBase(&sb, iface, ns)
		sb.WriteString("\n")
	}

	// Write file
	dir := filepath.Join(g.baseDir, ns.Name)
	filePath := filepath.Join(dir, ns.Name+"Server.swift")
	return os.WriteFile(filePath, []byte(sb.String()), 0644)
}

func (g *Generator) printHeader(sb *strings.Builder) {
	sb.WriteString("//\n")
	sb.WriteString("// This file was generated by tarsc - Tars IDL Compiler\n")
	sb.WriteString("// DO NOT EDIT!\n")
	sb.WriteString("//\n")
	sb.WriteString("// @generated\n")
	sb.WriteString("//\n\n")
}

func (g *Generator) generateEnum(sb *strings.Builder, e *ast.Enum) {
	sb.WriteString(fmt.Sprintf("public enum %s: Int32, Codable, CaseIterable {\n", e.Name))
	for _, m := range e.Members {
		sb.WriteString(fmt.Sprintf("    case %s = %d\n", lowerFirst(m.Name), m.Value))
	}
	sb.WriteString("\n")

	// Custom string description
	sb.WriteString("    public var description: String {\n")
	sb.WriteString("        switch self {\n")
	for _, m := range e.Members {
		sb.WriteString(fmt.Sprintf("        case .%s: return \"%s\"\n", lowerFirst(m.Name), m.Name))
	}
	sb.WriteString("        }\n")
	sb.WriteString("    }\n")
	sb.WriteString("}\n")
}

func (g *Generator) generateStruct(sb *strings.Builder, s *ast.Struct, ns *ast.Namespace) {
	// Generate struct
	sb.WriteString(fmt.Sprintf("public struct %s: Codable, TarsSerializable {\n", s.Name))

	// Properties
	for _, f := range s.Fields {
		swiftType := g.toSwiftType(f.Type)
		if !f.IsRequired {
			swiftType += "?"
		}
		defaultVal := ""
		if f.IsRequired {
			defaultVal = fmt.Sprintf(" = %s", g.getDefaultValue(f))
		}
		sb.WriteString(fmt.Sprintf("    public var %s: %s%s\n", lowerFirst(f.Name), swiftType, defaultVal))
	}
	sb.WriteString("\n")

	// CodingKeys enum for custom key mapping
	sb.WriteString("    private enum CodingKeys: String, CodingKey {\n")
	for _, f := range s.Fields {
		sb.WriteString(fmt.Sprintf("        case %s\n", lowerFirst(f.Name)))
	}
	sb.WriteString("    }\n\n")

	// Default initializer
	sb.WriteString("    public init() {}\n\n")

	// Full initializer
	sb.WriteString("    public init(\n")
	for i, f := range s.Fields {
		swiftType := g.toSwiftType(f.Type)
		defaultVal := ""
		if !f.IsRequired {
			swiftType += "?"
			defaultVal = " = nil"
		} else {
			defaultVal = fmt.Sprintf(" = %s", g.getDefaultValue(f))
		}
		comma := ","
		if i == len(s.Fields)-1 {
			comma = ""
		}
		sb.WriteString(fmt.Sprintf("        %s: %s%s%s\n", lowerFirst(f.Name), swiftType, defaultVal, comma))
	}
	sb.WriteString("    ) {\n")
	for _, f := range s.Fields {
		sb.WriteString(fmt.Sprintf("        self.%s = %s\n", lowerFirst(f.Name), lowerFirst(f.Name)))
	}
	sb.WriteString("    }\n\n")

	// TarsSerializable protocol
	sb.WriteString("    // MARK: - TarsSerializable\n\n")

	// writeTo method
	sb.WriteString("    public func writeTo(_ os: TarsOutputStream) throws {\n")
	for _, f := range s.Fields {
		fieldName := lowerFirst(f.Name)
		if !f.IsRequired {
			sb.WriteString(fmt.Sprintf("        if let %s = %s {\n", fieldName, fieldName))
			sb.WriteString(fmt.Sprintf("            try os.write(%s, tag: %d)\n", fieldName, f.Tag))
			sb.WriteString("        }\n")
		} else {
			sb.WriteString(fmt.Sprintf("        try os.write(%s, tag: %d)\n", fieldName, f.Tag))
		}
	}
	sb.WriteString("    }\n\n")

	// readFrom method
	sb.WriteString("    public mutating func readFrom(_ is: TarsInputStream) throws {\n")
	for _, f := range s.Fields {
		fieldName := lowerFirst(f.Name)
		if !f.IsRequired {
			sb.WriteString(fmt.Sprintf("        %s = try `is`.read(tag: %d, required: false)\n", fieldName, f.Tag))
		} else {
			sb.WriteString(fmt.Sprintf("        %s = try `is`.read(tag: %d, required: true)\n", fieldName, f.Tag))
		}
	}
	sb.WriteString("    }\n")

	sb.WriteString("}\n")
}

func (g *Generator) generateClientProxy(sb *strings.Builder, iface *ast.Interface, ns *ast.Namespace) {
	proxyName := iface.Name + "Proxy"

	// Generate result types for methods with out parameters
	for _, op := range iface.Operations {
		if g.hasOutParams(op) || (g.toSwiftType(op.ReturnType) != "Void" && g.hasOutParams(op)) {
			g.generateResultType(sb, op, iface.Name)
		}
	}

	sb.WriteString(fmt.Sprintf("public class %s: TarsServantProxy {\n", proxyName))
	sb.WriteString(fmt.Sprintf("    public static let servantName = \"%s.%s\"\n\n", ns.Name, iface.Name))

	// Override init
	sb.WriteString("    public override init(communicator: TarsCommunicator, servantName: String? = nil) {\n")
	sb.WriteString(fmt.Sprintf("        super.init(communicator: communicator, servantName: servantName ?? %s.servantName)\n", proxyName))
	sb.WriteString("    }\n\n")

	for _, op := range iface.Operations {
		g.generateProxyMethod(sb, op, iface.Name)
		sb.WriteString("\n")
	}

	sb.WriteString("}\n")
}

func (g *Generator) generateResultType(sb *strings.Builder, op *ast.Operation, ifaceName string) {
	typeName := ifaceName + upperFirst(op.Name) + "Result"

	sb.WriteString(fmt.Sprintf("public struct %s {\n", typeName))

	returnType := g.toSwiftType(op.ReturnType)
	if returnType != "Void" {
		sb.WriteString(fmt.Sprintf("    public let result: %s\n", returnType))
	}

	for _, p := range op.Params {
		if p.IsOut {
			sb.WriteString(fmt.Sprintf("    public let %s: %s\n", lowerFirst(p.Name), g.toSwiftType(p.Type)))
		}
	}

	sb.WriteString("}\n\n")
}

func (g *Generator) generateProxyMethod(sb *strings.Builder, op *ast.Operation, ifaceName string) {
	// Collect input params
	var inputParams []string
	for _, p := range op.Params {
		if !p.IsOut {
			inputParams = append(inputParams, fmt.Sprintf("%s: %s", lowerFirst(p.Name), g.toSwiftType(p.Type)))
		}
	}

	// Determine return type
	returnType := g.toSwiftType(op.ReturnType)
	hasOutParams := g.hasOutParams(op)

	var resultType string
	if hasOutParams {
		resultType = ifaceName + upperFirst(op.Name) + "Result"
	} else if returnType != "Void" {
		resultType = returnType
	} else {
		resultType = "Void"
	}

	// Method signature
	paramStr := strings.Join(inputParams, ", ")
	sb.WriteString(fmt.Sprintf("    public func %s(%s) async throws -> %s {\n", lowerFirst(op.Name), paramStr, resultType))

	// Create output stream
	sb.WriteString("        let os = TarsOutputStream()\n")

	// Write input parameters
	tagNum := 1
	for _, p := range op.Params {
		if !p.IsOut {
			sb.WriteString(fmt.Sprintf("        try os.write(%s, tag: %d)\n", lowerFirst(p.Name), tagNum))
		}
		tagNum++
	}

	// Invoke RPC
	sb.WriteString(fmt.Sprintf("        let response = try await invoke(funcName: \"%s\", request: os.getBuffer())\n", op.Name))

	// Parse response
	sb.WriteString("        let `is` = TarsInputStream(buffer: response)\n")

	// Read return value and out parameters
	if returnType != "Void" {
		sb.WriteString(fmt.Sprintf("        let result: %s = try `is`.read(tag: 0, required: true)\n", returnType))
	}

	tagNum = 1
	for _, p := range op.Params {
		if p.IsOut {
			sb.WriteString(fmt.Sprintf("        let %s: %s = try `is`.read(tag: %d, required: true)\n",
				lowerFirst(p.Name), g.toSwiftType(p.Type), tagNum))
		}
		tagNum++
	}

	// Return
	if hasOutParams {
		var returnFields []string
		if returnType != "Void" {
			returnFields = append(returnFields, "result: result")
		}
		for _, p := range op.Params {
			if p.IsOut {
				returnFields = append(returnFields, fmt.Sprintf("%s: %s", lowerFirst(p.Name), lowerFirst(p.Name)))
			}
		}
		sb.WriteString(fmt.Sprintf("        return %s(%s)\n", resultType, strings.Join(returnFields, ", ")))
	} else if returnType != "Void" {
		sb.WriteString("        return result\n")
	}

	sb.WriteString("    }\n")
}

func (g *Generator) generateServerProtocol(sb *strings.Builder, iface *ast.Interface, ns *ast.Namespace) {
	protocolName := iface.Name + "Servant"

	sb.WriteString(fmt.Sprintf("public protocol %s: AnyObject {\n", protocolName))

	for _, op := range iface.Operations {
		var params []string
		for _, p := range op.Params {
			paramType := g.toSwiftType(p.Type)
			if p.IsOut {
				paramType = "inout " + paramType
			}
			params = append(params, fmt.Sprintf("%s: %s", lowerFirst(p.Name), paramType))
		}
		params = append(params, "context: TarsContext")

		returnType := g.toSwiftType(op.ReturnType)
		if returnType == "Void" {
			returnType = ""
		} else {
			returnType = " -> " + returnType
		}

		sb.WriteString(fmt.Sprintf("    func %s(%s) async throws%s\n", lowerFirst(op.Name), strings.Join(params, ", "), returnType))
	}

	sb.WriteString("}\n")
}

func (g *Generator) generateServantBase(sb *strings.Builder, iface *ast.Interface, ns *ast.Namespace) {
	baseName := iface.Name + "ServantBase"
	protocolName := iface.Name + "Servant"

	sb.WriteString(fmt.Sprintf("open class %s: TarsServant {\n", baseName))
	sb.WriteString(fmt.Sprintf("    public static let servantName = \"%s.%s\"\n\n", ns.Name, iface.Name))

	sb.WriteString(fmt.Sprintf("    public weak var delegate: %s?\n\n", protocolName))

	sb.WriteString(fmt.Sprintf("    public init(delegate: %s) {\n", protocolName))
	sb.WriteString("        self.delegate = delegate\n")
	sb.WriteString("    }\n\n")

	// Dispatch method
	sb.WriteString("    public func dispatch(funcName: String, request: Data, context: TarsContext) async throws -> Data {\n")
	sb.WriteString("        guard let delegate = delegate else {\n")
	sb.WriteString("            throw TarsError.servantNotFound\n")
	sb.WriteString("        }\n\n")
	sb.WriteString("        let `is` = TarsInputStream(buffer: request)\n")
	sb.WriteString("        let os = TarsOutputStream()\n\n")
	sb.WriteString("        switch funcName {\n")

	for _, op := range iface.Operations {
		sb.WriteString(fmt.Sprintf("        case \"%s\":\n", op.Name))

		// Read input parameters
		tagNum := 1
		for _, p := range op.Params {
			if p.IsOut {
				sb.WriteString(fmt.Sprintf("            var %s: %s = %s\n",
					lowerFirst(p.Name), g.toSwiftType(p.Type), g.getTypeDefault(p.Type)))
			} else {
				sb.WriteString(fmt.Sprintf("            let %s: %s = try `is`.read(tag: %d, required: true)\n",
					lowerFirst(p.Name), g.toSwiftType(p.Type), tagNum))
			}
			tagNum++
		}

		// Call delegate
		var callParams []string
		for _, p := range op.Params {
			if p.IsOut {
				callParams = append(callParams, fmt.Sprintf("%s: &%s", lowerFirst(p.Name), lowerFirst(p.Name)))
			} else {
				callParams = append(callParams, fmt.Sprintf("%s: %s", lowerFirst(p.Name), lowerFirst(p.Name)))
			}
		}
		callParams = append(callParams, "context: context")

		returnType := g.toSwiftType(op.ReturnType)
		if returnType != "Void" {
			sb.WriteString(fmt.Sprintf("            let result = try await delegate.%s(%s)\n", lowerFirst(op.Name), strings.Join(callParams, ", ")))
			sb.WriteString("            try os.write(result, tag: 0)\n")
		} else {
			sb.WriteString(fmt.Sprintf("            try await delegate.%s(%s)\n", lowerFirst(op.Name), strings.Join(callParams, ", ")))
		}

		// Write out parameters
		tagNum = 1
		for _, p := range op.Params {
			if p.IsOut {
				sb.WriteString(fmt.Sprintf("            try os.write(%s, tag: %d)\n", lowerFirst(p.Name), tagNum))
			}
			tagNum++
		}
	}

	sb.WriteString("        default:\n")
	sb.WriteString("            throw TarsError.unknownFunction(funcName)\n")
	sb.WriteString("        }\n\n")
	sb.WriteString("        return os.getBuffer()\n")
	sb.WriteString("    }\n")

	sb.WriteString("}\n")
}

func (g *Generator) toSwiftType(t ast.Type) string {
	if t == nil {
		return "Void"
	}

	switch v := t.(type) {
	case *ast.BuiltinType:
		switch v.Kind {
		case ast.KindVoid:
			return "Void"
		case ast.KindBool:
			return "Bool"
		case ast.KindByte:
			if v.IsUnsigned {
				return "UInt8"
			}
			return "Int8"
		case ast.KindShort:
			if v.IsUnsigned {
				return "UInt16"
			}
			return "Int16"
		case ast.KindInt:
			if v.IsUnsigned {
				return "UInt32"
			}
			return "Int32"
		case ast.KindLong:
			if v.IsUnsigned {
				return "UInt64"
			}
			return "Int64"
		case ast.KindFloat:
			return "Float"
		case ast.KindDouble:
			return "Double"
		case ast.KindString:
			return "String"
		}
	case *ast.VectorType:
		if bt, ok := v.ElementType.(*ast.BuiltinType); ok && bt.Kind == ast.KindByte {
			return "Data"
		}
		return fmt.Sprintf("[%s]", g.toSwiftType(v.ElementType))
	case *ast.MapType:
		return fmt.Sprintf("[%s: %s]", g.toSwiftType(v.KeyType), g.toSwiftType(v.ValueType))
	case *ast.CustomType:
		return v.TypeName_
	}
	return "Any"
}

func (g *Generator) getDefaultValue(f *ast.Field) string {
	if f.HasDefault && f.DefaultValue != "" {
		return g.formatConstValue(f.DefaultValue, f.Type)
	}
	return g.getTypeDefault(f.Type)
}

func (g *Generator) getTypeDefault(t ast.Type) string {
	if t == nil {
		return "()"
	}

	switch v := t.(type) {
	case *ast.BuiltinType:
		switch v.Kind {
		case ast.KindBool:
			return "false"
		case ast.KindString:
			return "\"\""
		case ast.KindByte, ast.KindShort, ast.KindInt, ast.KindLong:
			return "0"
		case ast.KindFloat, ast.KindDouble:
			return "0.0"
		}
	case *ast.VectorType:
		if bt, ok := v.ElementType.(*ast.BuiltinType); ok && bt.Kind == ast.KindByte {
			return "Data()"
		}
		return "[]"
	case *ast.MapType:
		return "[:]"
	case *ast.CustomType:
		if g.enums[v.Name] || g.enums[v.TypeName_] {
			return fmt.Sprintf(".%s", lowerFirst(v.TypeName_))
		}
		return fmt.Sprintf("%s()", v.TypeName_)
	}
	return "nil"
}

func (g *Generator) formatConstValue(value string, t ast.Type) string {
	if t == nil {
		return value
	}

	if bt, ok := t.(*ast.BuiltinType); ok {
		switch bt.Kind {
		case ast.KindString:
			if !strings.HasPrefix(value, "\"") {
				return fmt.Sprintf("\"%s\"", value)
			}
		}
	}
	return value
}

func (g *Generator) hasOutParams(op *ast.Operation) bool {
	for _, p := range op.Params {
		if p.IsOut {
			return true
		}
	}
	return false
}

func lowerFirst(s string) string {
	if len(s) == 0 {
		return s
	}
	return strings.ToLower(s[:1]) + s[1:]
}

func upperFirst(s string) string {
	if len(s) == 0 {
		return s
	}
	return strings.ToUpper(s[:1]) + s[1:]
}
