/**
 * Tencent is pleased to support the open source community by making Tars available.
 *
 * Copyright (C) 2016THL A29 Limited, a Tencent company. All rights reserved.
 *
 * Licensed under the BSD 3-Clause License (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * https://opensource.org/licenses/BSD-3-Clause
 */

// Package php generates PHP code from Tars IDL
package php

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/TarsCloud/TarsCpp/tools/tarsc-go/pkg/ast"
)

// Generator generates PHP code
type Generator struct {
	baseDir string
}

// NewGenerator creates a new PHP generator
func NewGenerator(baseDir string) *Generator {
	return &Generator{baseDir: baseDir}
}

// Generate generates PHP code for the document
func (g *Generator) Generate(doc *ast.Document, baseName string) error {
	for _, ns := range doc.Namespaces {
		if err := g.generateNamespace(doc, ns, baseName); err != nil {
			return err
		}
	}
	return nil
}

func (g *Generator) generateNamespace(doc *ast.Document, ns *ast.Namespace, baseName string) error {
	var sb strings.Builder

	// PHP header
	sb.WriteString("<?php\n")
	sb.WriteString("// Generated by tarsc - Tars IDL Compiler\n")
	sb.WriteString("// DO NOT EDIT!\n\n")

	// Namespace
	sb.WriteString(fmt.Sprintf("namespace %s;\n\n", ns.Name))

	// Use statements
	sb.WriteString("use Tars\\Protocol\\Tars;\n\n")

	// Generate enums (as classes with constants)
	for _, e := range ns.Enums {
		sb.WriteString(g.generateEnum(e))
		sb.WriteString("\n")
	}

	// Generate structs
	for _, s := range ns.Structs {
		sb.WriteString(g.generateStruct(s))
		sb.WriteString("\n")
	}

	// Generate interfaces
	for _, iface := range ns.Interfaces {
		sb.WriteString(g.generateInterface(iface))
		sb.WriteString("\n")
	}

	// Write file
	dir := filepath.Join(g.baseDir, ns.Name)
	if err := os.MkdirAll(dir, 0755); err != nil {
		return err
	}

	filePath := filepath.Join(dir, baseName+".php")
	return os.WriteFile(filePath, []byte(sb.String()), 0644)
}

func (g *Generator) generateEnum(e *ast.Enum) string {
	var sb strings.Builder

	sb.WriteString(fmt.Sprintf("class %s\n{\n", e.Name))
	for _, m := range e.Members {
		sb.WriteString(fmt.Sprintf("    const %s = %d;\n", m.Name, m.Value))
	}
	sb.WriteString("}\n")

	return sb.String()
}

func (g *Generator) generateStruct(s *ast.Struct) string {
	var sb strings.Builder

	sb.WriteString(fmt.Sprintf("class %s extends \\Tars\\Protocol\\TarsStruct\n{\n", s.Name))

	// Fields
	sb.WriteString("    // Field definitions\n")
	for _, f := range s.Fields {
		sb.WriteString(fmt.Sprintf("    public $%s", f.Name))
		if f.HasDefault {
			sb.WriteString(fmt.Sprintf(" = %s", g.getPhpDefault(f)))
		} else {
			defaultVal := g.getTypeDefault(f.Type)
			if defaultVal != "" {
				sb.WriteString(fmt.Sprintf(" = %s", defaultVal))
			}
		}
		sb.WriteString(";\n")
	}
	sb.WriteString("\n")

	// _fields array for serialization
	sb.WriteString("    protected static $_fields = [\n")
	for _, f := range s.Fields {
		phpType := g.toPhpType(f.Type)
		required := "true"
		if !f.IsRequired {
			required = "false"
		}
		sb.WriteString(fmt.Sprintf("        %d => ['%s', '%s', %s],\n", f.Tag, f.Name, phpType, required))
	}
	sb.WriteString("    ];\n\n")

	// Constructor
	sb.WriteString("    public function __construct()\n")
	sb.WriteString("    {\n")
	sb.WriteString("        parent::__construct();\n")
	sb.WriteString("    }\n\n")

	// encode method
	sb.WriteString("    public function encode(\\Tars\\Protocol\\TarsOutputStream $os)\n")
	sb.WriteString("    {\n")
	for _, f := range s.Fields {
		sb.WriteString(fmt.Sprintf("        $os->write($this->%s, %d);\n", f.Name, f.Tag))
	}
	sb.WriteString("    }\n\n")

	// decode method
	sb.WriteString("    public function decode(\\Tars\\Protocol\\TarsInputStream $is)\n")
	sb.WriteString("    {\n")
	for _, f := range s.Fields {
		required := "true"
		if !f.IsRequired {
			required = "false"
		}
		sb.WriteString(fmt.Sprintf("        $this->%s = $is->read(%d, %s, $this->%s);\n", f.Name, f.Tag, required, f.Name))
	}
	sb.WriteString("    }\n")

	sb.WriteString("}\n")

	return sb.String()
}

func (g *Generator) generateInterface(iface *ast.Interface) string {
	var sb strings.Builder

	// Interface
	sb.WriteString(fmt.Sprintf("interface %sServant\n{\n", iface.Name))
	for _, op := range iface.Operations {
		sb.WriteString(g.generateOperation(op))
	}
	sb.WriteString("}\n\n")

	// Proxy class
	sb.WriteString(fmt.Sprintf("class %sProxy extends \\Tars\\Client\\CommunicatorConfig implements %sServant\n{\n", iface.Name, iface.Name))

	for _, op := range iface.Operations {
		sb.WriteString(g.generateProxyMethod(op))
		sb.WriteString("\n")
	}

	sb.WriteString("}\n")

	return sb.String()
}

func (g *Generator) generateOperation(op *ast.Operation) string {
	var params []string
	for _, p := range op.Params {
		if p.IsOut {
			params = append(params, fmt.Sprintf("&$%s", p.Name))
		} else {
			params = append(params, fmt.Sprintf("$%s", p.Name))
		}
	}

	return fmt.Sprintf("    public function %s(%s);\n", op.Name, strings.Join(params, ", "))
}

func (g *Generator) generateProxyMethod(op *ast.Operation) string {
	var sb strings.Builder

	var params []string
	for _, p := range op.Params {
		if p.IsOut {
			params = append(params, fmt.Sprintf("&$%s", p.Name))
		} else {
			params = append(params, fmt.Sprintf("$%s", p.Name))
		}
	}

	sb.WriteString(fmt.Sprintf("    public function %s(%s)\n", op.Name, strings.Join(params, ", ")))
	sb.WriteString("    {\n")
	sb.WriteString("        // TODO: Implement proxy call\n")
	sb.WriteString("    }\n")

	return sb.String()
}

func (g *Generator) toPhpType(t ast.Type) string {
	switch v := t.(type) {
	case *ast.BuiltinType:
		switch v.Kind {
		case ast.KindBool:
			return "bool"
		case ast.KindByte, ast.KindShort, ast.KindInt, ast.KindLong:
			return "int"
		case ast.KindFloat, ast.KindDouble:
			return "float"
		case ast.KindString:
			return "string"
		}
	case *ast.VectorType:
		return "vector"
	case *ast.MapType:
		return "map"
	case *ast.CustomType:
		return v.TypeName_
	}
	return "mixed"
}

func (g *Generator) getPhpDefault(f *ast.Field) string {
	if f.DefaultValue == "" {
		return g.getTypeDefault(f.Type)
	}

	switch v := f.Type.(type) {
	case *ast.BuiltinType:
		switch v.Kind {
		case ast.KindBool:
			if f.DefaultValue == "true" {
				return "true"
			}
			return "false"
		case ast.KindString:
			return f.DefaultValue
		default:
			return f.DefaultValue
		}
	}
	return f.DefaultValue
}

func (g *Generator) getTypeDefault(t ast.Type) string {
	switch v := t.(type) {
	case *ast.BuiltinType:
		switch v.Kind {
		case ast.KindBool:
			return "false"
		case ast.KindString:
			return "''"
		case ast.KindByte, ast.KindShort, ast.KindInt, ast.KindLong:
			return "0"
		case ast.KindFloat, ast.KindDouble:
			return "0.0"
		}
	case *ast.VectorType:
		return "[]"
	case *ast.MapType:
		return "[]"
	case *ast.CustomType:
		return fmt.Sprintf("new %s()", v.TypeName_)
	}
	return "null"
}
