/**
 * Tencent is pleased to support the open source community by making Tars available.
 *
 * Copyright (C) 2016THL A29 Limited, a Tencent company. All rights reserved.
 *
 * Licensed under the BSD 3-Clause License (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * https://opensource.org/licenses/BSD-3-Clause
 */

// Package python generates Python code from Tars IDL
package python

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/TarsCloud/TarsCpp/tools/tarsc-go/pkg/ast"
)

// Generator generates Python code
type Generator struct {
	baseDir string
	indent  int
}

// NewGenerator creates a new Python generator
func NewGenerator(baseDir string) *Generator {
	return &Generator{baseDir: baseDir}
}

// Generate generates Python code for the document
func (g *Generator) Generate(doc *ast.Document, baseName string) error {
	for _, ns := range doc.Namespaces {
		if err := g.generateNamespace(doc, ns, baseName); err != nil {
			return err
		}
	}
	return nil
}

func (g *Generator) generateNamespace(doc *ast.Document, ns *ast.Namespace, baseName string) error {
	var sb strings.Builder

	// Header
	sb.WriteString("# -*- coding: utf-8 -*-\n")
	sb.WriteString("# Generated by tarsc - Tars IDL Compiler\n")
	sb.WriteString("# DO NOT EDIT!\n\n")

	// Imports
	sb.WriteString("from tars.core import tarscore\n")
	sb.WriteString("from tars.__rpc import ServantProxy\n")

	// Include imports
	for _, inc := range doc.Includes {
		incName := strings.TrimSuffix(filepath.Base(inc), filepath.Ext(inc))
		sb.WriteString(fmt.Sprintf("from %s.%s import *\n", ns.Name, incName))
	}
	sb.WriteString("\n\n")

	// Generate enums
	for _, e := range ns.Enums {
		sb.WriteString(g.generateEnum(e))
		sb.WriteString("\n")
	}

	// Generate consts
	for _, c := range ns.Consts {
		sb.WriteString(g.generateConst(c))
	}
	if len(ns.Consts) > 0 {
		sb.WriteString("\n")
	}

	// Generate structs
	for _, s := range ns.Structs {
		sb.WriteString(g.generateStruct(s, ns))
		sb.WriteString("\n")
	}

	// Generate interfaces
	for _, iface := range ns.Interfaces {
		sb.WriteString(g.generateInterface(iface))
		sb.WriteString("\n")
	}

	// Write file
	dir := filepath.Join(g.baseDir, ns.Name)
	if err := os.MkdirAll(dir, 0755); err != nil {
		return err
	}

	filePath := filepath.Join(dir, baseName+".py")
	if err := os.WriteFile(filePath, []byte(sb.String()), 0644); err != nil {
		return err
	}

	// Create __init__.py
	initPath := filepath.Join(dir, "__init__.py")
	if _, err := os.Stat(initPath); os.IsNotExist(err) {
		os.WriteFile(initPath, []byte(""), 0644)
	}

	return nil
}

func (g *Generator) generateEnum(e *ast.Enum) string {
	var sb strings.Builder
	sb.WriteString(fmt.Sprintf("class %s:\n", e.Name))

	for _, m := range e.Members {
		sb.WriteString(fmt.Sprintf("    %s = %d\n", m.Name, m.Value))
	}

	return sb.String()
}

func (g *Generator) generateConst(c *ast.Const) string {
	return fmt.Sprintf("%s = %s\n", c.Name, c.Value)
}

func (g *Generator) generateStruct(s *ast.Struct, ns *ast.Namespace) string {
	var sb strings.Builder

	sb.WriteString(fmt.Sprintf("class %s(tarscore.struct):\n", s.Name))
	sb.WriteString(fmt.Sprintf("    __tars_class__ = \"%s.%s\"\n", ns.Name, s.Name))

	// Generate helper classes for vector and map fields
	for _, f := range s.Fields {
		if vt, ok := f.Type.(*ast.VectorType); ok {
			if _, isByte := vt.ElementType.(*ast.BuiltinType); !isByte || vt.ElementType.(*ast.BuiltinType).Kind != ast.KindByte {
				sb.WriteString(fmt.Sprintf("    vctcls_%s = %s\n", f.Name, g.makeDataType(f.Type)))
			}
		}
		if _, ok := f.Type.(*ast.MapType); ok {
			sb.WriteString(fmt.Sprintf("    mapcls_%s = %s\n", f.Name, g.makeDataType(f.Type)))
		}
	}

	// Constructor
	sb.WriteString("\n    def __init__(self):\n")
	for _, f := range s.Fields {
		sb.WriteString(fmt.Sprintf("        self.%s = %s\n", f.Name, g.getDefault(f, s.Name)))
	}

	// writeTo method
	sb.WriteString("\n    @staticmethod\n")
	sb.WriteString("    def writeTo(oos, value):\n")
	for _, f := range s.Fields {
		funcName := g.toFunctionName(f.Type, f.Name)
		sb.WriteString(fmt.Sprintf("        oos.write(%s, %d, value.%s)\n", funcName, f.Tag, f.Name))
	}

	// readFrom method
	sb.WriteString("\n    @staticmethod\n")
	sb.WriteString("    def readFrom(ios):\n")
	sb.WriteString(fmt.Sprintf("        value = %s()\n", s.Name))
	for _, f := range s.Fields {
		funcName := g.toFunctionName(f.Type, f.Name)
		required := "True"
		if !f.IsRequired {
			required = "False"
		}
		sb.WriteString(fmt.Sprintf("        value.%s = ios.read(%s, %d, %s, value.%s)\n",
			f.Name, funcName, f.Tag, required, f.Name))
	}
	sb.WriteString("        return value\n")

	return sb.String()
}

func (g *Generator) generateInterface(iface *ast.Interface) string {
	var sb strings.Builder

	sb.WriteString("# proxy for client\n")
	sb.WriteString(fmt.Sprintf("class %sProxy(ServantProxy):\n", iface.Name))

	for _, op := range iface.Operations {
		sb.WriteString(g.generateOperation(op))
	}

	return sb.String()
}

func (g *Generator) generateOperation(op *ast.Operation) string {
	var sb strings.Builder

	// Build parameters
	var params []string
	for _, p := range op.Params {
		if !p.IsOut {
			params = append(params, p.Name)
		}
	}
	params = append(params, "context=ServantProxy.mapcls_context()")

	sb.WriteString(fmt.Sprintf("    def %s(self, %s):\n", op.Name, strings.Join(params, ", ")))

	// Write input parameters
	sb.WriteString("        oos = tarscore.TarsOutputStream()\n")
	tagNum := 1
	for _, p := range op.Params {
		if !p.IsOut {
			sb.WriteString(fmt.Sprintf("        oos.write(%s, %d, %s)\n",
				g.makeDataType(p.Type), tagNum, p.Name))
		}
		tagNum++
	}

	sb.WriteString("\n")
	sb.WriteString(fmt.Sprintf("        rsp = self.tars_invoke(ServantProxy.TARSNORMAL, \"%s\", oos.getBuffer(), context, None)\n\n", op.Name))

	// Read output
	hasOutput := false
	if op.ReturnType != nil {
		if bt, ok := op.ReturnType.(*ast.BuiltinType); !ok || bt.Kind != ast.KindVoid {
			hasOutput = true
		}
	}
	for _, p := range op.Params {
		if p.IsOut {
			hasOutput = true
		}
	}

	if hasOutput {
		sb.WriteString("        ios = tarscore.TarsInputStream(rsp.sBuffer)\n")

		var returns []string
		if op.ReturnType != nil {
			if bt, ok := op.ReturnType.(*ast.BuiltinType); !ok || bt.Kind != ast.KindVoid {
				sb.WriteString(fmt.Sprintf("        ret = ios.read(%s, 0, True)\n", g.makeDataType(op.ReturnType)))
				returns = append(returns, "ret")
			}
		}

		tagNum = 1
		for _, p := range op.Params {
			if p.IsOut {
				sb.WriteString(fmt.Sprintf("        %s = ios.read(%s, %d, True)\n",
					p.Name, g.makeDataType(p.Type), tagNum))
				returns = append(returns, p.Name)
			}
			tagNum++
		}

		if len(returns) > 0 {
			sb.WriteString(fmt.Sprintf("\n        return (%s)\n", strings.Join(returns, ", ")))
		}
	}

	sb.WriteString("\n")
	return sb.String()
}

func (g *Generator) toFunctionName(t ast.Type, name string) string {
	switch v := t.(type) {
	case *ast.BuiltinType:
		switch v.Kind {
		case ast.KindBool:
			return "tarscore.boolean"
		case ast.KindString:
			return "tarscore.string"
		case ast.KindByte:
			return "tarscore.int8"
		case ast.KindShort:
			if v.IsUnsigned {
				return "tarscore.uint8"
			}
			return "tarscore.int16"
		case ast.KindInt:
			if v.IsUnsigned {
				return "tarscore.uint16"
			}
			return "tarscore.int32"
		case ast.KindLong:
			if v.IsUnsigned {
				return "tarscore.uint32"
			}
			return "tarscore.int64"
		case ast.KindFloat:
			return "tarscore.float"
		case ast.KindDouble:
			return "tarscore.double"
		}
	case *ast.VectorType:
		if bt, ok := v.ElementType.(*ast.BuiltinType); ok && bt.Kind == ast.KindByte {
			return "tarscore.bytes"
		}
		return "value.vctcls_" + name
	case *ast.MapType:
		return "value.mapcls_" + name
	case *ast.CustomType:
		return v.TypeName_
	}
	return "tarscore.int32"
}

func (g *Generator) makeDataType(t ast.Type) string {
	switch v := t.(type) {
	case *ast.BuiltinType:
		switch v.Kind {
		case ast.KindBool:
			return "tarscore.boolean"
		case ast.KindString:
			return "tarscore.string"
		case ast.KindByte:
			return "tarscore.int8"
		case ast.KindShort:
			if v.IsUnsigned {
				return "tarscore.uint8"
			}
			return "tarscore.int16"
		case ast.KindInt:
			if v.IsUnsigned {
				return "tarscore.uint16"
			}
			return "tarscore.int32"
		case ast.KindLong:
			if v.IsUnsigned {
				return "tarscore.uint32"
			}
			return "tarscore.int64"
		case ast.KindFloat:
			return "tarscore.float"
		case ast.KindDouble:
			return "tarscore.double"
		}
	case *ast.VectorType:
		if bt, ok := v.ElementType.(*ast.BuiltinType); ok && bt.Kind == ast.KindByte {
			return "tarscore.bytes"
		}
		return fmt.Sprintf("tarscore.vctclass(%s)", g.makeDataType(v.ElementType))
	case *ast.MapType:
		return fmt.Sprintf("tarscore.mapclass(%s, %s)", g.makeDataType(v.KeyType), g.makeDataType(v.ValueType))
	case *ast.CustomType:
		return v.TypeName_
	}
	return "tarscore.int32"
}

func (g *Generator) getDefault(f *ast.Field, structName string) string {
	if f.HasDefault && f.DefaultValue != "" {
		return g.formatDefault(f.Type, f.DefaultValue)
	}

	switch v := f.Type.(type) {
	case *ast.BuiltinType:
		switch v.Kind {
		case ast.KindBool:
			return "False"
		case ast.KindString:
			return "\"\""
		case ast.KindByte, ast.KindShort, ast.KindInt, ast.KindLong:
			return "0"
		case ast.KindFloat, ast.KindDouble:
			return "0.0"
		}
	case *ast.VectorType:
		if bt, ok := v.ElementType.(*ast.BuiltinType); ok && bt.Kind == ast.KindByte {
			return "bytes()"
		}
		return fmt.Sprintf("%s.vctcls_%s()", structName, f.Name)
	case *ast.MapType:
		return fmt.Sprintf("%s.mapcls_%s()", structName, f.Name)
	case *ast.CustomType:
		return v.TypeName_ + "()"
	}
	return "None"
}

func (g *Generator) formatDefault(t ast.Type, value string) string {
	switch v := t.(type) {
	case *ast.BuiltinType:
		switch v.Kind {
		case ast.KindBool:
			if value == "true" {
				return "True"
			}
			return "False"
		case ast.KindString:
			return value
		default:
			return value
		}
	}
	return value
}
