/**
 * Tencent is pleased to support the open source community by making Tars available.
 *
 * Copyright (C) 2016THL A29 Limited, a Tencent company. All rights reserved.
 *
 * Licensed under the BSD 3-Clause License (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * https://opensource.org/licenses/BSD-3-Clause
 */

// Package rust generates Rust code from Tars IDL.
//
// Output is wired against the tars-rs workspace:
//   - tars_core::codec for TLV encode/decode (Buffer, Reader, TarsEncode, TarsDecode, TarsStruct)
//   - tars_protocol::protocol for RequestPacket / ResponsePacket
//   - tars_rpc::servant::ServantProxy for client-side calls
//   - tars_transport::transport::ServerProtocolHandler for server-side dispatch
//
// Per interface the generator emits three items:
//   - `pub trait <Iface>` (async, user-implemented servant)
//   - `pub struct <Iface>Proxy` (client; wraps Arc<ServantProxy>)
//   - `pub struct <Iface>Servant<T: <Iface>>` (server-side dispatcher implementing ServerProtocolHandler)
package rust

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/TarsCloud/TarsCpp/tools/tarsc-go/pkg/ast"
)

// Generator generates Rust code
type Generator struct {
	baseDir string
}

// NewGenerator creates a new Rust generator
func NewGenerator(baseDir string) *Generator {
	return &Generator{baseDir: baseDir}
}

// Generate generates Rust code for the document
func (g *Generator) Generate(doc *ast.Document, baseName string) error {
	for _, ns := range doc.Namespaces {
		if err := g.generateNamespace(ns, baseName); err != nil {
			return err
		}
	}
	return nil
}

func (g *Generator) generateNamespace(ns *ast.Namespace, baseName string) error {
	var sb strings.Builder

	// File header
	sb.WriteString("// Generated by tarsc - Tars IDL Compiler\n")
	sb.WriteString("// DO NOT EDIT!\n\n")

	sb.WriteString("#![allow(dead_code, unused_imports, unused_mut, unused_variables, non_snake_case, non_camel_case_types, clippy::all)]\n\n")

	// Top-level imports
	sb.WriteString("use std::collections::HashMap;\n")
	sb.WriteString("use std::sync::Arc;\n")
	sb.WriteString("use async_trait::async_trait;\n")
	sb.WriteString("use tars_core::{consts, Context, Result, TarsError};\n")
	sb.WriteString("use tars_core::codec::{Buffer, PackageStatus, Reader, TarsDecode, TarsEncode, TarsStruct, TarsType, parse_package};\n")
	sb.WriteString("use tars_protocol::protocol::{RequestPacket, ResponsePacket};\n")
	sb.WriteString("use tars_rpc::servant::ServantProxy;\n")
	sb.WriteString("use tars_transport::transport::ServerProtocolHandler;\n\n")

	// Module
	modName := toSnakeCase(ns.Name)
	sb.WriteString(fmt.Sprintf("pub mod %s {\n", modName))
	sb.WriteString("    use super::*;\n\n")

	// Consts
	for _, c := range ns.Consts {
		sb.WriteString(g.generateConst(c))
	}
	if len(ns.Consts) > 0 {
		sb.WriteString("\n")
	}

	// Enums
	for _, e := range ns.Enums {
		sb.WriteString(g.generateEnum(e))
		sb.WriteString("\n")
	}

	// Structs
	for _, s := range ns.Structs {
		sb.WriteString(g.generateStruct(s))
		sb.WriteString("\n")
	}

	// Interfaces
	for _, iface := range ns.Interfaces {
		sb.WriteString(g.generateInterface(iface))
		sb.WriteString("\n")
	}

	sb.WriteString("}\n")

	// Write file
	if err := os.MkdirAll(g.baseDir, 0755); err != nil {
		return err
	}
	filePath := filepath.Join(g.baseDir, baseName+".rs")
	return os.WriteFile(filePath, []byte(sb.String()), 0644)
}

// ----- Consts -----

func (g *Generator) generateConst(c *ast.Const) string {
	if bt, ok := c.Type.(*ast.BuiltinType); ok && bt.Kind == ast.KindString {
		return fmt.Sprintf("    pub const %s: &str = %s;\n", strings.ToUpper(c.Name), c.Value)
	}
	return fmt.Sprintf("    pub const %s: %s = %s;\n", strings.ToUpper(c.Name), g.toRustType(c.Type), c.Value)
}

// ----- Enums -----

func (g *Generator) generateEnum(e *ast.Enum) string {
	var sb strings.Builder

	sb.WriteString("    #[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]\n")
	sb.WriteString("    #[repr(i32)]\n")
	sb.WriteString(fmt.Sprintf("    pub enum %s {\n", e.Name))
	for _, m := range e.Members {
		sb.WriteString(fmt.Sprintf("        %s = %d,\n", m.Name, m.Value))
	}
	sb.WriteString("    }\n\n")

	// Default
	if len(e.Members) > 0 {
		sb.WriteString(fmt.Sprintf("    impl Default for %s {\n", e.Name))
		sb.WriteString("        fn default() -> Self {\n")
		sb.WriteString(fmt.Sprintf("            %s::%s\n", e.Name, e.Members[0].Name))
		sb.WriteString("        }\n")
		sb.WriteString("    }\n\n")
	}

	// From<i32>
	sb.WriteString(fmt.Sprintf("    impl From<i32> for %s {\n", e.Name))
	sb.WriteString("        fn from(value: i32) -> Self {\n")
	sb.WriteString("            match value {\n")
	for _, m := range e.Members {
		sb.WriteString(fmt.Sprintf("                %d => %s::%s,\n", m.Value, e.Name, m.Name))
	}
	if len(e.Members) > 0 {
		sb.WriteString(fmt.Sprintf("                _ => %s::%s,\n", e.Name, e.Members[0].Name))
	} else {
		sb.WriteString("                _ => unreachable!(),\n")
	}
	sb.WriteString("            }\n")
	sb.WriteString("        }\n")
	sb.WriteString("    }\n\n")

	// TarsEncode
	sb.WriteString(fmt.Sprintf("    impl TarsEncode for %s {\n", e.Name))
	sb.WriteString("        fn encode(&self, buf: &mut Buffer, tag: u8) -> Result<()> {\n")
	sb.WriteString("            (*self as i32).encode(buf, tag)\n")
	sb.WriteString("        }\n")
	sb.WriteString("    }\n\n")

	// TarsDecode
	sb.WriteString(fmt.Sprintf("    impl TarsDecode for %s {\n", e.Name))
	sb.WriteString("        fn decode(reader: &mut Reader, tag: u8, require: bool) -> Result<Self> {\n")
	sb.WriteString("            let v = i32::decode(reader, tag, require)?;\n")
	sb.WriteString(fmt.Sprintf("            Ok(%s::from(v))\n", e.Name))
	sb.WriteString("        }\n")
	sb.WriteString("    }\n")

	return sb.String()
}

// ----- Structs -----

func (g *Generator) generateStruct(s *ast.Struct) string {
	var sb strings.Builder

	sb.WriteString("    #[derive(Debug, Clone, Default)]\n")
	sb.WriteString(fmt.Sprintf("    pub struct %s {\n", s.Name))
	for _, f := range s.Fields {
		sb.WriteString(fmt.Sprintf("        pub %s: %s,\n", g.toRustFieldName(f.Name), g.toRustType(f.Type)))
	}
	sb.WriteString("    }\n\n")

	// TarsStruct
	sb.WriteString(fmt.Sprintf("    impl TarsStruct for %s {\n", s.Name))

	// write_to
	sb.WriteString("        fn write_to(&self, buf: &mut Buffer) -> Result<()> {\n")
	for _, f := range s.Fields {
		fieldName := g.toRustFieldName(f.Name)
		g.emitEncode(&sb, "            ", "buf", true, "self."+fieldName, f.Type, f.Tag)
	}
	sb.WriteString("            Ok(())\n")
	sb.WriteString("        }\n\n")

	// read_from
	sb.WriteString("        fn read_from(reader: &mut Reader) -> Result<Self> {\n")
	sb.WriteString("            let mut __out = Self::default();\n")
	for _, f := range s.Fields {
		fieldName := g.toRustFieldName(f.Name)
		g.emitDecode(&sb, "            ", "__out."+fieldName, "reader", true, f.Type, f.Tag, f.IsRequired, "")
	}
	sb.WriteString("            Ok(__out)\n")
	sb.WriteString("        }\n")
	sb.WriteString("    }\n\n")

	// TarsEncode
	sb.WriteString(fmt.Sprintf("    impl TarsEncode for %s {\n", s.Name))
	sb.WriteString("        fn encode(&self, buf: &mut Buffer, tag: u8) -> Result<()> {\n")
	sb.WriteString("            buf.write_struct_begin(tag)?;\n")
	sb.WriteString("            self.write_to(buf)?;\n")
	sb.WriteString("            buf.write_struct_end()?;\n")
	sb.WriteString("            Ok(())\n")
	sb.WriteString("        }\n")
	sb.WriteString("    }\n\n")

	// TarsDecode
	sb.WriteString(fmt.Sprintf("    impl TarsDecode for %s {\n", s.Name))
	sb.WriteString("        fn decode(reader: &mut Reader, tag: u8, require: bool) -> Result<Self> {\n")
	sb.WriteString("            if !reader.read_struct_begin(tag, require)? {\n")
	sb.WriteString("                return Ok(Self::default());\n")
	sb.WriteString("            }\n")
	sb.WriteString("            let __out = Self::read_from(reader)?;\n")
	sb.WriteString("            reader.read_struct_end()?;\n")
	sb.WriteString("            Ok(__out)\n")
	sb.WriteString("        }\n")
	sb.WriteString("    }\n")

	return sb.String()
}

// ----- Interfaces -----

func (g *Generator) generateInterface(iface *ast.Interface) string {
	var sb strings.Builder

	g.generateServantTrait(&sb, iface)
	sb.WriteString("\n")
	g.generateProxy(&sb, iface)
	sb.WriteString("\n")
	g.generateServantImpl(&sb, iface)

	return sb.String()
}

// Server-side trait that the user implements.
func (g *Generator) generateServantTrait(sb *strings.Builder, iface *ast.Interface) {
	sb.WriteString("    /// Servant trait — implement this on the server side.\n")
	sb.WriteString("    #[async_trait]\n")
	sb.WriteString(fmt.Sprintf("    pub trait %s: Send + Sync + 'static {\n", iface.Name))
	for _, op := range iface.Operations {
		sb.WriteString("        ")
		sb.WriteString(g.formatTraitMethodSig(op))
		sb.WriteString(";\n")
	}
	sb.WriteString("    }\n")
}

// Returns: "async fn name(&self, ctx: &Context, p1: T1, ...) -> Result<RetTuple>"
func (g *Generator) formatTraitMethodSig(op *ast.Operation) string {
	params := []string{"&self", "ctx: &Context"}
	for _, p := range op.Params {
		if p.IsOut {
			continue
		}
		params = append(params, fmt.Sprintf("%s: %s", g.toRustFieldName(p.Name), g.toRustType(p.Type)))
	}
	return fmt.Sprintf("async fn %s(%s) -> Result<%s>", g.toRustMethodName(op.Name), strings.Join(params, ", "), g.formatReturnTuple(op))
}

// Build the return tuple type: (Ret, OutParam1, OutParam2, ...) or just `Ret` / `()`.
func (g *Generator) formatReturnTuple(op *ast.Operation) string {
	hasReturn := !isVoid(op.ReturnType)
	var outs []string
	for _, p := range op.Params {
		if p.IsOut {
			outs = append(outs, g.toRustType(p.Type))
		}
	}

	if !hasReturn && len(outs) == 0 {
		return "()"
	}

	var parts []string
	if hasReturn {
		parts = append(parts, g.toRustType(op.ReturnType))
	}
	parts = append(parts, outs...)

	if len(parts) == 1 {
		return parts[0]
	}
	return "(" + strings.Join(parts, ", ") + ")"
}

// Client-side proxy struct + impl block.
func (g *Generator) generateProxy(sb *strings.Builder, iface *ast.Interface) {
	sb.WriteString("    /// Client-side proxy. Wraps an `Arc<ServantProxy>` and serializes calls.\n")
	sb.WriteString("    #[derive(Clone)]\n")
	sb.WriteString(fmt.Sprintf("    pub struct %sProxy {\n", iface.Name))
	sb.WriteString("        proxy: Arc<ServantProxy>,\n")
	sb.WriteString("    }\n\n")

	sb.WriteString(fmt.Sprintf("    impl %sProxy {\n", iface.Name))
	sb.WriteString("        pub fn new(proxy: Arc<ServantProxy>) -> Self {\n")
	sb.WriteString("            Self { proxy }\n")
	sb.WriteString("        }\n\n")
	sb.WriteString("        pub fn proxy(&self) -> &Arc<ServantProxy> {\n")
	sb.WriteString("            &self.proxy\n")
	sb.WriteString("        }\n\n")

	for i, op := range iface.Operations {
		if i > 0 {
			sb.WriteString("\n")
		}
		g.generateProxyMethod(sb, op)
	}

	sb.WriteString("    }\n")
}

func (g *Generator) generateProxyMethod(sb *strings.Builder, op *ast.Operation) {
	// Build param list (excluding out params; ctx by value for ergonomics)
	params := []string{"&self", "ctx: Context"}
	for _, p := range op.Params {
		if p.IsOut {
			continue
		}
		params = append(params, fmt.Sprintf("%s: %s", g.toRustFieldName(p.Name), g.toRustType(p.Type)))
	}
	ret := g.formatReturnTuple(op)

	sb.WriteString(fmt.Sprintf("        pub async fn %s(%s) -> Result<%s> {\n",
		g.toRustMethodName(op.Name), strings.Join(params, ", "), ret))

	// Encode input params into a Buffer
	sb.WriteString("            let mut __buf = Buffer::new();\n")
	tag := 0
	for _, p := range op.Params {
		tag++ // tags are 1-based and cover both in and out for the wire format
		if p.IsOut {
			continue
		}
		g.emitEncode(sb, "            ", "__buf", false, g.toRustFieldName(p.Name), p.Type, tag)
	}

	sb.WriteString(fmt.Sprintf("            let __resp = self.proxy.invoke(ctx, %q, __buf.to_bytes(), HashMap::new(), HashMap::new()).await?;\n", op.Name))
	sb.WriteString("            let mut __reader = Reader::new(&__resp.s_buffer);\n")

	// Decode return value (tag 0) and out params (their position-based tag)
	hasReturn := !isVoid(op.ReturnType)
	if hasReturn {
		g.emitDecode(sb, "            ", "let __ret", "__reader", false, op.ReturnType, 0, true, "")
	}
	tag = 0
	var outVars []string
	for _, p := range op.Params {
		tag++
		if !p.IsOut {
			continue
		}
		varName := "__out_" + g.toRustFieldName(p.Name)
		outVars = append(outVars, varName)
		g.emitDecode(sb, "            ", "let "+varName, "__reader", false, p.Type, tag, true, "")
	}

	// Build return expression
	var parts []string
	if hasReturn {
		parts = append(parts, "__ret")
	}
	parts = append(parts, outVars...)
	switch len(parts) {
	case 0:
		sb.WriteString("            Ok(())\n")
	case 1:
		sb.WriteString(fmt.Sprintf("            Ok(%s)\n", parts[0]))
	default:
		sb.WriteString(fmt.Sprintf("            Ok((%s))\n", strings.Join(parts, ", ")))
	}

	sb.WriteString("        }\n")
}

// Server-side dispatcher: Servant<T> impls ServerProtocolHandler.
func (g *Generator) generateServantImpl(sb *strings.Builder, iface *ast.Interface) {
	sb.WriteString("    /// Server-side dispatcher. Wraps a user-supplied `T: " + iface.Name + "` and\n")
	sb.WriteString("    /// implements `ServerProtocolHandler` for use with `Application::add_servant`.\n")
	sb.WriteString(fmt.Sprintf("    pub struct %sServant<T: %s> {\n", iface.Name, iface.Name))
	sb.WriteString("        inner: Arc<T>,\n")
	sb.WriteString("    }\n\n")

	sb.WriteString(fmt.Sprintf("    impl<T: %s> %sServant<T> {\n", iface.Name, iface.Name))
	sb.WriteString("        pub fn new(inner: T) -> Self {\n")
	sb.WriteString("            Self { inner: Arc::new(inner) }\n")
	sb.WriteString("        }\n\n")
	sb.WriteString("        pub fn from_arc(inner: Arc<T>) -> Self {\n")
	sb.WriteString("            Self { inner }\n")
	sb.WriteString("        }\n\n")

	// Inherent dispatch helper — uses `?` and returns Result<Vec<u8>>.
	sb.WriteString("        async fn __dispatch(&self, ctx: &mut Context, __req: &RequestPacket) -> Result<Vec<u8>> {\n")
	sb.WriteString("            match __req.s_func_name.as_str() {\n")
	for _, op := range iface.Operations {
		g.emitDispatchArm(sb, "                ", op)
	}
	sb.WriteString("                __other => Err(TarsError::Protocol(format!(\"unknown method: {}\", __other))),\n")
	sb.WriteString("            }\n")
	sb.WriteString("        }\n")

	sb.WriteString("    }\n\n")

	sb.WriteString("    #[async_trait]\n")
	sb.WriteString(fmt.Sprintf("    impl<T: %s> ServerProtocolHandler for %sServant<T> {\n", iface.Name, iface.Name))
	sb.WriteString("        fn parse_package(&self, buff: &[u8]) -> (usize, PackageStatus) {\n")
	sb.WriteString("            parse_package(buff)\n")
	sb.WriteString("        }\n\n")

	sb.WriteString("        async fn invoke(&self, ctx: &mut Context, pkg: &[u8]) -> Vec<u8> {\n")
	sb.WriteString("            let __req = match RequestPacket::decode(pkg) {\n")
	sb.WriteString("                Ok(r) => r,\n")
	sb.WriteString("                Err(e) => {\n")
	sb.WriteString("                    return ResponsePacket::error(0, consts::TARS_SERVER_DECODE_ERR, &e.to_string())\n")
	sb.WriteString("                        .encode().unwrap_or_default();\n")
	sb.WriteString("                }\n")
	sb.WriteString("            };\n")
	sb.WriteString("            let __request_id = __req.i_request_id;\n")
	sb.WriteString("            match self.__dispatch(ctx, &__req).await {\n")
	sb.WriteString("                Ok(__buf) => ResponsePacket::success(__request_id, __buf).encode().unwrap_or_default(),\n")
	sb.WriteString("                Err(TarsError::ServerError { code, message }) => ResponsePacket::error(__request_id, code, &message).encode().unwrap_or_default(),\n")
	sb.WriteString("                Err(e) => ResponsePacket::error(__request_id, consts::TARS_SERVER_UNKNOWN_ERR, &e.to_string()).encode().unwrap_or_default(),\n")
	sb.WriteString("            }\n")
	sb.WriteString("        }\n\n")

	sb.WriteString("        fn invoke_timeout(&self, pkg: &[u8]) -> Vec<u8> {\n")
	sb.WriteString("            let __id = RequestPacket::decode(pkg).map(|r| r.i_request_id).unwrap_or(0);\n")
	sb.WriteString("            ResponsePacket::timeout(__id).encode().unwrap_or_default()\n")
	sb.WriteString("        }\n\n")

	sb.WriteString("        fn get_close_msg(&self) -> Vec<u8> {\n")
	sb.WriteString("            Vec::new()\n")
	sb.WriteString("        }\n\n")

	sb.WriteString("        fn do_close(&self, _ctx: &Context) {}\n")
	sb.WriteString("    }\n")
}

// Emit one match-arm in the dispatcher for the given operation.
func (g *Generator) emitDispatchArm(sb *strings.Builder, indent string, op *ast.Operation) {
	sb.WriteString(fmt.Sprintf("%s%q => {\n", indent, op.Name))
	body := indent + "    "

	// Decode in-params
	sb.WriteString(body + "let mut __reader = Reader::new(&__req.s_buffer);\n")
	tag := 0
	var inArgs []string
	for _, p := range op.Params {
		tag++
		if p.IsOut {
			continue
		}
		argName := g.toRustFieldName(p.Name)
		inArgs = append(inArgs, argName)
		g.emitDecode(sb, body, "let "+argName, "__reader", false, p.Type, tag, true, "")
	}

	// Initialize out params with defaults so we can pass &mut to user impl... but the trait
	// signature returns out params via the result tuple instead. So we just call the trait
	// method and unpack the tuple.
	hasReturn := !isVoid(op.ReturnType)
	var outNames []string
	for _, p := range op.Params {
		if p.IsOut {
			outNames = append(outNames, "__out_"+g.toRustFieldName(p.Name))
		}
	}

	// Build call expression
	callArgs := strings.Join(inArgs, ", ")
	sep := ""
	if callArgs != "" {
		sep = ", "
	}
	// LHS pattern for await result
	var lhs string
	switch {
	case !hasReturn && len(outNames) == 0:
		lhs = "()"
	case hasReturn && len(outNames) == 0:
		lhs = "__ret"
	case !hasReturn && len(outNames) == 1:
		lhs = outNames[0]
	default:
		var parts []string
		if hasReturn {
			parts = append(parts, "__ret")
		}
		parts = append(parts, outNames...)
		lhs = "(" + strings.Join(parts, ", ") + ")"
	}

	sb.WriteString(fmt.Sprintf("%slet %s = self.inner.%s(ctx%s%s).await?;\n",
		body, lhs, g.toRustMethodName(op.Name), sep, callArgs))

	// Encode response
	sb.WriteString(body + "let mut __out = Buffer::new();\n")
	if hasReturn {
		g.emitEncode(sb, body, "__out", false, "__ret", op.ReturnType, 0)
	}
	tag = 0
	for _, p := range op.Params {
		tag++
		if !p.IsOut {
			continue
		}
		g.emitEncode(sb, body, "__out", false, "__out_"+g.toRustFieldName(p.Name), p.Type, tag)
	}
	sb.WriteString(body + "Ok(__out.to_bytes())\n")
	sb.WriteString(indent + "}\n")
}

// ----- Codec emit helpers -----
//
// `bufName` / `readerName` are the variable names used for inherent method calls
// (e.g., `<bufName>.write_head(...)`). `bufIsRef` / `readerIsRef` say whether the
// variable is already an `&mut Buffer` / `&mut Reader`; when true we pass it as
// `<name>` to `TarsEncode::encode` / `TarsDecode::decode`, when false we prefix
// `&mut`.

func (g *Generator) bufRef(bufName string, bufIsRef bool) string {
	if bufIsRef {
		return bufName
	}
	return "&mut " + bufName
}

func (g *Generator) readerRef(readerName string, readerIsRef bool) string {
	if readerIsRef {
		return readerName
	}
	return "&mut " + readerName
}

// emitEncode writes encode statements for `varExpr: t` at `tag`, targeting the
// buffer named `bufName`.
func (g *Generator) emitEncode(sb *strings.Builder, indent, bufName string, bufIsRef bool, varExpr string, t ast.Type, tag int) {
	bufRef := g.bufRef(bufName, bufIsRef)
	switch v := t.(type) {
	case *ast.VectorType:
		if bt, ok := v.ElementType.(*ast.BuiltinType); ok && bt.Kind == ast.KindByte && !bt.IsUnsigned {
			sb.WriteString(fmt.Sprintf("%s%s.encode(%s, %d)?;\n", indent, varExpr, bufRef, tag))
			return
		}
		sb.WriteString(fmt.Sprintf("%s%s.write_head(TarsType::List, %d)?;\n", indent, bufName, tag))
		sb.WriteString(fmt.Sprintf("%s%s.write_int32(%s.len() as i32, 0)?;\n", indent, bufName, varExpr))
		sb.WriteString(fmt.Sprintf("%sfor __item in %s.iter() {\n", indent, varExpr))
		g.emitEncode(sb, indent+"    ", bufName, bufIsRef, "__item", v.ElementType, 0)
		sb.WriteString(indent + "}\n")
	case *ast.MapType:
		sb.WriteString(fmt.Sprintf("%s%s.write_head(TarsType::Map, %d)?;\n", indent, bufName, tag))
		sb.WriteString(fmt.Sprintf("%s%s.write_int32(%s.len() as i32, 0)?;\n", indent, bufName, varExpr))
		sb.WriteString(fmt.Sprintf("%sfor (__k, __v) in %s.iter() {\n", indent, varExpr))
		g.emitEncode(sb, indent+"    ", bufName, bufIsRef, "__k", v.KeyType, 0)
		g.emitEncode(sb, indent+"    ", bufName, bufIsRef, "__v", v.ValueType, 1)
		sb.WriteString(indent + "}\n")
	default:
		sb.WriteString(fmt.Sprintf("%s%s.encode(%s, %d)?;\n", indent, varExpr, bufRef, tag))
	}
}

// emitDecode emits a statement that decodes a value of `t` from `readerName` at
// `tag` and assigns it to `lhs`. `lhs` may be:
//   - `"let foo"` — emits `let foo: T = ...;`
//   - a path like `"__out.field"` — emits `__out.field = ...;` (no type annotation)
//
// `tmpSuffix` is appended to internal `__len`, `__vec`, `__item` etc. so nested
// emissions don't shadow.
func (g *Generator) emitDecode(sb *strings.Builder, indent, lhs, readerName string, readerIsRef bool, t ast.Type, tag int, require bool, tmpSuffix string) {
	requireLit := "false"
	if require {
		requireLit = "true"
	}
	readerRef := g.readerRef(readerName, readerIsRef)
	isLet := strings.HasPrefix(lhs, "let ")

	rhs := func(expr string) string {
		if isLet {
			return fmt.Sprintf("%s%s: %s = %s;\n", indent, lhs, g.toRustType(t), expr)
		}
		return fmt.Sprintf("%s%s = %s;\n", indent, lhs, expr)
	}

	switch v := t.(type) {
	case *ast.VectorType:
		if bt, ok := v.ElementType.(*ast.BuiltinType); ok && bt.Kind == ast.KindByte && !bt.IsUnsigned {
			sb.WriteString(rhs(fmt.Sprintf("<%s as TarsDecode>::decode(%s, %d, %s)?", g.toRustType(t), readerRef, tag, requireLit)))
			return
		}
		// Inline list decode as a block expression.
		lenVar := "__len" + tmpSuffix
		vecVar := "__vec" + tmpSuffix
		itemVar := "__item" + tmpSuffix
		elemType := g.toRustType(v.ElementType)

		var inner strings.Builder
		inner.WriteString("{\n")
		inner.WriteString(fmt.Sprintf("%s    let %s = %s.read_list_begin(%d, %s)?;\n", indent, lenVar, readerName, tag, requireLit))
		inner.WriteString(fmt.Sprintf("%s    let mut %s: Vec<%s> = Vec::with_capacity(%s as usize);\n", indent, vecVar, elemType, lenVar))
		inner.WriteString(fmt.Sprintf("%s    for _ in 0..%s {\n", indent, lenVar))
		g.emitDecode(&inner, indent+"        ", "let "+itemVar, readerName, readerIsRef, v.ElementType, 0, true, tmpSuffix+"_e")
		inner.WriteString(fmt.Sprintf("%s        %s.push(%s);\n", indent, vecVar, itemVar))
		inner.WriteString(fmt.Sprintf("%s    }\n", indent))
		inner.WriteString(fmt.Sprintf("%s    %s\n", indent, vecVar))
		inner.WriteString(fmt.Sprintf("%s}", indent))
		sb.WriteString(rhs(inner.String()))
	case *ast.MapType:
		lenVar := "__len" + tmpSuffix
		mapVar := "__map" + tmpSuffix
		kVar := "__k" + tmpSuffix
		vVar := "__v" + tmpSuffix
		keyType := g.toRustType(v.KeyType)
		valType := g.toRustType(v.ValueType)

		var inner strings.Builder
		inner.WriteString("{\n")
		inner.WriteString(fmt.Sprintf("%s    let %s = %s.read_map_begin(%d, %s)?;\n", indent, lenVar, readerName, tag, requireLit))
		inner.WriteString(fmt.Sprintf("%s    let mut %s: HashMap<%s, %s> = HashMap::with_capacity(%s as usize);\n", indent, mapVar, keyType, valType, lenVar))
		inner.WriteString(fmt.Sprintf("%s    for _ in 0..%s {\n", indent, lenVar))
		g.emitDecode(&inner, indent+"        ", "let "+kVar, readerName, readerIsRef, v.KeyType, 0, true, tmpSuffix+"_k")
		g.emitDecode(&inner, indent+"        ", "let "+vVar, readerName, readerIsRef, v.ValueType, 1, true, tmpSuffix+"_v")
		inner.WriteString(fmt.Sprintf("%s        %s.insert(%s, %s);\n", indent, mapVar, kVar, vVar))
		inner.WriteString(fmt.Sprintf("%s    }\n", indent))
		inner.WriteString(fmt.Sprintf("%s    %s\n", indent, mapVar))
		inner.WriteString(fmt.Sprintf("%s}", indent))
		sb.WriteString(rhs(inner.String()))
	default:
		sb.WriteString(rhs(fmt.Sprintf("<%s as TarsDecode>::decode(%s, %d, %s)?", g.toRustType(t), readerRef, tag, requireLit)))
	}
}

// ----- Type mapping & naming helpers -----

func (g *Generator) toRustType(t ast.Type) string {
	if t == nil {
		return "()"
	}
	switch v := t.(type) {
	case *ast.BuiltinType:
		switch v.Kind {
		case ast.KindVoid:
			return "()"
		case ast.KindBool:
			return "bool"
		case ast.KindByte:
			if v.IsUnsigned {
				return "u8"
			}
			return "i8"
		case ast.KindShort:
			if v.IsUnsigned {
				return "u16"
			}
			return "i16"
		case ast.KindInt:
			if v.IsUnsigned {
				return "u32"
			}
			return "i32"
		case ast.KindLong:
			if v.IsUnsigned {
				return "u64"
			}
			return "i64"
		case ast.KindFloat:
			return "f32"
		case ast.KindDouble:
			return "f64"
		case ast.KindString:
			return "String"
		}
	case *ast.VectorType:
		if bt, ok := v.ElementType.(*ast.BuiltinType); ok && bt.Kind == ast.KindByte && !bt.IsUnsigned {
			return "Vec<u8>"
		}
		return fmt.Sprintf("Vec<%s>", g.toRustType(v.ElementType))
	case *ast.MapType:
		return fmt.Sprintf("HashMap<%s, %s>", g.toRustType(v.KeyType), g.toRustType(v.ValueType))
	case *ast.CustomType:
		return v.TypeName_
	}
	return "()"
}

func isVoid(t ast.Type) bool {
	if t == nil {
		return true
	}
	if bt, ok := t.(*ast.BuiltinType); ok && bt.Kind == ast.KindVoid {
		return true
	}
	return false
}

func (g *Generator) toRustFieldName(name string) string {
	return toSnakeCase(name)
}

func (g *Generator) toRustMethodName(name string) string {
	return toSnakeCase(name)
}

// toSnakeCase converts CamelCase / mixedCase to snake_case.
func toSnakeCase(name string) string {
	if name == "" {
		return ""
	}
	var b strings.Builder
	runes := []rune(name)
	for i, r := range runes {
		isUpper := r >= 'A' && r <= 'Z'
		if isUpper && i > 0 {
			prev := runes[i-1]
			next := rune(0)
			if i+1 < len(runes) {
				next = runes[i+1]
			}
			prevLower := prev >= 'a' && prev <= 'z'
			prevDigit := prev >= '0' && prev <= '9'
			nextLower := next >= 'a' && next <= 'z'
			// boundary either lowerCase->Upper or Upper->Upper-then-lower (XMLParser -> xml_parser)
			if prevLower || prevDigit || (next != 0 && nextLower && i > 0) {
				if prev != '_' {
					b.WriteRune('_')
				}
			}
		}
		if isUpper {
			b.WriteRune(r - 'A' + 'a')
		} else {
			b.WriteRune(r)
		}
	}
	return b.String()
}
