/**
 * Tencent is pleased to support the open source community by making Tars available.
 *
 * Copyright (C) 2016THL A29 Limited, a Tencent company. All rights reserved.
 *
 * Licensed under the BSD 3-Clause License (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * https://opensource.org/licenses/BSD-3-Clause
 */

// Package rust generates Rust code from Tars IDL
package rust

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/TarsCloud/TarsCpp/tools/tarsc-go/pkg/ast"
)

// Generator generates Rust code
type Generator struct {
	baseDir string
}

// NewGenerator creates a new Rust generator
func NewGenerator(baseDir string) *Generator {
	return &Generator{baseDir: baseDir}
}

// Generate generates Rust code for the document
func (g *Generator) Generate(doc *ast.Document, baseName string) error {
	for _, ns := range doc.Namespaces {
		if err := g.generateNamespace(doc, ns, baseName); err != nil {
			return err
		}
	}
	return nil
}

func (g *Generator) generateNamespace(doc *ast.Document, ns *ast.Namespace, baseName string) error {
	var sb strings.Builder

	// File header
	sb.WriteString("// Generated by tarsc - Tars IDL Compiler\n")
	sb.WriteString("// DO NOT EDIT!\n\n")

	sb.WriteString("#![allow(dead_code)]\n")
	sb.WriteString("#![allow(unused_imports)]\n\n")

	// Use statements
	sb.WriteString("use std::collections::HashMap;\n")
	sb.WriteString("use tars_stream::{TarsDecoder, TarsEncoder, TarsStruct};\n")
	sb.WriteString("use serde::{Deserialize, Serialize};\n\n")

	// Module definition
	sb.WriteString(fmt.Sprintf("pub mod %s {\n", strings.ToLower(ns.Name)))
	sb.WriteString("    use super::*;\n\n")

	// Generate consts
	for _, c := range ns.Consts {
		sb.WriteString(g.generateConst(c))
	}
	if len(ns.Consts) > 0 {
		sb.WriteString("\n")
	}

	// Generate enums
	for _, e := range ns.Enums {
		sb.WriteString(g.generateEnum(e))
		sb.WriteString("\n")
	}

	// Generate structs
	for _, s := range ns.Structs {
		sb.WriteString(g.generateStruct(s))
		sb.WriteString("\n")
	}

	// Generate traits (interfaces)
	for _, iface := range ns.Interfaces {
		sb.WriteString(g.generateTrait(iface))
		sb.WriteString("\n")
	}

	// Close module
	sb.WriteString("}\n")

	// Write file
	if err := os.MkdirAll(g.baseDir, 0755); err != nil {
		return err
	}

	filePath := filepath.Join(g.baseDir, baseName+".rs")
	return os.WriteFile(filePath, []byte(sb.String()), 0644)
}

func (g *Generator) generateConst(c *ast.Const) string {
	rustType := g.toRustType(c.Type)
	value := c.Value
	if bt, ok := c.Type.(*ast.BuiltinType); ok && bt.Kind == ast.KindString {
		value = "&str"
		return fmt.Sprintf("    pub const %s: %s = %s;\n", strings.ToUpper(c.Name), value, c.Value)
	}
	return fmt.Sprintf("    pub const %s: %s = %s;\n", strings.ToUpper(c.Name), rustType, value)
}

func (g *Generator) generateEnum(e *ast.Enum) string {
	var sb strings.Builder

	sb.WriteString("    #[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]\n")
	sb.WriteString("    #[repr(i32)]\n")
	sb.WriteString(fmt.Sprintf("    pub enum %s {\n", e.Name))
	for _, m := range e.Members {
		sb.WriteString(fmt.Sprintf("        %s = %d,\n", m.Name, m.Value))
	}
	sb.WriteString("    }\n\n")

	// Default implementation
	if len(e.Members) > 0 {
		sb.WriteString(fmt.Sprintf("    impl Default for %s {\n", e.Name))
		sb.WriteString("        fn default() -> Self {\n")
		sb.WriteString(fmt.Sprintf("            %s::%s\n", e.Name, e.Members[0].Name))
		sb.WriteString("        }\n")
		sb.WriteString("    }\n\n")
	}

	// From<i32> implementation
	sb.WriteString(fmt.Sprintf("    impl From<i32> for %s {\n", e.Name))
	sb.WriteString("        fn from(value: i32) -> Self {\n")
	sb.WriteString("            match value {\n")
	for _, m := range e.Members {
		sb.WriteString(fmt.Sprintf("                %d => %s::%s,\n", m.Value, e.Name, m.Name))
	}
	if len(e.Members) > 0 {
		sb.WriteString(fmt.Sprintf("                _ => %s::%s,\n", e.Name, e.Members[0].Name))
	}
	sb.WriteString("            }\n")
	sb.WriteString("        }\n")
	sb.WriteString("    }\n")

	return sb.String()
}

func (g *Generator) generateStruct(s *ast.Struct) string {
	var sb strings.Builder

	sb.WriteString("    #[derive(Debug, Clone, Default, Serialize, Deserialize)]\n")
	sb.WriteString(fmt.Sprintf("    pub struct %s {\n", s.Name))

	for _, f := range s.Fields {
		rustType := g.toRustType(f.Type)
		if !f.IsRequired {
			rustType = fmt.Sprintf("Option<%s>", rustType)
		}
		sb.WriteString(fmt.Sprintf("        pub %s: %s,\n", g.toRustFieldName(f.Name), rustType))
	}
	sb.WriteString("    }\n\n")

	// TarsStruct implementation
	sb.WriteString(fmt.Sprintf("    impl TarsStruct for %s {\n", s.Name))

	// encode method
	sb.WriteString("        fn encode<W: std::io::Write>(&self, encoder: &mut TarsEncoder<W>) -> std::io::Result<()> {\n")
	for _, f := range s.Fields {
		fieldName := g.toRustFieldName(f.Name)
		if f.IsRequired {
			sb.WriteString(fmt.Sprintf("            encoder.write(%d, &self.%s)?;\n", f.Tag, fieldName))
		} else {
			sb.WriteString(fmt.Sprintf("            if let Some(ref v) = self.%s {\n", fieldName))
			sb.WriteString(fmt.Sprintf("                encoder.write(%d, v)?;\n", f.Tag))
			sb.WriteString("            }\n")
		}
	}
	sb.WriteString("            Ok(())\n")
	sb.WriteString("        }\n\n")

	// decode method
	sb.WriteString("        fn decode<R: std::io::Read>(decoder: &mut TarsDecoder<R>) -> std::io::Result<Self> {\n")
	sb.WriteString("            let mut result = Self::default();\n")
	for _, f := range s.Fields {
		fieldName := g.toRustFieldName(f.Name)
		if f.IsRequired {
			sb.WriteString(fmt.Sprintf("            result.%s = decoder.read(%d, true)?;\n", fieldName, f.Tag))
		} else {
			sb.WriteString(fmt.Sprintf("            result.%s = decoder.read_optional(%d)?;\n", fieldName, f.Tag))
		}
	}
	sb.WriteString("            Ok(result)\n")
	sb.WriteString("        }\n")
	sb.WriteString("    }\n")

	return sb.String()
}

func (g *Generator) generateTrait(iface *ast.Interface) string {
	var sb strings.Builder

	// Trait definition
	sb.WriteString(fmt.Sprintf("    pub trait %s {\n", iface.Name))

	for _, op := range iface.Operations {
		sb.WriteString(g.generateTraitMethod(op))
	}

	sb.WriteString("    }\n\n")

	// Proxy struct
	sb.WriteString(fmt.Sprintf("    pub struct %sProxy {\n", iface.Name))
	sb.WriteString("        // TODO: Add proxy fields\n")
	sb.WriteString("    }\n\n")

	// Proxy implementation
	sb.WriteString(fmt.Sprintf("    impl %s for %sProxy {\n", iface.Name, iface.Name))

	for _, op := range iface.Operations {
		sb.WriteString(g.generateProxyMethod(op))
		sb.WriteString("\n")
	}

	sb.WriteString("    }\n")

	return sb.String()
}

func (g *Generator) generateTraitMethod(op *ast.Operation) string {
	var sb strings.Builder

	returnType := g.toRustType(op.ReturnType)
	if returnType == "()" {
		returnType = "Result<(), Box<dyn std::error::Error>>"
	} else {
		returnType = fmt.Sprintf("Result<%s, Box<dyn std::error::Error>>", returnType)
	}

	var params []string
	params = append(params, "&mut self")
	for _, p := range op.Params {
		rustType := g.toRustType(p.Type)
		if p.IsOut {
			params = append(params, fmt.Sprintf("%s: &mut %s", g.toRustFieldName(p.Name), rustType))
		} else {
			params = append(params, fmt.Sprintf("%s: &%s", g.toRustFieldName(p.Name), rustType))
		}
	}

	sb.WriteString(fmt.Sprintf("        fn %s(%s) -> %s;\n", g.toRustMethodName(op.Name), strings.Join(params, ", "), returnType))

	return sb.String()
}

func (g *Generator) generateProxyMethod(op *ast.Operation) string {
	var sb strings.Builder

	returnType := g.toRustType(op.ReturnType)
	if returnType == "()" {
		returnType = "Result<(), Box<dyn std::error::Error>>"
	} else {
		returnType = fmt.Sprintf("Result<%s, Box<dyn std::error::Error>>", returnType)
	}

	var params []string
	params = append(params, "&mut self")
	for _, p := range op.Params {
		rustType := g.toRustType(p.Type)
		if p.IsOut {
			params = append(params, fmt.Sprintf("%s: &mut %s", g.toRustFieldName(p.Name), rustType))
		} else {
			params = append(params, fmt.Sprintf("%s: &%s", g.toRustFieldName(p.Name), rustType))
		}
	}

	sb.WriteString(fmt.Sprintf("        fn %s(%s) -> %s {\n", g.toRustMethodName(op.Name), strings.Join(params, ", "), returnType))
	sb.WriteString("            // TODO: Implement proxy call\n")
	sb.WriteString("            unimplemented!()\n")
	sb.WriteString("        }\n")

	return sb.String()
}

func (g *Generator) toRustType(t ast.Type) string {
	if t == nil {
		return "()"
	}

	switch v := t.(type) {
	case *ast.BuiltinType:
		switch v.Kind {
		case ast.KindVoid:
			return "()"
		case ast.KindBool:
			return "bool"
		case ast.KindByte:
			if v.IsUnsigned {
				return "u8"
			}
			return "i8"
		case ast.KindShort:
			if v.IsUnsigned {
				return "u16"
			}
			return "i16"
		case ast.KindInt:
			if v.IsUnsigned {
				return "u32"
			}
			return "i32"
		case ast.KindLong:
			if v.IsUnsigned {
				return "u64"
			}
			return "i64"
		case ast.KindFloat:
			return "f32"
		case ast.KindDouble:
			return "f64"
		case ast.KindString:
			return "String"
		}
	case *ast.VectorType:
		if bt, ok := v.ElementType.(*ast.BuiltinType); ok && bt.Kind == ast.KindByte {
			return "Vec<u8>"
		}
		return fmt.Sprintf("Vec<%s>", g.toRustType(v.ElementType))
	case *ast.MapType:
		return fmt.Sprintf("HashMap<%s, %s>", g.toRustType(v.KeyType), g.toRustType(v.ValueType))
	case *ast.CustomType:
		return v.TypeName_
	}
	return "()"
}

func (g *Generator) toRustFieldName(name string) string {
	// Convert camelCase to snake_case
	var result strings.Builder
	for i, r := range name {
		if i > 0 && r >= 'A' && r <= 'Z' {
			result.WriteRune('_')
		}
		result.WriteRune(r)
	}
	return strings.ToLower(result.String())
}

func (g *Generator) toRustMethodName(name string) string {
	return g.toRustFieldName(name)
}
