/**
 * Tencent is pleased to support the open source community by making Tars available.
 *
 * Copyright (C) 2016THL A29 Limited, a Tencent company. All rights reserved.
 *
 * Licensed under the BSD 3-Clause License (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * https://opensource.org/licenses/BSD-3-Clause
 */

// Package cpp generates C++ code from Tars IDL
package cpp

import (
	"crypto/md5"
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/TarsCloud/TarsCpp/tools/tarsc-go/pkg/ast"
)

const tarsVersion = "3.0.22"

// Generator generates C++ code
type Generator struct {
	baseDir string
}

// NewGenerator creates a new C++ generator
func NewGenerator(baseDir string) *Generator {
	return &Generator{baseDir: baseDir}
}

// Generate generates C++ code for the document
func (g *Generator) Generate(doc *ast.Document, baseName string) error {
	for _, ns := range doc.Namespaces {
		if err := g.generateNamespace(doc, ns, baseName); err != nil {
			return err
		}
	}
	return nil
}

func (g *Generator) generateNamespace(doc *ast.Document, ns *ast.Namespace, baseName string) error {
	var sb strings.Builder

	// File header comment
	sb.WriteString("// **********************************************************************\n")
	sb.WriteString("// This file was generated by a TARS parser!\n")
	sb.WriteString(fmt.Sprintf("// TARS version %s.\n", tarsVersion))
	sb.WriteString("// **********************************************************************\n\n")

	// Header guard with double underscore prefix
	guardName := "__" + strings.ToUpper(baseName) + "_H_"
	sb.WriteString(fmt.Sprintf("#ifndef %s\n", guardName))
	sb.WriteString(fmt.Sprintf("#define %s\n\n", guardName))

	// Includes in the same order as C++ version
	sb.WriteString("#include <map>\n")
	sb.WriteString("#include <string>\n")
	sb.WriteString("#include <vector>\n")
	sb.WriteString("#include \"tup/Tars.h\"\n")
	sb.WriteString("#include \"tup/TarsJson.h\"\n")
	sb.WriteString("using namespace std;\n")

	// Include dependencies
	for _, inc := range doc.Includes {
		incName := strings.TrimSuffix(filepath.Base(inc), filepath.Ext(inc))
		sb.WriteString(fmt.Sprintf("#include \"%s.h\"\n", incName))
	}
	sb.WriteString("\n")

	// Namespace
	sb.WriteString(fmt.Sprintf("\nnamespace %s\n{\n", ns.Name))

	// Generate consts first (before enums)
	for _, c := range ns.Consts {
		sb.WriteString(g.generateConst(c))
		sb.WriteString("\n")
	}

	// Generate enums with etos and stoe helper functions
	for _, e := range ns.Enums {
		sb.WriteString(g.generateEnum(e))
		sb.WriteString("\n")
	}

	// Generate structs (no forward declarations)
	for i, s := range ns.Structs {
		if i > 0 {
			sb.WriteString("\n")
		}
		sb.WriteString(g.generateStruct(s, ns.Name))
	}

	// Generate interfaces
	for _, iface := range ns.Interfaces {
		sb.WriteString(g.generateInterface(iface, ns.Name))
		sb.WriteString("\n")
	}

	// Close namespace with trailing newlines to match C++ version
	sb.WriteString("\n\n}\n\n\n\n")

	// End header guard
	sb.WriteString("#endif\n")

	// Write file
	if err := os.MkdirAll(g.baseDir, 0755); err != nil {
		return err
	}

	filePath := filepath.Join(g.baseDir, baseName+".h")
	return os.WriteFile(filePath, []byte(sb.String()), 0644)
}

func (g *Generator) generateEnum(e *ast.Enum) string {
	var sb strings.Builder

	// Enum definition with trailing comma on all values
	sb.WriteString(fmt.Sprintf("    enum %s\n    {\n", e.Name))
	for _, m := range e.Members {
		sb.WriteString(fmt.Sprintf("        %s = %d,\n", m.Name, m.Value))
	}
	sb.WriteString("    };\n")

	// etos (enum to string) function
	sb.WriteString(fmt.Sprintf("    inline string etos(const %s & e)\n", e.Name))
	sb.WriteString("    {\n")
	sb.WriteString("        switch(e)\n")
	sb.WriteString("        {\n")
	for _, m := range e.Members {
		sb.WriteString(fmt.Sprintf("            case %s: return \"%s\";\n", m.Name, m.Name))
	}
	sb.WriteString("            default: return \"\";\n")
	sb.WriteString("        }\n")
	sb.WriteString("    }\n")

	// stoe (string to enum) function
	sb.WriteString(fmt.Sprintf("    inline int stoe(const string & s, %s & e)\n", e.Name))
	sb.WriteString("    {\n")
	for _, m := range e.Members {
		sb.WriteString(fmt.Sprintf("        if(s == \"%s\")  { e=%s; return 0;}\n", m.Name, m.Name))
	}
	sb.WriteString("\n        return -1;\n")
	sb.WriteString("    }\n")

	return sb.String()
}

func (g *Generator) generateConst(c *ast.Const) string {
	cppType := g.toCppType(c.Type)
	return fmt.Sprintf("    const %s %s = %s;\n", cppType, c.Name, c.Value)
}

func (g *Generator) generateStruct(s *ast.Struct, nsName string) string {
	var sb strings.Builder

	// Calculate MD5 for the struct (same algorithm as C++ version)
	md5Hash := g.calculateStructMD5(s, nsName)

	sb.WriteString(fmt.Sprintf("    struct %s : public tars::TarsStructBase\n", s.Name))
	sb.WriteString("    {\n")
	sb.WriteString("    public:\n")

	// className static method
	sb.WriteString("        static string className()\n")
	sb.WriteString("        {\n")
	sb.WriteString(fmt.Sprintf("            return \"%s.%s\";\n", nsName, s.Name))
	sb.WriteString("        }\n")

	// MD5 static method
	sb.WriteString("        static string MD5()\n")
	sb.WriteString("        {\n")
	sb.WriteString(fmt.Sprintf("            return \"%s\";\n", md5Hash))
	sb.WriteString("        }\n")

	// Constructor
	sb.WriteString(fmt.Sprintf("        %s()\n", s.Name))
	sb.WriteString("        {\n")
	sb.WriteString("            resetDefautlt();\n")
	sb.WriteString("        }\n")

	// resetDefault method
	sb.WriteString("        void resetDefautlt()\n")
	sb.WriteString("        {\n")
	for _, f := range s.Fields {
		defaultVal := g.getCppDefault(f)
		if defaultVal != "" {
			sb.WriteString(fmt.Sprintf("            %s = %s;\n", f.Name, defaultVal))
		} else {
			// For custom types, call resetDefautlt()
			// For vectors and maps, call clear()
			switch f.Type.(type) {
			case *ast.CustomType:
				sb.WriteString(fmt.Sprintf("            %s.resetDefautlt();\n", f.Name))
			case *ast.VectorType, *ast.MapType:
				sb.WriteString(fmt.Sprintf("            %s.clear();\n", f.Name))
			}
		}
	}
	sb.WriteString("        }\n")

	// writeTo method with optional field optimization (matching C++ version behavior)
	sb.WriteString("        template<typename WriterT>\n")
	sb.WriteString("        void writeTo(tars::TarsOutputStream<WriterT>& _os) const\n")
	sb.WriteString("        {\n")
	for _, f := range s.Fields {
		if f.IsRequired {
			sb.WriteString(fmt.Sprintf("            _os.write(%s, %d);\n", f.Name, f.Tag))
		} else {
			// For optional fields, check if value differs from default (like C++ version)
			switch ft := f.Type.(type) {
			case *ast.BuiltinType:
				switch ft.Kind {
				case ast.KindBool:
					sb.WriteString(fmt.Sprintf("            if (%s != false)\n", f.Name))
					sb.WriteString("            {\n")
					sb.WriteString(fmt.Sprintf("                _os.write(%s, %d);\n", f.Name, f.Tag))
					sb.WriteString("            }\n")
				case ast.KindByte, ast.KindShort, ast.KindInt, ast.KindLong:
					sb.WriteString(fmt.Sprintf("            if (%s != 0)\n", f.Name))
					sb.WriteString("            {\n")
					sb.WriteString(fmt.Sprintf("                _os.write(%s, %d);\n", f.Name, f.Tag))
					sb.WriteString("            }\n")
				case ast.KindFloat, ast.KindDouble:
					sb.WriteString(fmt.Sprintf("            if (!tars::TC_Common::equal(%s, (double)0))\n", f.Name))
					sb.WriteString("            {\n")
					sb.WriteString(fmt.Sprintf("                _os.write(%s, %d);\n", f.Name, f.Tag))
					sb.WriteString("            }\n")
				case ast.KindString:
					sb.WriteString(fmt.Sprintf("            if (%s != \"\")\n", f.Name))
					sb.WriteString("            {\n")
					sb.WriteString(fmt.Sprintf("                _os.write(%s, %d);\n", f.Name, f.Tag))
					sb.WriteString("            }\n")
				default:
					sb.WriteString(fmt.Sprintf("            _os.write(%s, %d);\n", f.Name, f.Tag))
				}
			case *ast.VectorType, *ast.MapType:
				// For vectors and maps, check if empty
				sb.WriteString(fmt.Sprintf("            if (!%s.empty())\n", f.Name))
				sb.WriteString("            {\n")
				sb.WriteString(fmt.Sprintf("                _os.write(%s, %d);\n", f.Name, f.Tag))
				sb.WriteString("            }\n")
			default:
				// For custom types - just write
				sb.WriteString(fmt.Sprintf("            _os.write(%s, %d);\n", f.Name, f.Tag))
			}
		}
	}
	sb.WriteString("        }\n")

	// readFrom method
	sb.WriteString("        template<typename ReaderT>\n")
	sb.WriteString("        void readFrom(tars::TarsInputStream<ReaderT>& _is)\n")
	sb.WriteString("        {\n")
	sb.WriteString("            resetDefautlt();\n")
	for _, f := range s.Fields {
		required := "true"
		if !f.IsRequired {
			required = "false"
		}
		sb.WriteString(fmt.Sprintf("            _is.read(%s, %d, %s);\n", f.Name, f.Tag, required))
	}
	sb.WriteString("        }\n")

	// writeToJson method
	sb.WriteString("        tars::JsonValueObjPtr writeToJson() const\n")
	sb.WriteString("        {\n")
	sb.WriteString("            tars::JsonValueObjPtr p = new tars::JsonValueObj();\n")
	for _, f := range s.Fields {
		sb.WriteString(fmt.Sprintf("            p->value[\"%s\"] = tars::JsonOutput::writeJson(%s);\n", f.Name, f.Name))
	}
	sb.WriteString("            return p;\n")
	sb.WriteString("        }\n")

	// writeToJsonString method
	sb.WriteString("        string writeToJsonString() const\n")
	sb.WriteString("        {\n")
	sb.WriteString("            return tars::TC_Json::writeValue(writeToJson());\n")
	sb.WriteString("        }\n")

	// readFromJson method
	sb.WriteString("        void readFromJson(const tars::JsonValuePtr & p, bool isRequire = true)\n")
	sb.WriteString("        {\n")
	sb.WriteString("            resetDefautlt();\n")
	sb.WriteString("            if(NULL == p.get() || p->getType() != tars::eJsonTypeObj)\n")
	sb.WriteString("            {\n")
	sb.WriteString("                char s[128];\n")
	sb.WriteString("                snprintf(s, sizeof(s), \"read 'struct' type mismatch, get type: %d.\", (p.get() ? p->getType() : 0));\n")
	sb.WriteString("                throw tars::TC_Json_Exception(s);\n")
	sb.WriteString("            }\n")
	sb.WriteString("            tars::JsonValueObjPtr pObj=tars::JsonValueObjPtr::dynamicCast(p);\n")
	for _, f := range s.Fields {
		required := "true"
		if !f.IsRequired {
			required = "false"
		}
		sb.WriteString(fmt.Sprintf("            tars::JsonInput::readJson(%s,pObj->value[\"%s\"], %s);\n", f.Name, f.Name, required))
	}
	sb.WriteString("        }\n")

	// readFromJsonString method
	sb.WriteString("        void readFromJsonString(const string & str)\n")
	sb.WriteString("        {\n")
	sb.WriteString("            readFromJson(tars::TC_Json::getValue(str));\n")
	sb.WriteString("        }\n")

	// display method
	sb.WriteString("        ostream& display(ostream& _os, int _level=0) const\n")
	sb.WriteString("        {\n")
	sb.WriteString("            tars::TarsDisplayer _ds(_os, _level);\n")
	for _, f := range s.Fields {
		sb.WriteString(fmt.Sprintf("            _ds.display(%s,\"%s\");\n", f.Name, f.Name))
	}
	sb.WriteString("            return _os;\n")
	sb.WriteString("        }\n")

	// displaySimple method
	sb.WriteString("        ostream& displaySimple(ostream& _os, int _level=0) const\n")
	sb.WriteString("        {\n")
	sb.WriteString("            tars::TarsDisplayer _ds(_os, _level);\n")
	for i, f := range s.Fields {
		sep := "true"
		if i == len(s.Fields)-1 {
			sep = "false"
		}
		sb.WriteString(fmt.Sprintf("            _ds.displaySimple(%s, %s);\n", f.Name, sep))
	}
	sb.WriteString("            return _os;\n")
	sb.WriteString("        }\n")

	// Fields in public section at the end
	sb.WriteString("    public:\n")
	for _, f := range s.Fields {
		cppType := g.toCppTypeWithNs(f.Type, nsName)
		sb.WriteString(fmt.Sprintf("        %s %s;\n", cppType, f.Name))
	}

	sb.WriteString("    };\n")

	// Comparison operators
	sb.WriteString(fmt.Sprintf("    inline bool operator==(const %s&l, const %s&r)\n", s.Name, s.Name))
	sb.WriteString("    {\n")
	sb.WriteString("        return ")
	for i, f := range s.Fields {
		if i > 0 {
			sb.WriteString(" && ")
		}
		// For float/double types, use tars::TC_Common::equal()
		if bt, ok := f.Type.(*ast.BuiltinType); ok && (bt.Kind == ast.KindFloat || bt.Kind == ast.KindDouble) {
			sb.WriteString(fmt.Sprintf("tars::TC_Common::equal(l.%s,r.%s)", f.Name, f.Name))
		} else {
			sb.WriteString(fmt.Sprintf("l.%s == r.%s", f.Name, f.Name))
		}
	}
	sb.WriteString(";\n    }\n")

	sb.WriteString(fmt.Sprintf("    inline bool operator!=(const %s&l, const %s&r)\n", s.Name, s.Name))
	sb.WriteString("    {\n")
	sb.WriteString("        return !(l == r);\n")
	sb.WriteString("    }\n")

	// ostream operator
	sb.WriteString(fmt.Sprintf("    inline ostream& operator<<(ostream & os,const %s&r)\n", s.Name))
	sb.WriteString("    {\n")
	sb.WriteString("        os << r.writeToJsonString();\n")
	sb.WriteString("        return os;\n")
	sb.WriteString("    }\n")

	// istream operator
	sb.WriteString(fmt.Sprintf("    inline istream& operator>>(istream& is,%s&l)\n", s.Name))
	sb.WriteString("    {\n")
	sb.WriteString("        std::istreambuf_iterator<char> eos;\n")
	sb.WriteString("        std::string s(std::istreambuf_iterator<char>(is), eos);\n")
	sb.WriteString("        l.readFromJsonString(s);\n")
	sb.WriteString("        return is;\n")
	sb.WriteString("    }\n")

	return sb.String()
}

func (g *Generator) calculateStructMD5(s *ast.Struct, nsName string) string {
	// Create a string representation of the struct for MD5 (matching C++ version's algorithm)
	// C++ version: "_" + type + "_" + type + ...
	// Custom types need namespace prefix (e.g., News::ProcessTimeStamp)
	var sb strings.Builder
	for _, f := range s.Fields {
		cppType := g.toCppTypeWithNs(f.Type, nsName)
		sb.WriteString("_")
		sb.WriteString(cppType)
	}
	hash := md5.Sum([]byte(sb.String()))
	return fmt.Sprintf("%x", hash)
}

func (g *Generator) generateInterface(iface *ast.Interface, nsName string) string {
	var sb strings.Builder

	// Proxy class
	sb.WriteString(fmt.Sprintf("    class %sPrx : public tars::ServantProxy\n", iface.Name))
	sb.WriteString("    {\n")
	sb.WriteString("    public:\n")
	sb.WriteString(fmt.Sprintf("        typedef std::shared_ptr<%sPrx> ptr;\n\n", iface.Name))

	// Methods
	for _, op := range iface.Operations {
		sb.WriteString(g.generateProxyMethod(op))
		sb.WriteString("\n")
	}

	sb.WriteString(fmt.Sprintf("        %sPrx* tars_hash(int64_t key)\n", iface.Name))
	sb.WriteString("        {\n")
	sb.WriteString(fmt.Sprintf("            return (%sPrx*)ServantProxy::tars_hash(key);\n", iface.Name))
	sb.WriteString("        }\n")

	sb.WriteString("    };\n\n")

	// Servant class
	sb.WriteString(fmt.Sprintf("    class %s : public tars::Servant\n", iface.Name))
	sb.WriteString("    {\n")
	sb.WriteString("    public:\n")
	sb.WriteString(fmt.Sprintf("        virtual ~%s() {}\n\n", iface.Name))

	for _, op := range iface.Operations {
		sb.WriteString(g.generateServantMethod(op))
		sb.WriteString("\n")
	}

	sb.WriteString("    };\n")

	return sb.String()
}

func (g *Generator) generateProxyMethod(op *ast.Operation) string {
	var sb strings.Builder

	returnType := g.toCppType(op.ReturnType)
	if returnType == "" {
		returnType = "void"
	}

	var params []string
	for _, p := range op.Params {
		cppType := g.toCppType(p.Type)
		if p.IsOut {
			params = append(params, fmt.Sprintf("%s& %s", cppType, p.Name))
		} else {
			params = append(params, fmt.Sprintf("const %s& %s", cppType, p.Name))
		}
	}
	params = append(params, "const map<string, string>& context = TARS_CONTEXT()")

	sb.WriteString(fmt.Sprintf("        %s %s(%s)\n", returnType, op.Name, strings.Join(params, ", ")))
	sb.WriteString("        {\n")
	sb.WriteString("            // TODO: Implement proxy call\n")
	if returnType != "void" {
		sb.WriteString(fmt.Sprintf("            return %s;\n", g.getTypeDefault(op.ReturnType)))
	}
	sb.WriteString("        }\n")

	return sb.String()
}

func (g *Generator) generateServantMethod(op *ast.Operation) string {
	var sb strings.Builder

	returnType := g.toCppType(op.ReturnType)
	if returnType == "" {
		returnType = "void"
	}

	var params []string
	for _, p := range op.Params {
		cppType := g.toCppType(p.Type)
		if p.IsOut {
			params = append(params, fmt.Sprintf("%s& %s", cppType, p.Name))
		} else {
			params = append(params, fmt.Sprintf("const %s& %s", cppType, p.Name))
		}
	}
	params = append(params, "tars::TarsCurrentPtr current")

	sb.WriteString(fmt.Sprintf("        virtual %s %s(%s) = 0;\n", returnType, op.Name, strings.Join(params, ", ")))

	return sb.String()
}

func (g *Generator) toCppType(t ast.Type) string {
	return g.toCppTypeWithNs(t, "")
}

func (g *Generator) toCppTypeWithNs(t ast.Type, nsName string) string {
	if t == nil {
		return "void"
	}

	switch v := t.(type) {
	case *ast.BuiltinType:
		switch v.Kind {
		case ast.KindVoid:
			return "void"
		case ast.KindBool:
			return "tars::Bool"
		case ast.KindByte:
			// Byte is always Char (unsigned byte gets promoted to Short by parser)
			return "tars::Char"
		case ast.KindShort:
			// unsigned byte in tars is promoted to Short(unsigned) by parser
			// C++ maps it back to UInt8
			if v.IsUnsigned {
				return "tars::UInt8"
			}
			return "tars::Short"
		case ast.KindInt:
			// unsigned short in tars is promoted to Int(unsigned) by parser
			// C++ maps it back to UInt16
			if v.IsUnsigned {
				return "tars::UInt16"
			}
			return "tars::Int32"
		case ast.KindLong:
			// unsigned int in tars is promoted to Long(unsigned) by parser
			// C++ maps it back to UInt32
			if v.IsUnsigned {
				return "tars::UInt32"
			}
			return "tars::Int64"
		case ast.KindFloat:
			return "tars::Float"
		case ast.KindDouble:
			return "tars::Double"
		case ast.KindString:
			return "std::string"
		}
	case *ast.VectorType:
		if bt, ok := v.ElementType.(*ast.BuiltinType); ok && bt.Kind == ast.KindByte {
			return "vector<tars::Char>"
		}
		return fmt.Sprintf("vector<%s>", g.toCppTypeWithNs(v.ElementType, nsName))
	case *ast.MapType:
		return fmt.Sprintf("map<%s, %s>", g.toCppTypeWithNs(v.KeyType, nsName), g.toCppTypeWithNs(v.ValueType, nsName))
	case *ast.CustomType:
		if nsName != "" {
			return nsName + "::" + v.Name
		}
		return v.Name
	}
	return "void"
}

func (g *Generator) getCppDefault(f *ast.Field) string {
	if f.HasDefault && f.DefaultValue != "" {
		return f.DefaultValue
	}
	return g.getTypeDefault(f.Type)
}

func (g *Generator) getTypeDefault(t ast.Type) string {
	if t == nil {
		return ""
	}

	switch v := t.(type) {
	case *ast.BuiltinType:
		switch v.Kind {
		case ast.KindBool:
			return "false"
		case ast.KindString:
			return "\"\""
		case ast.KindByte, ast.KindShort, ast.KindInt, ast.KindLong, ast.KindFloat, ast.KindDouble:
			return "0"
		}
	case *ast.VectorType, *ast.MapType:
		return ""
	case *ast.CustomType:
		return ""
	}
	return ""
}
