/**
 * Tencent is pleased to support the open source community by making Tars available.
 *
 * Copyright (C) 2016THL A29 Limited, a Tencent company. All rights reserved.
 *
 * Licensed under the BSD 3-Clause License (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * https://opensource.org/licenses/BSD-3-Clause
 */

// Package csharp generates C# code from Tars IDL
package csharp

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/TarsCloud/TarsCpp/tools/tarsc-go/pkg/ast"
)

// Generator generates C# code
type Generator struct {
	baseDir string
}

// NewGenerator creates a new C# generator
func NewGenerator(baseDir string) *Generator {
	return &Generator{baseDir: baseDir}
}

// Generate generates C# code for the document
func (g *Generator) Generate(doc *ast.Document, baseName string) error {
	for _, ns := range doc.Namespaces {
		if err := g.generateNamespace(doc, ns, baseName); err != nil {
			return err
		}
	}
	return nil
}

func (g *Generator) generateNamespace(doc *ast.Document, ns *ast.Namespace, baseName string) error {
	// Create output directory
	nsDir := filepath.Join(g.baseDir, ns.Name)
	if err := os.MkdirAll(nsDir, 0755); err != nil {
		return err
	}

	// Generate main file (data structures, enums, constants)
	if err := g.generateMainFile(ns, nsDir, baseName); err != nil {
		return err
	}

	// Generate TarsCodec.cs (serialization base classes)
	if err := g.generateCodecFile(ns, nsDir); err != nil {
		return err
	}

	// Generate Prx and Servant files for each interface
	for _, iface := range ns.Interfaces {
		if err := g.generatePrxFile(ns, iface, nsDir); err != nil {
			return err
		}
		if err := g.generateServantFile(ns, iface, nsDir); err != nil {
			return err
		}
	}

	return nil
}

func (g *Generator) generateMainFile(ns *ast.Namespace, nsDir string, baseName string) error {
	var sb strings.Builder

	// File header
	sb.WriteString("// Generated by tarsc - Tars IDL Compiler\n")
	sb.WriteString("// DO NOT EDIT!\n\n")

	// Using statements
	sb.WriteString("using System;\n")
	sb.WriteString("using System.Collections.Generic;\n\n")

	// Namespace
	sb.WriteString(fmt.Sprintf("namespace %s\n{\n", ns.Name))

	// Generate constants
	if len(ns.Consts) > 0 {
		sb.WriteString(g.generateConst(ns.Consts, baseName))
		sb.WriteString("\n")
	}

	// Generate enums
	for _, e := range ns.Enums {
		sb.WriteString(g.generateEnum(e))
		sb.WriteString("\n")
	}

	// Generate structs with serialization
	for _, s := range ns.Structs {
		sb.WriteString(g.generateStruct(s, ns))
		sb.WriteString("\n")
	}

	// Generate interfaces (pure interface definitions only)
	for _, iface := range ns.Interfaces {
		sb.WriteString(g.generateInterface(iface))
		sb.WriteString("\n")
	}

	// Close namespace
	sb.WriteString("}\n")

	// Write file
	filePath := filepath.Join(nsDir, baseName+".cs")
	return os.WriteFile(filePath, []byte(sb.String()), 0644)
}

func (g *Generator) generateConst(consts []*ast.Const, baseName string) string {
	var sb strings.Builder

	// Use PascalCase for class name
	className := g.toPascalCase(baseName) + "Const"

	sb.WriteString(fmt.Sprintf("    /// <summary>\n"))
	sb.WriteString(fmt.Sprintf("    /// Constants defined in %s\n", baseName))
	sb.WriteString(fmt.Sprintf("    /// </summary>\n"))
	sb.WriteString(fmt.Sprintf("    public static class %s\n    {\n", className))

	for _, c := range consts {
		csType := g.toCSharpType(c.Type)
		value := c.Value
		// Handle string values
		if bt, ok := c.Type.(*ast.BuiltinType); ok && bt.Kind == ast.KindString {
			if !strings.HasPrefix(value, "\"") {
				value = fmt.Sprintf("\"%s\"", value)
			}
		}
		sb.WriteString(fmt.Sprintf("        public const %s %s = %s;\n", csType, c.Name, value))
	}

	sb.WriteString("    }\n")

	return sb.String()
}

func (g *Generator) generateEnum(e *ast.Enum) string {
	var sb strings.Builder

	sb.WriteString(fmt.Sprintf("    public enum %s\n    {\n", e.Name))
	for _, m := range e.Members {
		sb.WriteString(fmt.Sprintf("        %s = %d,\n", m.Name, m.Value))
	}
	sb.WriteString("    }\n")

	return sb.String()
}

func (g *Generator) generateStruct(s *ast.Struct, ns *ast.Namespace) string {
	var sb strings.Builder

	sb.WriteString(fmt.Sprintf("    [TarsStruct]\n"))
	sb.WriteString(fmt.Sprintf("    public class %s\n    {\n", s.Name))

	// Fields
	for _, f := range s.Fields {
		csType := g.toCSharpType(f.Type)
		required := "false"
		if f.IsRequired {
			required = "true"
		}
		sb.WriteString(fmt.Sprintf("        [TarsStructProperty(%d, IsRequire = %s)]\n", f.Tag, required))
		sb.WriteString(fmt.Sprintf("        public %s %s { get; set; }", csType, g.toCSharpFieldName(f.Name)))
		if f.HasDefault {
			sb.WriteString(fmt.Sprintf(" = %s;", g.getCSharpDefault(f, ns)))
		} else {
			defaultVal := g.getTypeDefault(f.Type)
			if defaultVal != "" {
				sb.WriteString(fmt.Sprintf(" = %s;", defaultVal))
			} else {
				sb.WriteString(";")
			}
		}
		sb.WriteString("\n\n")
	}

	// Generate WriteTo method
	sb.WriteString(g.generateWriteToMethod(s, ns))
	sb.WriteString("\n")

	// Generate ReadFrom method
	sb.WriteString(g.generateReadFromMethod(s, ns))

	sb.WriteString("    }\n")

	return sb.String()
}

func (g *Generator) generateWriteToMethod(s *ast.Struct, ns *ast.Namespace) string {
	var sb strings.Builder

	sb.WriteString("        /// <summary>\n")
	sb.WriteString("        /// Serialize this object to TarsOutputStream\n")
	sb.WriteString("        /// </summary>\n")
	sb.WriteString("        public void WriteTo(TarsOutputStream os)\n")
	sb.WriteString("        {\n")

	for _, f := range s.Fields {
		fieldName := g.toCSharpFieldName(f.Name)
		if g.isStructType(f.Type, ns) {
			sb.WriteString(fmt.Sprintf("            os.WriteStruct(%s, %d);\n", fieldName, f.Tag))
		} else if g.isEnumType(f.Type, ns) {
			sb.WriteString(fmt.Sprintf("            os.Write((int)%s, %d);\n", fieldName, f.Tag))
		} else {
			sb.WriteString(fmt.Sprintf("            os.Write(%s, %d);\n", fieldName, f.Tag))
		}
	}

	sb.WriteString("        }\n")

	return sb.String()
}

func (g *Generator) generateReadFromMethod(s *ast.Struct, ns *ast.Namespace) string {
	var sb strings.Builder

	sb.WriteString("        /// <summary>\n")
	sb.WriteString("        /// Deserialize from TarsInputStream\n")
	sb.WriteString("        /// </summary>\n")
	sb.WriteString("        public void ReadFrom(TarsInputStream ist)\n")
	sb.WriteString("        {\n")

	for _, f := range s.Fields {
		fieldName := g.toCSharpFieldName(f.Name)
		required := "true"
		if !f.IsRequired {
			required = "false"
		}

		// Determine default value for Read
		defaultVal := g.getTypeDefault(f.Type)
		if f.HasDefault {
			defaultVal = g.getCSharpDefault(f, ns)
		}

		csType := g.toCSharpType(f.Type)

		// Check if this is a struct type that needs special handling
		if g.isStructType(f.Type, ns) {
			sb.WriteString(fmt.Sprintf("            %s = ist.Read<%s>(%d, %s);\n",
				fieldName, csType, f.Tag, required))
		} else if g.isEnumType(f.Type, ns) {
			// For enum types, read as int and cast
			sb.WriteString(fmt.Sprintf("            %s = (%s)ist.Read(0, %d, %s);\n",
				fieldName, csType, f.Tag, required))
		} else if g.isVectorType(f.Type) {
			sb.WriteString(fmt.Sprintf("            %s = ist.ReadList<%s>(%d, %s);\n",
				fieldName, g.getVectorElementType(f.Type), f.Tag, required))
		} else if g.isMapType(f.Type) {
			kt, vt := g.getMapKeyValueTypes(f.Type)
			sb.WriteString(fmt.Sprintf("            %s = ist.ReadMap<%s, %s>(%d, %s);\n",
				fieldName, kt, vt, f.Tag, required))
		} else {
			sb.WriteString(fmt.Sprintf("            %s = ist.Read(%s, %d, %s);\n",
				fieldName, defaultVal, f.Tag, required))
		}
	}

	sb.WriteString("        }\n")

	return sb.String()
}

func (g *Generator) generateInterface(iface *ast.Interface) string {
	var sb strings.Builder

	// Interface definition (pure interface)
	sb.WriteString(fmt.Sprintf("    /// <summary>\n"))
	sb.WriteString(fmt.Sprintf("    /// Interface for %s\n", iface.Name))
	sb.WriteString(fmt.Sprintf("    /// </summary>\n"))
	sb.WriteString(fmt.Sprintf("    public interface I%s\n    {\n", iface.Name))

	for _, op := range iface.Operations {
		sb.WriteString(g.generateOperation(op, false))
		sb.WriteString(g.generateOperation(op, true)) // async version
	}

	sb.WriteString("    }\n")

	return sb.String()
}

func (g *Generator) generateOperation(op *ast.Operation, async bool) string {
	var sb strings.Builder

	returnType := g.toCSharpType(op.ReturnType)
	if returnType == "" {
		returnType = "void"
	}

	var params []string
	for _, p := range op.Params {
		csType := g.toCSharpType(p.Type)
		if p.IsOut {
			params = append(params, fmt.Sprintf("out %s %s", csType, p.Name))
		} else {
			params = append(params, fmt.Sprintf("%s %s", csType, p.Name))
		}
	}

	if async {
		// Async methods cannot have out parameters in the signature
		var asyncParams []string
		for _, p := range op.Params {
			csType := g.toCSharpType(p.Type)
			if !p.IsOut {
				asyncParams = append(asyncParams, fmt.Sprintf("%s %s", csType, p.Name))
			}
		}

		asyncReturnType := "Task"
		if returnType != "void" {
			asyncReturnType = fmt.Sprintf("Task<%s>", returnType)
		}
		sb.WriteString(fmt.Sprintf("        %s %sAsync(%s);\n", asyncReturnType, op.Name, strings.Join(asyncParams, ", ")))
	} else {
		sb.WriteString(fmt.Sprintf("        %s %s(%s);\n", returnType, op.Name, strings.Join(params, ", ")))
	}

	return sb.String()
}

func (g *Generator) generateCodecFile(ns *ast.Namespace, nsDir string) error {
	var sb strings.Builder

	// File header
	sb.WriteString("// Generated by tarsc - Tars IDL Compiler\n")
	sb.WriteString("// DO NOT EDIT!\n\n")

	sb.WriteString("using System;\n")
	sb.WriteString("using System.Collections.Generic;\n")
	sb.WriteString("using System.IO;\n")
	sb.WriteString("using System.Text;\n\n")

	sb.WriteString(fmt.Sprintf("namespace %s\n{\n", ns.Name))

	// TarsStructAttribute
	sb.WriteString(`    /// <summary>
    /// Attribute for Tars struct
    /// </summary>
    [AttributeUsage(AttributeTargets.Class | AttributeTargets.Struct)]
    public class TarsStructAttribute : Attribute
    {
    }

    /// <summary>
    /// Attribute for Tars struct property
    /// </summary>
    [AttributeUsage(AttributeTargets.Property)]
    public class TarsStructPropertyAttribute : Attribute
    {
        public int Tag { get; }
        public bool IsRequire { get; set; }

        public TarsStructPropertyAttribute(int tag)
        {
            Tag = tag;
        }
    }

`)

	// TarsOutputStream
	sb.WriteString(`    /// <summary>
    /// Output stream for Tars serialization
    /// </summary>
    public class TarsOutputStream
    {
        private readonly MemoryStream _stream;
        private readonly BinaryWriter _writer;

        public TarsOutputStream()
        {
            _stream = new MemoryStream();
            _writer = new BinaryWriter(_stream);
        }

        public void Write(bool val, int tag)
        {
            WriteHead(0, tag);
            _writer.Write((byte)(val ? 1 : 0));
        }

        public void Write(sbyte val, int tag)
        {
            if (val == 0)
            {
                WriteHead(12, tag);
            }
            else
            {
                WriteHead(0, tag);
                _writer.Write((byte)val);
            }
        }

        public void Write(byte val, int tag)
        {
            Write((short)val, tag);
        }

        public void Write(short val, int tag)
        {
            if (val >= -128 && val <= 127)
            {
                Write((sbyte)val, tag);
            }
            else
            {
                WriteHead(1, tag);
                _writer.Write((short)((val >> 8) | (val << 8)));
            }
        }

        public void Write(int val, int tag)
        {
            if (val >= short.MinValue && val <= short.MaxValue)
            {
                Write((short)val, tag);
            }
            else
            {
                WriteHead(2, tag);
                WriteInt32BE(val);
            }
        }

        public void Write(long val, int tag)
        {
            if (val >= int.MinValue && val <= int.MaxValue)
            {
                Write((int)val, tag);
            }
            else
            {
                WriteHead(3, tag);
                WriteInt64BE(val);
            }
        }

        public void Write(float val, int tag)
        {
            WriteHead(4, tag);
            byte[] bytes = BitConverter.GetBytes(val);
            if (BitConverter.IsLittleEndian)
                Array.Reverse(bytes);
            _writer.Write(bytes);
        }

        public void Write(double val, int tag)
        {
            WriteHead(5, tag);
            byte[] bytes = BitConverter.GetBytes(val);
            if (BitConverter.IsLittleEndian)
                Array.Reverse(bytes);
            _writer.Write(bytes);
        }

        public void Write(string val, int tag)
        {
            if (val == null) val = "";
            byte[] bytes = Encoding.UTF8.GetBytes(val);
            if (bytes.Length <= 255)
            {
                WriteHead(6, tag);
                _writer.Write((byte)bytes.Length);
            }
            else
            {
                WriteHead(7, tag);
                WriteInt32BE(bytes.Length);
            }
            _writer.Write(bytes);
        }

        public void Write<T>(List<T> val, int tag)
        {
            WriteHead(9, tag);
            if (val == null)
            {
                Write(0, 0);
            }
            else
            {
                Write(val.Count, 0);
                foreach (var item in val)
                {
                    WriteAny(item, 0);
                }
            }
        }

        public void Write<K, V>(Dictionary<K, V> val, int tag)
        {
            WriteHead(8, tag);
            if (val == null)
            {
                Write(0, 0);
            }
            else
            {
                Write(val.Count, 0);
                foreach (var kvp in val)
                {
                    WriteAny(kvp.Key, 0);
                    WriteAny(kvp.Value, 1);
                }
            }
        }

        public void Write(byte[] val, int tag)
        {
            WriteHead(13, tag);
            WriteHead(0, 0);
            if (val == null)
            {
                Write(0, 0);
            }
            else
            {
                Write(val.Length, 0);
                _writer.Write(val);
            }
        }

        public void WriteStruct<T>(T val, int tag) where T : class
        {
            WriteHead(10, tag);
            if (val != null)
            {
                var method = val.GetType().GetMethod("WriteTo");
                method?.Invoke(val, new object[] { this });
            }
            WriteHead(11, 0);
        }

        private void WriteAny<T>(T val, int tag)
        {
            switch (val)
            {
                case bool b: Write(b, tag); break;
                case sbyte sb: Write(sb, tag); break;
                case byte by: Write(by, tag); break;
                case short s: Write(s, tag); break;
                case int i: Write(i, tag); break;
                case long l: Write(l, tag); break;
                case float f: Write(f, tag); break;
                case double d: Write(d, tag); break;
                case string str: Write(str, tag); break;
                default:
                    var method = val?.GetType().GetMethod("WriteTo");
                    if (method != null)
                    {
                        WriteHead(10, tag);
                        method.Invoke(val, new object[] { this });
                        WriteHead(11, 0);
                    }
                    break;
            }
        }

        private void WriteHead(int type, int tag)
        {
            if (tag < 15)
            {
                _writer.Write((byte)((tag << 4) | type));
            }
            else
            {
                _writer.Write((byte)(0xF0 | type));
                _writer.Write((byte)tag);
            }
        }

        private void WriteInt32BE(int val)
        {
            _writer.Write((byte)(val >> 24));
            _writer.Write((byte)(val >> 16));
            _writer.Write((byte)(val >> 8));
            _writer.Write((byte)val);
        }

        private void WriteInt64BE(long val)
        {
            _writer.Write((byte)(val >> 56));
            _writer.Write((byte)(val >> 48));
            _writer.Write((byte)(val >> 40));
            _writer.Write((byte)(val >> 32));
            _writer.Write((byte)(val >> 24));
            _writer.Write((byte)(val >> 16));
            _writer.Write((byte)(val >> 8));
            _writer.Write((byte)val);
        }

        public byte[] ToByteArray()
        {
            return _stream.ToArray();
        }

        public void Dispose()
        {
            _writer?.Dispose();
            _stream?.Dispose();
        }
    }

`)

	// TarsInputStream
	sb.WriteString(`    /// <summary>
    /// Input stream for Tars deserialization
    /// </summary>
    public class TarsInputStream
    {
        private readonly byte[] _buffer;
        private int _position;

        public TarsInputStream(byte[] buffer)
        {
            _buffer = buffer ?? throw new ArgumentNullException(nameof(buffer));
            _position = 0;
        }

        public bool Read(bool defaultVal, int tag, bool isRequire)
        {
            if (!SkipToTag(tag))
            {
                if (isRequire) throw new TarsDecodeException($"Required field not found: tag={tag}");
                return defaultVal;
            }
            var head = ReadHead();
            return ReadByte() != 0;
        }

        public sbyte Read(sbyte defaultVal, int tag, bool isRequire)
        {
            if (!SkipToTag(tag))
            {
                if (isRequire) throw new TarsDecodeException($"Required field not found: tag={tag}");
                return defaultVal;
            }
            var head = ReadHead();
            if (head.Type == 12) return 0;
            return (sbyte)ReadByte();
        }

        public byte Read(byte defaultVal, int tag, bool isRequire)
        {
            return (byte)Read((short)defaultVal, tag, isRequire);
        }

        public short Read(short defaultVal, int tag, bool isRequire)
        {
            if (!SkipToTag(tag))
            {
                if (isRequire) throw new TarsDecodeException($"Required field not found: tag={tag}");
                return defaultVal;
            }
            var head = ReadHead();
            switch (head.Type)
            {
                case 0: return (short)(sbyte)ReadByte();
                case 1: return ReadInt16BE();
                case 12: return 0;
                default: throw new TarsDecodeException($"Type mismatch: expected short, got type={head.Type}");
            }
        }

        public int Read(int defaultVal, int tag, bool isRequire)
        {
            if (!SkipToTag(tag))
            {
                if (isRequire) throw new TarsDecodeException($"Required field not found: tag={tag}");
                return defaultVal;
            }
            var head = ReadHead();
            switch (head.Type)
            {
                case 0: return (sbyte)ReadByte();
                case 1: return ReadInt16BE();
                case 2: return ReadInt32BE();
                case 12: return 0;
                default: throw new TarsDecodeException($"Type mismatch: expected int, got type={head.Type}");
            }
        }

        public long Read(long defaultVal, int tag, bool isRequire)
        {
            if (!SkipToTag(tag))
            {
                if (isRequire) throw new TarsDecodeException($"Required field not found: tag={tag}");
                return defaultVal;
            }
            var head = ReadHead();
            switch (head.Type)
            {
                case 0: return (sbyte)ReadByte();
                case 1: return ReadInt16BE();
                case 2: return ReadInt32BE();
                case 3: return ReadInt64BE();
                case 12: return 0;
                default: throw new TarsDecodeException($"Type mismatch: expected long, got type={head.Type}");
            }
        }

        public float Read(float defaultVal, int tag, bool isRequire)
        {
            if (!SkipToTag(tag))
            {
                if (isRequire) throw new TarsDecodeException($"Required field not found: tag={tag}");
                return defaultVal;
            }
            var head = ReadHead();
            if (head.Type == 12) return 0;
            if (head.Type != 4) throw new TarsDecodeException($"Type mismatch: expected float, got type={head.Type}");
            byte[] bytes = ReadBytes(4);
            if (BitConverter.IsLittleEndian) Array.Reverse(bytes);
            return BitConverter.ToSingle(bytes, 0);
        }

        public double Read(double defaultVal, int tag, bool isRequire)
        {
            if (!SkipToTag(tag))
            {
                if (isRequire) throw new TarsDecodeException($"Required field not found: tag={tag}");
                return defaultVal;
            }
            var head = ReadHead();
            switch (head.Type)
            {
                case 4:
                    byte[] floatBytes = ReadBytes(4);
                    if (BitConverter.IsLittleEndian) Array.Reverse(floatBytes);
                    return BitConverter.ToSingle(floatBytes, 0);
                case 5:
                    byte[] doubleBytes = ReadBytes(8);
                    if (BitConverter.IsLittleEndian) Array.Reverse(doubleBytes);
                    return BitConverter.ToDouble(doubleBytes, 0);
                case 12: return 0;
                default: throw new TarsDecodeException($"Type mismatch: expected double, got type={head.Type}");
            }
        }

        public string Read(string defaultVal, int tag, bool isRequire)
        {
            if (!SkipToTag(tag))
            {
                if (isRequire) throw new TarsDecodeException($"Required field not found: tag={tag}");
                return defaultVal;
            }
            var head = ReadHead();
            int len;
            switch (head.Type)
            {
                case 6:
                    len = ReadByte();
                    break;
                case 7:
                    len = ReadInt32BE();
                    break;
                default:
                    throw new TarsDecodeException($"Type mismatch: expected string, got type={head.Type}");
            }
            return Encoding.UTF8.GetString(ReadBytes(len));
        }

        public T Read<T>(int tag, bool isRequire) where T : class, new()
        {
            if (!SkipToTag(tag))
            {
                if (isRequire) throw new TarsDecodeException($"Required field not found: tag={tag}");
                return null;
            }
            var head = ReadHead();
            if (head.Type != 10) throw new TarsDecodeException($"Type mismatch: expected struct, got type={head.Type}");

            var result = new T();
            var method = typeof(T).GetMethod("ReadFrom");
            method?.Invoke(result, new object[] { this });

            SkipToStructEnd();
            return result;
        }

        public List<T> ReadList<T>(int tag, bool isRequire)
        {
            if (!SkipToTag(tag))
            {
                if (isRequire) throw new TarsDecodeException($"Required field not found: tag={tag}");
                return new List<T>();
            }
            var head = ReadHead();
            if (head.Type != 9) throw new TarsDecodeException($"Type mismatch: expected list, got type={head.Type}");

            int count = Read(0, 0, true);
            var result = new List<T>(count);
            for (int i = 0; i < count; i++)
            {
                result.Add(ReadElement<T>(0));
            }
            return result;
        }

        public Dictionary<K, V> ReadMap<K, V>(int tag, bool isRequire)
        {
            if (!SkipToTag(tag))
            {
                if (isRequire) throw new TarsDecodeException($"Required field not found: tag={tag}");
                return new Dictionary<K, V>();
            }
            var head = ReadHead();
            if (head.Type != 8) throw new TarsDecodeException($"Type mismatch: expected map, got type={head.Type}");

            int count = Read(0, 0, true);
            var result = new Dictionary<K, V>(count);
            for (int i = 0; i < count; i++)
            {
                K key = ReadElement<K>(0);
                V value = ReadElement<V>(1);
                result[key] = value;
            }
            return result;
        }

        public byte[] ReadBytes(int tag, bool isRequire)
        {
            if (!SkipToTag(tag))
            {
                if (isRequire) throw new TarsDecodeException($"Required field not found: tag={tag}");
                return Array.Empty<byte>();
            }
            var head = ReadHead();
            if (head.Type != 13) throw new TarsDecodeException($"Type mismatch: expected bytes, got type={head.Type}");

            var subHead = ReadHead();
            int len = Read(0, 0, true);
            return ReadBytes(len);
        }

        private T ReadElement<T>(int tag)
        {
            var type = typeof(T);
            if (type == typeof(bool)) return (T)(object)Read(false, tag, true);
            if (type == typeof(sbyte)) return (T)(object)Read((sbyte)0, tag, true);
            if (type == typeof(byte)) return (T)(object)Read((byte)0, tag, true);
            if (type == typeof(short)) return (T)(object)Read((short)0, tag, true);
            if (type == typeof(int)) return (T)(object)Read(0, tag, true);
            if (type == typeof(long)) return (T)(object)Read(0L, tag, true);
            if (type == typeof(float)) return (T)(object)Read(0f, tag, true);
            if (type == typeof(double)) return (T)(object)Read(0d, tag, true);
            if (type == typeof(string)) return (T)(object)Read("", tag, true);

            // Struct type
            if (!SkipToTag(tag)) throw new TarsDecodeException($"Required field not found: tag={tag}");
            var head = ReadHead();
            if (head.Type != 10) throw new TarsDecodeException($"Type mismatch: expected struct, got type={head.Type}");

            var result = Activator.CreateInstance<T>();
            var method = type.GetMethod("ReadFrom");
            method?.Invoke(result, new object[] { this });

            SkipToStructEnd();
            return result;
        }

        private bool SkipToTag(int tag)
        {
            while (_position < _buffer.Length)
            {
                int savedPos = _position;
                var head = PeekHead();
                if (head.Type == 11) return false;
                if (head.Tag == tag) return true;
                if (head.Tag > tag) { _position = savedPos; return false; }
                ReadHead();
                SkipField(head.Type);
            }
            return false;
        }

        private void SkipToStructEnd()
        {
            while (_position < _buffer.Length)
            {
                var head = ReadHead();
                if (head.Type == 11) return;
                SkipField(head.Type);
            }
        }

        private void SkipField(int type)
        {
            switch (type)
            {
                case 0: _position += 1; break;
                case 1: _position += 2; break;
                case 2: _position += 4; break;
                case 3: _position += 8; break;
                case 4: _position += 4; break;
                case 5: _position += 8; break;
                case 6: _position += 1 + ReadByte(); break;
                case 7: _position += 4 + ReadInt32BE(); break;
                case 8: // Map
                    int mapCount = Read(0, 0, true);
                    for (int i = 0; i < mapCount * 2; i++) { var h = ReadHead(); SkipField(h.Type); }
                    break;
                case 9: // List
                    int listCount = Read(0, 0, true);
                    for (int i = 0; i < listCount; i++) { var h = ReadHead(); SkipField(h.Type); }
                    break;
                case 10: SkipToStructEnd(); break;
                case 11: break;
                case 12: break;
                case 13: // SimpleList (bytes)
                    var subHead = ReadHead();
                    int len = Read(0, 0, true);
                    _position += len;
                    break;
            }
        }

        private (int Type, int Tag) ReadHead()
        {
            byte b = ReadByte();
            int type = b & 0x0F;
            int tag = (b >> 4) & 0x0F;
            if (tag == 15)
            {
                tag = ReadByte();
            }
            return (type, tag);
        }

        private (int Type, int Tag) PeekHead()
        {
            int savedPos = _position;
            var head = ReadHead();
            _position = savedPos;
            return head;
        }

        private byte ReadByte()
        {
            if (_position >= _buffer.Length) throw new TarsDecodeException("Unexpected end of buffer");
            return _buffer[_position++];
        }

        private byte[] ReadBytes(int count)
        {
            if (_position + count > _buffer.Length) throw new TarsDecodeException("Unexpected end of buffer");
            var result = new byte[count];
            Array.Copy(_buffer, _position, result, 0, count);
            _position += count;
            return result;
        }

        private short ReadInt16BE()
        {
            byte b1 = ReadByte();
            byte b2 = ReadByte();
            return (short)((b1 << 8) | b2);
        }

        private int ReadInt32BE()
        {
            byte b1 = ReadByte();
            byte b2 = ReadByte();
            byte b3 = ReadByte();
            byte b4 = ReadByte();
            return (b1 << 24) | (b2 << 16) | (b3 << 8) | b4;
        }

        private long ReadInt64BE()
        {
            long result = 0;
            for (int i = 0; i < 8; i++)
            {
                result = (result << 8) | ReadByte();
            }
            return result;
        }
    }

    /// <summary>
    /// Exception for Tars decode errors
    /// </summary>
    public class TarsDecodeException : Exception
    {
        public TarsDecodeException(string message) : base(message) { }
    }

`)

	// TarsServantProxy base class
	sb.WriteString(`    /// <summary>
    /// Base class for Tars servant proxy
    /// </summary>
    public abstract class TarsServantProxy
    {
        private Func<string, byte[], byte[]> _invokeFunc;
        private Func<string, byte[], System.Threading.Tasks.Task<byte[]>> _invokeAsyncFunc;

        /// <summary>
        /// Set the invoke function for sync calls
        /// </summary>
        public void SetInvokeFunc(Func<string, byte[], byte[]> func)
        {
            _invokeFunc = func;
        }

        /// <summary>
        /// Set the invoke function for async calls
        /// </summary>
        public void SetInvokeAsyncFunc(Func<string, byte[], System.Threading.Tasks.Task<byte[]>> func)
        {
            _invokeAsyncFunc = func;
        }

        /// <summary>
        /// Invoke a method synchronously
        /// </summary>
        protected TarsInputStream Invoke(string funcName, TarsOutputStream os)
        {
            if (_invokeFunc == null)
                throw new InvalidOperationException("Invoke function not set. Call SetInvokeFunc first.");

            byte[] response = _invokeFunc(funcName, os.ToByteArray());
            return new TarsInputStream(response);
        }

        /// <summary>
        /// Invoke a method asynchronously
        /// </summary>
        protected async System.Threading.Tasks.Task<TarsInputStream> InvokeAsync(string funcName, TarsOutputStream os)
        {
            if (_invokeAsyncFunc == null)
                throw new InvalidOperationException("Async invoke function not set. Call SetInvokeAsyncFunc first.");

            byte[] response = await _invokeAsyncFunc(funcName, os.ToByteArray());
            return new TarsInputStream(response);
        }
    }

`)

	// TarsServant base class
	sb.WriteString(`    /// <summary>
    /// Base class for Tars servant implementation
    /// </summary>
    public abstract class TarsServant
    {
        /// <summary>
        /// Dispatch a request to the appropriate method
        /// </summary>
        public abstract byte[] Dispatch(string funcName, byte[] request);
    }
`)

	sb.WriteString("}\n")

	// Write file
	filePath := filepath.Join(nsDir, "TarsCodec.cs")
	return os.WriteFile(filePath, []byte(sb.String()), 0644)
}

func (g *Generator) generatePrxFile(ns *ast.Namespace, iface *ast.Interface, nsDir string) error {
	var sb strings.Builder

	// File header
	sb.WriteString("// Generated by tarsc - Tars IDL Compiler\n")
	sb.WriteString("// DO NOT EDIT!\n\n")

	sb.WriteString("using System;\n")
	sb.WriteString("using System.Collections.Generic;\n")
	sb.WriteString("using System.Threading.Tasks;\n\n")

	sb.WriteString(fmt.Sprintf("namespace %s\n{\n", ns.Name))

	// Proxy class
	sb.WriteString(fmt.Sprintf("    /// <summary>\n"))
	sb.WriteString(fmt.Sprintf("    /// Client proxy for %s\n", iface.Name))
	sb.WriteString(fmt.Sprintf("    /// </summary>\n"))
	sb.WriteString(fmt.Sprintf("    public class %sPrx : TarsServantProxy, I%s\n    {\n", iface.Name, iface.Name))

	for _, op := range iface.Operations {
		sb.WriteString(g.generatePrxMethod(op, false))
		sb.WriteString("\n")
		sb.WriteString(g.generatePrxMethod(op, true)) // async version
		sb.WriteString("\n")
	}

	sb.WriteString("    }\n")
	sb.WriteString("}\n")

	// Write file
	filePath := filepath.Join(nsDir, iface.Name+"Prx.cs")
	return os.WriteFile(filePath, []byte(sb.String()), 0644)
}

func (g *Generator) generatePrxMethod(op *ast.Operation, async bool) string {
	var sb strings.Builder

	returnType := g.toCSharpType(op.ReturnType)
	if returnType == "" {
		returnType = "void"
	}
	hasReturn := returnType != "void"

	// Build parameter list
	var params []string
	var asyncParams []string
	var outParams []*ast.ParamDecl
	for _, p := range op.Params {
		csType := g.toCSharpType(p.Type)
		if p.IsOut {
			outParams = append(outParams, p)
			params = append(params, fmt.Sprintf("out %s %s", csType, p.Name))
		} else {
			params = append(params, fmt.Sprintf("%s %s", csType, p.Name))
			asyncParams = append(asyncParams, fmt.Sprintf("%s %s", csType, p.Name))
		}
	}

	if async {
		asyncReturnType := "Task"
		if hasReturn {
			asyncReturnType = fmt.Sprintf("Task<%s>", returnType)
		}
		sb.WriteString(fmt.Sprintf("        public async %s %sAsync(%s)\n",
			asyncReturnType, op.Name, strings.Join(asyncParams, ", ")))
	} else {
		sb.WriteString(fmt.Sprintf("        public %s %s(%s)\n",
			returnType, op.Name, strings.Join(params, ", ")))
	}

	sb.WriteString("        {\n")

	// Create output stream and write parameters
	sb.WriteString("            var os = new TarsOutputStream();\n")
	tagIndex := 1
	for _, p := range op.Params {
		if !p.IsOut {
			if g.isStructType(p.Type, nil) {
				sb.WriteString(fmt.Sprintf("            os.WriteStruct(%s, %d);\n", p.Name, tagIndex))
			} else if g.isVectorType(p.Type) || g.isMapType(p.Type) {
				sb.WriteString(fmt.Sprintf("            os.Write(%s, %d);\n", p.Name, tagIndex))
			} else {
				sb.WriteString(fmt.Sprintf("            os.Write(%s, %d);\n", p.Name, tagIndex))
			}
		}
		tagIndex++
	}

	// Invoke
	if async {
		sb.WriteString(fmt.Sprintf("            var ist = await InvokeAsync(\"%s\", os);\n", g.toLowerFirst(op.Name)))
	} else {
		sb.WriteString(fmt.Sprintf("            var ist = Invoke(\"%s\", os);\n", g.toLowerFirst(op.Name)))
	}

	// Read out parameters (only for sync methods)
	if !async {
		for _, p := range outParams {
			csType := g.toCSharpType(p.Type)
			// Find the tag index for this out parameter
			outTag := 1
			for _, param := range op.Params {
				if param == p {
					break
				}
				outTag++
			}
			if g.isStructType(p.Type, nil) {
				sb.WriteString(fmt.Sprintf("            %s = ist.Read<%s>(%d, true);\n", p.Name, csType, outTag))
			} else if g.isVectorType(p.Type) {
				sb.WriteString(fmt.Sprintf("            %s = ist.ReadList<%s>(%d, true);\n",
					p.Name, g.getVectorElementType(p.Type), outTag))
			} else if g.isMapType(p.Type) {
				kt, vt := g.getMapKeyValueTypes(p.Type)
				sb.WriteString(fmt.Sprintf("            %s = ist.ReadMap<%s, %s>(%d, true);\n", p.Name, kt, vt, outTag))
			} else {
				sb.WriteString(fmt.Sprintf("            %s = ist.Read(%s, %d, true);\n",
					p.Name, g.getTypeDefaultForRead(p.Type), outTag))
			}
		}
	}

	// Read return value
	if hasReturn {
		if g.isStructType(op.ReturnType, nil) {
			sb.WriteString(fmt.Sprintf("            var ret = ist.Read<%s>(0, true);\n", returnType))
		} else if g.isVectorType(op.ReturnType) {
			sb.WriteString(fmt.Sprintf("            var ret = ist.ReadList<%s>(0, true);\n",
				g.getVectorElementType(op.ReturnType)))
		} else if g.isMapType(op.ReturnType) {
			kt, vt := g.getMapKeyValueTypes(op.ReturnType)
			sb.WriteString(fmt.Sprintf("            var ret = ist.ReadMap<%s, %s>(0, true);\n", kt, vt))
		} else {
			sb.WriteString(fmt.Sprintf("            var ret = ist.Read(%s, 0, true);\n",
				g.getTypeDefaultForRead(op.ReturnType)))
		}
		sb.WriteString("            return ret;\n")
	}

	sb.WriteString("        }\n")

	return sb.String()
}

func (g *Generator) generateServantFile(ns *ast.Namespace, iface *ast.Interface, nsDir string) error {
	var sb strings.Builder

	// File header
	sb.WriteString("// Generated by tarsc - Tars IDL Compiler\n")
	sb.WriteString("// DO NOT EDIT!\n\n")

	sb.WriteString("using System;\n")
	sb.WriteString("using System.Collections.Generic;\n\n")

	sb.WriteString(fmt.Sprintf("namespace %s\n{\n", ns.Name))

	// Servant interface for implementation
	sb.WriteString(fmt.Sprintf("    /// <summary>\n"))
	sb.WriteString(fmt.Sprintf("    /// Servant interface for %s implementation\n", iface.Name))
	sb.WriteString(fmt.Sprintf("    /// </summary>\n"))
	sb.WriteString(fmt.Sprintf("    public interface I%sServant\n    {\n", iface.Name))
	for _, op := range iface.Operations {
		sb.WriteString(g.generateServantInterfaceMethod(op))
	}
	sb.WriteString("    }\n\n")

	// Abstract servant class with dispatch
	sb.WriteString(fmt.Sprintf("    /// <summary>\n"))
	sb.WriteString(fmt.Sprintf("    /// Abstract servant class for %s\n", iface.Name))
	sb.WriteString(fmt.Sprintf("    /// </summary>\n"))
	sb.WriteString(fmt.Sprintf("    public abstract class %sServant : TarsServant, I%sServant\n    {\n", iface.Name, iface.Name))

	// Abstract methods
	for _, op := range iface.Operations {
		sb.WriteString(g.generateServantAbstractMethod(op))
		sb.WriteString("\n")
	}

	// Dispatch method
	sb.WriteString("        /// <summary>\n")
	sb.WriteString("        /// Dispatch incoming request to appropriate method\n")
	sb.WriteString("        /// </summary>\n")
	sb.WriteString("        public override byte[] Dispatch(string funcName, byte[] request)\n")
	sb.WriteString("        {\n")
	sb.WriteString("            var ist = new TarsInputStream(request);\n")
	sb.WriteString("            var os = new TarsOutputStream();\n\n")
	sb.WriteString("            switch (funcName)\n")
	sb.WriteString("            {\n")

	for _, op := range iface.Operations {
		sb.WriteString(g.generateDispatchCase(op))
	}

	sb.WriteString("                default:\n")
	sb.WriteString("                    throw new NotSupportedException($\"Unknown function: {funcName}\");\n")
	sb.WriteString("            }\n\n")
	sb.WriteString("            return os.ToByteArray();\n")
	sb.WriteString("        }\n")

	sb.WriteString("    }\n")
	sb.WriteString("}\n")

	// Write file
	filePath := filepath.Join(nsDir, iface.Name+"Servant.cs")
	return os.WriteFile(filePath, []byte(sb.String()), 0644)
}

func (g *Generator) generateServantInterfaceMethod(op *ast.Operation) string {
	var sb strings.Builder

	returnType := g.toCSharpType(op.ReturnType)
	if returnType == "" {
		returnType = "void"
	}

	var params []string
	for _, p := range op.Params {
		csType := g.toCSharpType(p.Type)
		if p.IsOut {
			params = append(params, fmt.Sprintf("out %s %s", csType, p.Name))
		} else {
			params = append(params, fmt.Sprintf("%s %s", csType, p.Name))
		}
	}

	sb.WriteString(fmt.Sprintf("        %s %s(%s);\n", returnType, op.Name, strings.Join(params, ", ")))

	return sb.String()
}

func (g *Generator) generateServantAbstractMethod(op *ast.Operation) string {
	var sb strings.Builder

	returnType := g.toCSharpType(op.ReturnType)
	if returnType == "" {
		returnType = "void"
	}

	var params []string
	for _, p := range op.Params {
		csType := g.toCSharpType(p.Type)
		if p.IsOut {
			params = append(params, fmt.Sprintf("out %s %s", csType, p.Name))
		} else {
			params = append(params, fmt.Sprintf("%s %s", csType, p.Name))
		}
	}

	sb.WriteString(fmt.Sprintf("        public abstract %s %s(%s);\n", returnType, op.Name, strings.Join(params, ", ")))

	return sb.String()
}

func (g *Generator) generateDispatchCase(op *ast.Operation) string {
	var sb strings.Builder

	returnType := g.toCSharpType(op.ReturnType)
	if returnType == "" {
		returnType = "void"
	}
	hasReturn := returnType != "void"

	sb.WriteString(fmt.Sprintf("                case \"%s\":\n", g.toLowerFirst(op.Name)))
	sb.WriteString("                {\n")

	// Read input parameters
	tagIndex := 1
	var callArgs []string
	for _, p := range op.Params {
		csType := g.toCSharpType(p.Type)
		if p.IsOut {
			sb.WriteString(fmt.Sprintf("                    %s %s;\n", csType, p.Name))
			callArgs = append(callArgs, fmt.Sprintf("out %s", p.Name))
		} else {
			if g.isStructType(p.Type, nil) {
				sb.WriteString(fmt.Sprintf("                    var %s = ist.Read<%s>(%d, true);\n", p.Name, csType, tagIndex))
			} else if g.isVectorType(p.Type) {
				sb.WriteString(fmt.Sprintf("                    var %s = ist.ReadList<%s>(%d, true);\n",
					p.Name, g.getVectorElementType(p.Type), tagIndex))
			} else if g.isMapType(p.Type) {
				kt, vt := g.getMapKeyValueTypes(p.Type)
				sb.WriteString(fmt.Sprintf("                    var %s = ist.ReadMap<%s, %s>(%d, true);\n", p.Name, kt, vt, tagIndex))
			} else {
				sb.WriteString(fmt.Sprintf("                    var %s = ist.Read(%s, %d, true);\n",
					p.Name, g.getTypeDefaultForRead(p.Type), tagIndex))
			}
			callArgs = append(callArgs, p.Name)
		}
		tagIndex++
	}

	// Call method
	if hasReturn {
		sb.WriteString(fmt.Sprintf("                    var result = %s(%s);\n", op.Name, strings.Join(callArgs, ", ")))
	} else {
		sb.WriteString(fmt.Sprintf("                    %s(%s);\n", op.Name, strings.Join(callArgs, ", ")))
	}

	// Write return value
	if hasReturn {
		if g.isStructType(op.ReturnType, nil) {
			sb.WriteString("                    os.WriteStruct(result, 0);\n")
		} else {
			sb.WriteString("                    os.Write(result, 0);\n")
		}
	}

	// Write out parameters
	tagIndex = 1
	for _, p := range op.Params {
		if p.IsOut {
			if g.isStructType(p.Type, nil) {
				sb.WriteString(fmt.Sprintf("                    os.WriteStruct(%s, %d);\n", p.Name, tagIndex))
			} else {
				sb.WriteString(fmt.Sprintf("                    os.Write(%s, %d);\n", p.Name, tagIndex))
			}
		}
		tagIndex++
	}

	sb.WriteString("                    break;\n")
	sb.WriteString("                }\n")

	return sb.String()
}

// Helper methods

func (g *Generator) toCSharpType(t ast.Type) string {
	if t == nil {
		return "void"
	}

	switch v := t.(type) {
	case *ast.BuiltinType:
		switch v.Kind {
		case ast.KindVoid:
			return "void"
		case ast.KindBool:
			return "bool"
		case ast.KindByte:
			if v.IsUnsigned {
				return "byte"
			}
			return "sbyte"
		case ast.KindShort:
			if v.IsUnsigned {
				return "ushort"
			}
			return "short"
		case ast.KindInt:
			if v.IsUnsigned {
				return "uint"
			}
			return "int"
		case ast.KindLong:
			if v.IsUnsigned {
				return "ulong"
			}
			return "long"
		case ast.KindFloat:
			return "float"
		case ast.KindDouble:
			return "double"
		case ast.KindString:
			return "string"
		}
	case *ast.VectorType:
		if bt, ok := v.ElementType.(*ast.BuiltinType); ok && bt.Kind == ast.KindByte {
			return "byte[]"
		}
		return fmt.Sprintf("List<%s>", g.toCSharpType(v.ElementType))
	case *ast.MapType:
		return fmt.Sprintf("Dictionary<%s, %s>", g.toCSharpType(v.KeyType), g.toCSharpType(v.ValueType))
	case *ast.CustomType:
		return v.TypeName_
	}
	return "object"
}

func (g *Generator) toCSharpFieldName(name string) string {
	if len(name) == 0 {
		return name
	}
	return strings.ToUpper(name[:1]) + name[1:]
}

func (g *Generator) toPascalCase(name string) string {
	if len(name) == 0 {
		return name
	}
	// Handle underscore separated names
	parts := strings.Split(name, "_")
	for i, p := range parts {
		if len(p) > 0 {
			parts[i] = strings.ToUpper(p[:1]) + p[1:]
		}
	}
	return strings.Join(parts, "")
}

func (g *Generator) toLowerFirst(name string) string {
	if len(name) == 0 {
		return name
	}
	return strings.ToLower(name[:1]) + name[1:]
}

func (g *Generator) getCSharpDefault(f *ast.Field, ns *ast.Namespace) string {
	if f.DefaultValue == "" {
		return g.getTypeDefault(f.Type)
	}

	switch v := f.Type.(type) {
	case *ast.BuiltinType:
		switch v.Kind {
		case ast.KindString:
			// Ensure string is quoted
			if !strings.HasPrefix(f.DefaultValue, "\"") {
				return fmt.Sprintf("\"%s\"", f.DefaultValue)
			}
			return f.DefaultValue
		case ast.KindFloat:
			return f.DefaultValue + "f"
		default:
			return f.DefaultValue
		}
	case *ast.CustomType:
		// Check if it's an enum reference
		if ns != nil {
			for _, e := range ns.Enums {
				for _, m := range e.Members {
					if m.Name == f.DefaultValue {
						return fmt.Sprintf("%s.%s", e.Name, m.Name)
					}
				}
			}
		}
		return f.DefaultValue
	}
	return f.DefaultValue
}

func (g *Generator) getTypeDefault(t ast.Type) string {
	if t == nil {
		return ""
	}

	switch v := t.(type) {
	case *ast.BuiltinType:
		switch v.Kind {
		case ast.KindBool:
			return "false"
		case ast.KindString:
			return "\"\""
		case ast.KindByte, ast.KindShort, ast.KindInt, ast.KindLong:
			return "0"
		case ast.KindFloat:
			return "0.0f"
		case ast.KindDouble:
			return "0.0"
		}
	case *ast.VectorType:
		return fmt.Sprintf("new %s()", g.toCSharpType(t))
	case *ast.MapType:
		return fmt.Sprintf("new %s()", g.toCSharpType(t))
	case *ast.CustomType:
		return fmt.Sprintf("new %s()", v.TypeName_)
	}
	return ""
}

func (g *Generator) getTypeDefaultForRead(t ast.Type) string {
	if t == nil {
		return "0"
	}

	switch v := t.(type) {
	case *ast.BuiltinType:
		switch v.Kind {
		case ast.KindBool:
			return "false"
		case ast.KindString:
			return "\"\""
		case ast.KindByte, ast.KindShort, ast.KindInt, ast.KindLong:
			return "0"
		case ast.KindFloat:
			return "0f"
		case ast.KindDouble:
			return "0d"
		}
	case *ast.CustomType:
		// Enum defaults
		return "0"
	}
	return "0"
}

func (g *Generator) isStructType(t ast.Type, ns *ast.Namespace) bool {
	if ct, ok := t.(*ast.CustomType); ok {
		// If namespace is provided, check if it's an enum
		if ns != nil {
			for _, e := range ns.Enums {
				if e.Name == ct.TypeName_ {
					return false
				}
			}
		}
		// Assume custom types that are not enums are structs
		return true
	}
	return false
}

func (g *Generator) isEnumType(t ast.Type, ns *ast.Namespace) bool {
	if ct, ok := t.(*ast.CustomType); ok {
		// Check if it's an enum
		if ns != nil {
			for _, e := range ns.Enums {
				if e.Name == ct.TypeName_ {
					return true
				}
			}
		}
	}
	return false
}

func (g *Generator) isVectorType(t ast.Type) bool {
	_, ok := t.(*ast.VectorType)
	return ok
}

func (g *Generator) isMapType(t ast.Type) bool {
	_, ok := t.(*ast.MapType)
	return ok
}

func (g *Generator) getVectorElementType(t ast.Type) string {
	if vt, ok := t.(*ast.VectorType); ok {
		return g.toCSharpType(vt.ElementType)
	}
	return "object"
}

func (g *Generator) getMapKeyValueTypes(t ast.Type) (string, string) {
	if mt, ok := t.(*ast.MapType); ok {
		return g.toCSharpType(mt.KeyType), g.toCSharpType(mt.ValueType)
	}
	return "object", "object"
}
