/**
 * Tencent is pleased to support the open source community by making Tars available.
 *
 * Copyright (C) 2016THL A29 Limited, a Tencent company. All rights reserved.
 *
 * Licensed under the BSD 3-Clause License (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * https://opensource.org/licenses/BSD-3-Clause
 */

// Package objc generates Objective-C code from Tars IDL
package objc

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/TarsCloud/TarsCpp/tools/tarsc-go/pkg/ast"
)

// Generator generates Objective-C code
type Generator struct {
	baseDir string
}

// NewGenerator creates a new Objective-C generator
func NewGenerator(baseDir string) *Generator {
	return &Generator{baseDir: baseDir}
}

// Generate generates Objective-C code for the document
func (g *Generator) Generate(doc *ast.Document, baseName string) error {
	for _, ns := range doc.Namespaces {
		if err := g.generateHeader(doc, ns, baseName); err != nil {
			return err
		}
		if err := g.generateImplementation(doc, ns, baseName); err != nil {
			return err
		}
	}
	return nil
}

func (g *Generator) generateHeader(doc *ast.Document, ns *ast.Namespace, baseName string) error {
	var sb strings.Builder
	prefix := ns.Name

	// Header
	sb.WriteString("// Generated by tarsc - Tars IDL Compiler\n")
	sb.WriteString("// DO NOT EDIT!\n\n")

	sb.WriteString("#import <Foundation/Foundation.h>\n")
	sb.WriteString("#import \"TarsObject.h\"\n\n")

	sb.WriteString("NS_ASSUME_NONNULL_BEGIN\n\n")

	// Generate enums
	for _, e := range ns.Enums {
		sb.WriteString(g.generateEnumHeader(e, prefix))
		sb.WriteString("\n")
	}

	// Forward declarations
	for _, s := range ns.Structs {
		sb.WriteString(fmt.Sprintf("@class %s%s;\n", prefix, s.Name))
	}
	if len(ns.Structs) > 0 {
		sb.WriteString("\n")
	}

	// Generate structs
	for _, s := range ns.Structs {
		sb.WriteString(g.generateStructHeader(s, prefix))
		sb.WriteString("\n")
	}

	// Generate interfaces
	for _, iface := range ns.Interfaces {
		sb.WriteString(g.generateInterfaceHeader(iface, prefix))
		sb.WriteString("\n")
	}

	sb.WriteString("NS_ASSUME_NONNULL_END\n")

	// Write file
	if err := os.MkdirAll(g.baseDir, 0755); err != nil {
		return err
	}

	filePath := filepath.Join(g.baseDir, prefix+baseName+".h")
	return os.WriteFile(filePath, []byte(sb.String()), 0644)
}

func (g *Generator) generateImplementation(doc *ast.Document, ns *ast.Namespace, baseName string) error {
	var sb strings.Builder
	prefix := ns.Name

	// Header
	sb.WriteString("// Generated by tarsc - Tars IDL Compiler\n")
	sb.WriteString("// DO NOT EDIT!\n\n")

	sb.WriteString(fmt.Sprintf("#import \"%s%s.h\"\n\n", prefix, baseName))

	// Generate struct implementations
	for _, s := range ns.Structs {
		sb.WriteString(g.generateStructImpl(s, prefix))
		sb.WriteString("\n")
	}

	// Generate interface implementations
	for _, iface := range ns.Interfaces {
		sb.WriteString(g.generateInterfaceImpl(iface, prefix))
		sb.WriteString("\n")
	}

	// Write file
	filePath := filepath.Join(g.baseDir, prefix+baseName+".m")
	return os.WriteFile(filePath, []byte(sb.String()), 0644)
}

func (g *Generator) generateEnumHeader(e *ast.Enum, prefix string) string {
	var sb strings.Builder

	sb.WriteString(fmt.Sprintf("typedef NS_ENUM(NSInteger, %s%s) {\n", prefix, e.Name))
	for _, m := range e.Members {
		sb.WriteString(fmt.Sprintf("    %s%s%s = %d,\n", prefix, e.Name, m.Name, m.Value))
	}
	sb.WriteString("};\n")

	return sb.String()
}

func (g *Generator) generateStructHeader(s *ast.Struct, prefix string) string {
	var sb strings.Builder

	sb.WriteString(fmt.Sprintf("@interface %s%s : TarsObject\n\n", prefix, s.Name))

	// Properties
	for _, f := range s.Fields {
		objcType := g.toObjcType(f.Type)
		sb.WriteString(fmt.Sprintf("@property (nonatomic, %s) %s %s;\n", g.getPropertyAttr(f.Type), objcType, f.Name))
	}

	sb.WriteString("\n@end\n")

	return sb.String()
}

func (g *Generator) generateStructImpl(s *ast.Struct, prefix string) string {
	var sb strings.Builder

	sb.WriteString(fmt.Sprintf("@implementation %s%s\n\n", prefix, s.Name))

	// init method
	sb.WriteString("- (instancetype)init {\n")
	sb.WriteString("    self = [super init];\n")
	sb.WriteString("    if (self) {\n")
	for _, f := range s.Fields {
		defaultVal := g.getObjcDefault(f)
		if defaultVal != "" {
			sb.WriteString(fmt.Sprintf("        _%s = %s;\n", f.Name, defaultVal))
		}
	}
	sb.WriteString("    }\n")
	sb.WriteString("    return self;\n")
	sb.WriteString("}\n\n")

	// __encode method
	sb.WriteString("- (void)__encode:(TarsOutputStream *)os {\n")
	for _, f := range s.Fields {
		sb.WriteString(fmt.Sprintf("    [os write:self.%s tag:%d];\n", f.Name, f.Tag))
	}
	sb.WriteString("}\n\n")

	// __decode method
	sb.WriteString("- (void)__decode:(TarsInputStream *)is {\n")
	for _, f := range s.Fields {
		required := "YES"
		if !f.IsRequired {
			required = "NO"
		}
		sb.WriteString(fmt.Sprintf("    self.%s = [is read:self.%s tag:%d require:%s];\n", f.Name, f.Name, f.Tag, required))
	}
	sb.WriteString("}\n")

	sb.WriteString("\n@end\n")

	return sb.String()
}

func (g *Generator) generateInterfaceHeader(iface *ast.Interface, prefix string) string {
	var sb strings.Builder

	// Protocol
	sb.WriteString(fmt.Sprintf("@protocol %s%sServant <NSObject>\n\n", prefix, iface.Name))

	for _, op := range iface.Operations {
		sb.WriteString(g.generateMethodDecl(op))
	}

	sb.WriteString("\n@end\n\n")

	// Proxy class
	sb.WriteString(fmt.Sprintf("@interface %s%sProxy : TarsObjectProxy <%s%sServant>\n\n", prefix, iface.Name, prefix, iface.Name))
	sb.WriteString("@end\n")

	return sb.String()
}

func (g *Generator) generateInterfaceImpl(iface *ast.Interface, prefix string) string {
	var sb strings.Builder

	sb.WriteString(fmt.Sprintf("@implementation %s%sProxy\n\n", prefix, iface.Name))

	for _, op := range iface.Operations {
		sb.WriteString(g.generateMethodImpl(op))
		sb.WriteString("\n")
	}

	sb.WriteString("@end\n")

	return sb.String()
}

func (g *Generator) generateMethodDecl(op *ast.Operation) string {
	var sb strings.Builder

	returnType := g.toObjcType(op.ReturnType)
	if returnType == "" {
		returnType = "void"
	}

	sb.WriteString(fmt.Sprintf("- (%s)%s", returnType, op.Name))

	for i, p := range op.Params {
		objcType := g.toObjcType(p.Type)
		if p.IsOut {
			objcType += " *"
		}
		if i == 0 {
			sb.WriteString(fmt.Sprintf(":(%s)%s", objcType, p.Name))
		} else {
			sb.WriteString(fmt.Sprintf(" %s:(%s)%s", p.Name, objcType, p.Name))
		}
	}

	sb.WriteString(";\n")

	return sb.String()
}

func (g *Generator) generateMethodImpl(op *ast.Operation) string {
	var sb strings.Builder

	returnType := g.toObjcType(op.ReturnType)
	if returnType == "" {
		returnType = "void"
	}

	sb.WriteString(fmt.Sprintf("- (%s)%s", returnType, op.Name))

	for i, p := range op.Params {
		objcType := g.toObjcType(p.Type)
		if p.IsOut {
			objcType += " *"
		}
		if i == 0 {
			sb.WriteString(fmt.Sprintf(":(%s)%s", objcType, p.Name))
		} else {
			sb.WriteString(fmt.Sprintf(" %s:(%s)%s", p.Name, objcType, p.Name))
		}
	}

	sb.WriteString(" {\n")
	sb.WriteString("    // TODO: Implement proxy call\n")
	if returnType != "void" {
		sb.WriteString(fmt.Sprintf("    return %s;\n", g.getTypeDefaultValue(op.ReturnType)))
	}
	sb.WriteString("}\n")

	return sb.String()
}

func (g *Generator) toObjcType(t ast.Type) string {
	if t == nil {
		return "void"
	}

	switch v := t.(type) {
	case *ast.BuiltinType:
		switch v.Kind {
		case ast.KindVoid:
			return "void"
		case ast.KindBool:
			return "BOOL"
		case ast.KindByte:
			return "int8_t"
		case ast.KindShort:
			if v.IsUnsigned {
				return "uint16_t"
			}
			return "int16_t"
		case ast.KindInt:
			if v.IsUnsigned {
				return "uint32_t"
			}
			return "int32_t"
		case ast.KindLong:
			if v.IsUnsigned {
				return "uint64_t"
			}
			return "int64_t"
		case ast.KindFloat:
			return "float"
		case ast.KindDouble:
			return "double"
		case ast.KindString:
			return "NSString *"
		}
	case *ast.VectorType:
		if bt, ok := v.ElementType.(*ast.BuiltinType); ok && bt.Kind == ast.KindByte {
			return "NSData *"
		}
		return "NSArray *"
	case *ast.MapType:
		return "NSDictionary *"
	case *ast.CustomType:
		return v.TypeName_ + " *"
	}
	return "id"
}

func (g *Generator) getPropertyAttr(t ast.Type) string {
	switch v := t.(type) {
	case *ast.BuiltinType:
		switch v.Kind {
		case ast.KindBool, ast.KindByte, ast.KindShort, ast.KindInt, ast.KindLong, ast.KindFloat, ast.KindDouble:
			return "assign"
		case ast.KindString:
			return "copy"
		}
	case *ast.VectorType, *ast.MapType, *ast.CustomType:
		return "strong"
	}
	return "strong"
}

func (g *Generator) getObjcDefault(f *ast.Field) string {
	if f.HasDefault && f.DefaultValue != "" {
		return f.DefaultValue
	}
	return g.getTypeDefaultValue(f.Type)
}

func (g *Generator) getTypeDefaultValue(t ast.Type) string {
	if t == nil {
		return ""
	}

	switch v := t.(type) {
	case *ast.BuiltinType:
		switch v.Kind {
		case ast.KindBool:
			return "NO"
		case ast.KindString:
			return "@\"\""
		case ast.KindByte, ast.KindShort, ast.KindInt, ast.KindLong:
			return "0"
		case ast.KindFloat, ast.KindDouble:
			return "0.0"
		}
	case *ast.VectorType:
		return "@[]"
	case *ast.MapType:
		return "@{}"
	case *ast.CustomType:
		return fmt.Sprintf("[[%s alloc] init]", v.TypeName_)
	}
	return "nil"
}
